using System;
using System.Collections.Generic;
using UnityEngine;

// Token: 0x020001B3 RID: 435
public class AENEOOFMBKE : KEPNAIFBDKF
{
	// Token: 0x06006183 RID: 24963 RVA: 0x002D5F30 File Offset: 0x002D4130
	public virtual void KJFNHNJEADK(bool CFMPGCJMHJM)
	{
		bool flag = this.EKPPDKEAAMG(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 793f, 46f), string.Concat(this.OHNAHKMBABD ? 1 : 1));
		}
		base.FCCFIHJKFNK(CFMPGCJMHJM);
	}

	// Token: 0x06006184 RID: 24964 RVA: 0x002D5FEC File Offset: 0x002D41EC
	private void KPIOHFIFEKM(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.IKGFHGKKCPG.CHPPAAAAJFC(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.IKGFHGKKCPG.BFHKBOPOFGB = false;
			FBFJFAKAGJG.IKGFHGKKCPG.KMOGGCNEKPB("OfficeSittingReading", 400f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.LMGDONLPHBJ("post_22", 483f);
	}

	// Token: 0x06006185 RID: 24965 RVA: 0x002D6090 File Offset: 0x002D4290
	private void DBKIAPEPBME(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.JFIDAGABKID().KGKCOLCPIMD(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.FIHNMPAMAFE("_Offsets", 405f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = false;
		}
	}

	// Token: 0x06006186 RID: 24966 RVA: 0x002D6114 File Offset: 0x002D4314
	public virtual void BLGIOPMGMPG(bool CFMPGCJMHJM)
	{
		bool flag = this.KLDJIGOOFPB(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 85f, 639f), string.Concat(this.OHNAHKMBABD ? 0 : 1));
		}
		base.HCHJHBGEGMP(CFMPGCJMHJM);
	}

	// Token: 0x06006187 RID: 24967 RVA: 0x002D61D0 File Offset: 0x002D43D0
	public virtual void FHAHIOKONND()
	{
		if (this.OHNAHKMBABD)
		{
			MDEKJCCIDIA.IKGFHGKKCPG.ABLFGLMKPNO = false;
			MDEKJCCIDIA.IKGFHGKKCPG.AMBNJGDIDED = this.APABMACIAOK;
			MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = this.JOONFGABJEA;
			if (!this.ICBPAMNOHHM(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC))
			{
				MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = -1;
			}
		}
		base.NLLHGPLNPFN();
	}

	// Token: 0x06006188 RID: 24968 RVA: 0x002D6233 File Offset: 0x002D4433
	public void DCDAAOHNNOO(string DCCPCBLODIG)
	{
		this.FLBHDKHKAPM = JLFJEGIPIMM.PKGMBFEMKGP().FGCOGEFACJJ(DCCPCBLODIG);
		this.MGLECJKFBCN = true;
	}

	// Token: 0x06006189 RID: 24969 RVA: 0x002D6250 File Offset: 0x002D4450
	private bool LBGFMFHGNCJ(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE == null || (!this.OAJFBGDGGHD && MEJMEKODJAE.ICOFLHIIBCP) || ((this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (!this.MGLECJKFBCN && !JLFJEGIPIMM.MHFDIJGJGBJ().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM)) && false);
	}

	// Token: 0x0600618A RID: 24970 RVA: 0x002D62AE File Offset: 0x002D44AE
	public EKBAPCMPANI FDCGELJLOEI()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.EHHKCFOAKAI(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x0600618B RID: 24971 RVA: 0x002D62D4 File Offset: 0x002D44D4
	private void ODMDGCOHCKM(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.IKGFHGKKCPG.IEHLDAKIIDF(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.DIHKGFJGMBE("demoVector2", 165f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = true;
		}
	}

	// Token: 0x0600618C RID: 24972 RVA: 0x002D6358 File Offset: 0x002D4558
	private bool KBBOMGFKEOM(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE != null && ((!this.OAJFBGDGGHD && MEJMEKODJAE.ICOFLHIIBCP) || (!this.PBHHLLKCICM && !MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) || (!this.MGLECJKFBCN && !JLFJEGIPIMM.IKGFHGKKCPG.EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM) && false));
	}

	// Token: 0x0600618D RID: 24973 RVA: 0x002D63B8 File Offset: 0x002D45B8
	public virtual void GELIPMEBFLE()
	{
		if (this.OHNAHKMBABD)
		{
			MDEKJCCIDIA.IKGFHGKKCPG.ABLFGLMKPNO = false;
			MDEKJCCIDIA.IKGFHGKKCPG.AMBNJGDIDED = this.APABMACIAOK;
			MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = this.JOONFGABJEA;
			if (!this.LCIPMAMCPLF(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC))
			{
				MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = -1;
			}
		}
		base.BKHMJNDBHCO();
	}

	// Token: 0x0600618E RID: 24974 RVA: 0x002D641C File Offset: 0x002D461C
	private bool JGGBILCFMKJ(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE != null && ((!this.OAJFBGDGGHD && MEJMEKODJAE.ICOFLHIIBCP) || (!this.PBHHLLKCICM && !MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) || (!this.MGLECJKFBCN && !JLFJEGIPIMM.PKGMBFEMKGP().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM)));
	}

	// Token: 0x0600618F RID: 24975 RVA: 0x002D647C File Offset: 0x002D467C
	public virtual void BCLGMIJEAJL(bool CFMPGCJMHJM)
	{
		bool flag = this.MPJEAGICLPH(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 1446f, 934f), string.Concat(this.OHNAHKMBABD ? 1 : 0));
		}
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006190 RID: 24976 RVA: 0x002D6538 File Offset: 0x002D4738
	private void ILPPFLKDIHJ(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.IKGFHGKKCPG.GLPNNGNMHOO(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.GGFHIFPFEBI("Hidden/Post FX/Temporal Anti-aliasing", 322f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.MNJNNDHCDGG().BFHKBOPOFGB = false;
		}
	}

	// Token: 0x06006191 RID: 24977 RVA: 0x002D65BC File Offset: 0x002D47BC
	public virtual void DBHACAENJOE(bool CFMPGCJMHJM)
	{
		bool flag = this.EKPPDKEAAMG(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 362f, 1676f), string.Concat(this.OHNAHKMBABD ? 1 : 0));
		}
		base.FCCFIHJKFNK(CFMPGCJMHJM);
	}

	// Token: 0x06006192 RID: 24978 RVA: 0x002D6678 File Offset: 0x002D4878
	private void JNJJFFOIPMH(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.IKGFHGKKCPG.HFBKHEHNCPO(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.DAOCDJPLEPE("", 1567f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.IKGFHGKKCPG.BFHKBOPOFGB = true;
		}
	}

	// Token: 0x06006193 RID: 24979 RVA: 0x002D66FC File Offset: 0x002D48FC
	public virtual void BADHPFPMHIO()
	{
		if (this.OHNAHKMBABD)
		{
			MDEKJCCIDIA.IKGFHGKKCPG.ABLFGLMKPNO = false;
			MDEKJCCIDIA.IKGFHGKKCPG.AMBNJGDIDED = this.APABMACIAOK;
			MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = this.JOONFGABJEA;
			if (!this.LBGFMFHGNCJ(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC))
			{
				MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = -1;
			}
		}
		base.OKLHKBMOLHN();
	}

	// Token: 0x06006194 RID: 24980 RVA: 0x002D6760 File Offset: 0x002D4960
	public virtual void MGJDALDLMJK()
	{
		if (this.OHNAHKMBABD)
		{
			MDEKJCCIDIA.IKGFHGKKCPG.ABLFGLMKPNO = true;
			MDEKJCCIDIA.IKGFHGKKCPG.AMBNJGDIDED = this.APABMACIAOK;
			MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = this.JOONFGABJEA;
			if (!this.AJBKJEGFHAB(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC))
			{
				MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = -1;
			}
		}
		base.ECMIKEAHNIE();
	}

	// Token: 0x06006195 RID: 24981 RVA: 0x002D67C4 File Offset: 0x002D49C4
	public virtual void ODHMHPKOAMA(bool CFMPGCJMHJM)
	{
		bool flag = this.LBGFMFHGNCJ(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 973f, 254f), string.Concat(this.OHNAHKMBABD ? 0 : 0));
		}
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006196 RID: 24982 RVA: 0x002D6880 File Offset: 0x002D4A80
	private void FBJDJEPOIDB(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.IKGFHGKKCPG.FDMNKDONMFM(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.JFIDAGABKID().BFHKBOPOFGB = false;
			FBFJFAKAGJG.IKGFHGKKCPG.DIHKGFJGMBE("GiantGrabIdle2", 1188f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.CHCGCGBDPLP("______________________________", 1845f);
	}

	// Token: 0x06006197 RID: 24983 RVA: 0x002D6924 File Offset: 0x002D4B24
	private void AEGMNMBNDFO(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.IKGFHGKKCPG.FDMNKDONMFM(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.JFIDAGABKID().BFHKBOPOFGB = true;
			FBFJFAKAGJG.IKGFHGKKCPG.CHCGCGBDPLP("^(", 1693f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.DIHKGFJGMBE("ALP=", 494f);
	}

	// Token: 0x06006198 RID: 24984 RVA: 0x002D69C8 File Offset: 0x002D4BC8
	private bool EKPPDKEAAMG(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE == null || ((this.OAJFBGDGGHD || !MEJMEKODJAE.ICOFLHIIBCP) && (this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (this.MGLECJKFBCN || JLFJEGIPIMM.NNEAHAFBOHC().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM)));
	}

	// Token: 0x06006199 RID: 24985 RVA: 0x002D6A28 File Offset: 0x002D4C28
	private void MFGFGILNKGO(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.MNJNNDHCDGG().GLPNNGNMHOO(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.DIHKGFJGMBE("IceHockeyPassLeft", 332f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.JFIDAGABKID().BFHKBOPOFGB = false;
		}
	}

	// Token: 0x0600619A RID: 24986 RVA: 0x002D6AAC File Offset: 0x002D4CAC
	private bool DGKEHMMOPLP(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE == null || ((this.OAJFBGDGGHD || !MEJMEKODJAE.ICOFLHIIBCP) && (this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (this.MGLECJKFBCN || JLFJEGIPIMM.PKGMBFEMKGP().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM)));
	}

	// Token: 0x0600619B RID: 24987 RVA: 0x002D6B0C File Offset: 0x002D4D0C
	private bool CDPIBALBOGC(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE == null || ((this.OAJFBGDGGHD || !MEJMEKODJAE.ICOFLHIIBCP) && ((!this.PBHHLLKCICM && !MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) || (!this.MGLECJKFBCN && !JLFJEGIPIMM.NNEAHAFBOHC().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM))));
	}

	// Token: 0x0600619C RID: 24988 RVA: 0x002D6B6C File Offset: 0x002D4D6C
	private bool ICBPAMNOHHM(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE != null && (this.OAJFBGDGGHD || !MEJMEKODJAE.ICOFLHIIBCP) && (this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (this.MGLECJKFBCN || JLFJEGIPIMM.PKGMBFEMKGP().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM) || true);
	}

	// Token: 0x0600619D RID: 24989 RVA: 0x002D6BCA File Offset: 0x002D4DCA
	public void OPLOEIDILFI(string DCCPCBLODIG)
	{
		this.FLBHDKHKAPM = JLFJEGIPIMM.PKGMBFEMKGP().HJKCDNIECNI(DCCPCBLODIG);
		this.MGLECJKFBCN = false;
	}

	// Token: 0x17000167 RID: 359
	// (set) Token: 0x0600619E RID: 24990 RVA: 0x002D6BE4 File Offset: 0x002D4DE4
	public string EBALPPCAHNI
	{
		set
		{
			this.FLBHDKHKAPM = JLFJEGIPIMM.IKGFHGKKCPG.HJKCDNIECNI(value);
			this.MGLECJKFBCN = false;
		}
	}

	// Token: 0x0600619F RID: 24991 RVA: 0x002D6C00 File Offset: 0x002D4E00
	private bool MMLLCAPHKIE(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE == null || (!this.OAJFBGDGGHD && MEJMEKODJAE.ICOFLHIIBCP) || ((this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (!this.MGLECJKFBCN && !JLFJEGIPIMM.NNEAHAFBOHC().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM)) && false);
	}

	// Token: 0x060061A0 RID: 24992 RVA: 0x002D6C60 File Offset: 0x002D4E60
	public AENEOOFMBKE(ONKDCGNBALK OCBAOFLJBGP, float POFBHAEFJNE, float AIIFDJADHJP, int MNOGMHMJLLB, int FADJLIMBINH = 51) : base(OCBAOFLJBGP, POFBHAEFJNE, AIIFDJADHJP, null, 0)
	{
		this.APABMACIAOK = FADJLIMBINH;
		this.JOONFGABJEA = MNOGMHMJLLB;
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.EHHKCFOAKAI(this.APABMACIAOK, this.JOONFGABJEA);
		this.KPLMFNIFPMM = false;
		this.KNIOGNKKINO = 12;
		this.FJBIDGIINCP = new ONKDCGNBALK.CMMHGMILOIM(this.HGIKJHDDAAE);
		this.ENCPJNMMMJI = new ONKDCGNBALK.CMMHGMILOIM(this.BMMLFCBGDOD);
	}

	// Token: 0x060061A1 RID: 24993 RVA: 0x002D6CF8 File Offset: 0x002D4EF8
	public virtual void HCJHIMJIOGJ(bool CFMPGCJMHJM)
	{
		bool flag = this.MHBODPKEMGF(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 1565f, 501f), string.Concat(this.OHNAHKMBABD ? 1 : 1));
		}
		base.FCCFIHJKFNK(CFMPGCJMHJM);
	}

	// Token: 0x060061A2 RID: 24994 RVA: 0x002D62AE File Offset: 0x002D44AE
	public EKBAPCMPANI OOEMCNNDLOC()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.EHHKCFOAKAI(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061A3 RID: 24995 RVA: 0x002D6DB3 File Offset: 0x002D4FB3
	public void IOOMFNMNOGP(string DCCPCBLODIG)
	{
		this.FLBHDKHKAPM = JLFJEGIPIMM.PKGMBFEMKGP().KFDOBDHOPLK(DCCPCBLODIG);
		this.MGLECJKFBCN = true;
	}

	// Token: 0x060061A4 RID: 24996 RVA: 0x002D6DD0 File Offset: 0x002D4FD0
	private void GEDCFFLFKLB(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.MNJNNDHCDGG().HILJENLHLDE(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = false;
			FBFJFAKAGJG.IKGFHGKKCPG.HJICBDFHNOO("IdleDie2", 953f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.LMGDONLPHBJ("WATER_REFLECTIVE", 1114f);
	}

	// Token: 0x060061A5 RID: 24997 RVA: 0x002D62AE File Offset: 0x002D44AE
	public EKBAPCMPANI AILMHMDPDAJ()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.EHHKCFOAKAI(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061A6 RID: 24998 RVA: 0x002D6E72 File Offset: 0x002D5072
	public EKBAPCMPANI ABKMJEBHNMC()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KIFEKEONBOL(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061A7 RID: 24999 RVA: 0x002D6E98 File Offset: 0x002D5098
	private void JOCPPNLGHCM(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.JFIDAGABKID().CHPPAAAAJFC(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.MNJNNDHCDGG().BFHKBOPOFGB = false;
			FBFJFAKAGJG.IKGFHGKKCPG.BIHLCHODGFB("MotorbikeHandstand", 1367f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.HFJOFLCNLPA("", 1958f);
	}

	// Token: 0x060061A8 RID: 25000 RVA: 0x002D6F3C File Offset: 0x002D513C
	public virtual void NEIJHIGNACK(bool CFMPGCJMHJM)
	{
		bool flag = this.BNAOBJAEINK(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 283f, 1816f), string.Concat(this.OHNAHKMBABD ? 0 : 0));
		}
		base.KCHEILEJGPL(CFMPGCJMHJM);
	}

	// Token: 0x060061A9 RID: 25001 RVA: 0x002D6FF8 File Offset: 0x002D51F8
	private bool KLDJIGOOFPB(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE == null || (!this.OAJFBGDGGHD && MEJMEKODJAE.ICOFLHIIBCP) || ((this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (!this.MGLECJKFBCN && !JLFJEGIPIMM.MHFDIJGJGBJ().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM)));
	}

	// Token: 0x060061AA RID: 25002 RVA: 0x002D7058 File Offset: 0x002D5258
	public override void FKMLCFCDJAD()
	{
		if (this.OHNAHKMBABD)
		{
			MDEKJCCIDIA.IKGFHGKKCPG.ABLFGLMKPNO = false;
			MDEKJCCIDIA.IKGFHGKKCPG.AMBNJGDIDED = this.APABMACIAOK;
			MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = this.JOONFGABJEA;
			if (!this.FEHKMMILPLH(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC))
			{
				MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = -1;
			}
		}
		base.NLLHGPLNPFN();
	}

	// Token: 0x060061AB RID: 25003 RVA: 0x002D70BB File Offset: 0x002D52BB
	public EKBAPCMPANI MCKPBBIJGKF()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.EJFELLJIACI(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061AC RID: 25004 RVA: 0x002D6E72 File Offset: 0x002D5072
	public EKBAPCMPANI MLIPJMDCBFP()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KIFEKEONBOL(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061AD RID: 25005 RVA: 0x002D70E0 File Offset: 0x002D52E0
	private void AFHOMGMKNNL(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.JFIDAGABKID().IEHLDAKIIDF(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.IAIFBJJHLOA("Near", 1640f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = true;
		}
	}

	// Token: 0x060061AE RID: 25006 RVA: 0x002D7164 File Offset: 0x002D5364
	private void BPBDODINFDD(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.HMJJPNDEKPP().IJAEDDCCNHG(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.IKGFHGKKCPG.BFHKBOPOFGB = false;
			FBFJFAKAGJG.IKGFHGKKCPG.FIHNMPAMAFE("move", 547f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.GAFOHKNHFOA("KatanaReady", 446f);
	}

	// Token: 0x060061AF RID: 25007 RVA: 0x002D7206 File Offset: 0x002D5406
	public void HHDGMAMONGP(string DCCPCBLODIG)
	{
		this.FLBHDKHKAPM = JLFJEGIPIMM.IKGFHGKKCPG.FGCOGEFACJJ(DCCPCBLODIG);
		this.MGLECJKFBCN = true;
	}

	// Token: 0x060061B0 RID: 25008 RVA: 0x002D7220 File Offset: 0x002D5420
	public virtual void CMECHJMLPGD(bool CFMPGCJMHJM)
	{
		bool flag = this.JGGBILCFMKJ(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 1076f, 589f), string.Concat(this.OHNAHKMBABD ? 1 : 0));
		}
		base.HCHJHBGEGMP(CFMPGCJMHJM);
	}

	// Token: 0x060061B1 RID: 25009 RVA: 0x002D72DC File Offset: 0x002D54DC
	public virtual void OEGEMMPIIPC(bool CFMPGCJMHJM)
	{
		bool flag = this.LJHNLNPIEBD(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 618f, 631f), string.Concat(this.OHNAHKMBABD ? 1 : 1));
		}
		base.KCHEILEJGPL(CFMPGCJMHJM);
	}

	// Token: 0x060061B2 RID: 25010 RVA: 0x002D7398 File Offset: 0x002D5598
	private void HPJJIPBNAME(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.IKGFHGKKCPG.FDMNKDONMFM(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.MNJNNDHCDGG().BFHKBOPOFGB = false;
			FBFJFAKAGJG.IKGFHGKKCPG.HJICBDFHNOO("Katana", 378f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.KMOGGCNEKPB("Flap_08.wav", 831f);
	}

	// Token: 0x060061B3 RID: 25011 RVA: 0x002D743C File Offset: 0x002D563C
	public virtual void DLBGNLEIMPB(bool CFMPGCJMHJM)
	{
		bool flag = this.KEECEEFCGKF(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 1267f, 1660f), string.Concat(this.OHNAHKMBABD ? 0 : 1));
		}
		base.FCCFIHJKFNK(CFMPGCJMHJM);
	}

	// Token: 0x060061B4 RID: 25012 RVA: 0x002D74F8 File Offset: 0x002D56F8
	private void NIPHGAHDJFE(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.JFIDAGABKID().HILJENLHLDE(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.MNJNNDHCDGG().BFHKBOPOFGB = true;
			FBFJFAKAGJG.IKGFHGKKCPG.KJDAEGFOAIO("IdleButtonPress", 78f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.IAIFBJJHLOA("11", 613f);
	}

	// Token: 0x060061B5 RID: 25013 RVA: 0x002D759C File Offset: 0x002D579C
	public virtual void LKNFIMJJPPO(bool CFMPGCJMHJM)
	{
		bool flag = this.MLJBPHHOFJB(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 1770f, 1818f), string.Concat(this.OHNAHKMBABD ? 1 : 0));
		}
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x060061B6 RID: 25014 RVA: 0x002D7658 File Offset: 0x002D5858
	private bool MPJEAGICLPH(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE != null && (this.OAJFBGDGGHD || !MEJMEKODJAE.ICOFLHIIBCP) && (this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (this.MGLECJKFBCN || JLFJEGIPIMM.PKGMBFEMKGP().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM) || true);
	}

	// Token: 0x060061B7 RID: 25015 RVA: 0x002D76B8 File Offset: 0x002D58B8
	private bool OIFGPMCBHLC(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE != null && ((!this.OAJFBGDGGHD && MEJMEKODJAE.ICOFLHIIBCP) || ((this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (!this.MGLECJKFBCN && !JLFJEGIPIMM.IKGFHGKKCPG.EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM)) && false));
	}

	// Token: 0x060061B8 RID: 25016 RVA: 0x002D7718 File Offset: 0x002D5918
	private void KFKAEICFMLE(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.HMJJPNDEKPP().CHPPAAAAJFC(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = true;
			FBFJFAKAGJG.IKGFHGKKCPG.FIHNMPAMAFE("?", 1026f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.LMGDONLPHBJ("Platform", 1097f);
	}

	// Token: 0x060061B9 RID: 25017 RVA: 0x002D77BC File Offset: 0x002D59BC
	public virtual void MKEAIAOHEEB()
	{
		if (this.OHNAHKMBABD)
		{
			MDEKJCCIDIA.IKGFHGKKCPG.ABLFGLMKPNO = false;
			MDEKJCCIDIA.IKGFHGKKCPG.AMBNJGDIDED = this.APABMACIAOK;
			MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = this.JOONFGABJEA;
			if (!this.FEHKMMILPLH(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC))
			{
				MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = -1;
			}
		}
		base.FKMLCFCDJAD();
	}

	// Token: 0x060061BA RID: 25018 RVA: 0x002D7820 File Offset: 0x002D5A20
	private void LECGKPNPEKO(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.IKGFHGKKCPG.KGKCOLCPIMD(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.CHCGCGBDPLP("WeaponStrafeRunLeft", 1091f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = false;
		}
	}

	// Token: 0x060061BB RID: 25019 RVA: 0x002D78A4 File Offset: 0x002D5AA4
	private bool JFEEJDJANGP(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE != null && ((!this.OAJFBGDGGHD && MEJMEKODJAE.ICOFLHIIBCP) || ((this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (!this.MGLECJKFBCN && !JLFJEGIPIMM.MHFDIJGJGBJ().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM))));
	}

	// Token: 0x060061BC RID: 25020 RVA: 0x002D7904 File Offset: 0x002D5B04
	private bool LCIPMAMCPLF(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE != null && (this.OAJFBGDGGHD || !MEJMEKODJAE.ICOFLHIIBCP) && (this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (this.MGLECJKFBCN || JLFJEGIPIMM.IKGFHGKKCPG.EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM));
	}

	// Token: 0x060061BD RID: 25021 RVA: 0x002D7964 File Offset: 0x002D5B64
	public virtual void GLEBDMABDBP()
	{
		if (this.OHNAHKMBABD)
		{
			MDEKJCCIDIA.IKGFHGKKCPG.ABLFGLMKPNO = false;
			MDEKJCCIDIA.IKGFHGKKCPG.AMBNJGDIDED = this.APABMACIAOK;
			MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = this.JOONFGABJEA;
			if (!this.FEHKMMILPLH(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC))
			{
				MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = -1;
			}
		}
		base.ECMIKEAHNIE();
	}

	// Token: 0x060061BE RID: 25022 RVA: 0x002D6E72 File Offset: 0x002D5072
	public EKBAPCMPANI FAJNMGGKPDE()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KIFEKEONBOL(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061BF RID: 25023 RVA: 0x002D79C8 File Offset: 0x002D5BC8
	private void EPGEIODAKAG(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.HMJJPNDEKPP().HICPILKPFLP(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.LMGDONLPHBJ("_rcIn.ogg", 933f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.JFIDAGABKID().BFHKBOPOFGB = false;
		}
	}

	// Token: 0x060061C0 RID: 25024 RVA: 0x002D7A4C File Offset: 0x002D5C4C
	private bool FEHKMMILPLH(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE == null || (!this.OAJFBGDGGHD && MEJMEKODJAE.ICOFLHIIBCP) || (!this.PBHHLLKCICM && !MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) || (!this.MGLECJKFBCN && !JLFJEGIPIMM.NNEAHAFBOHC().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM));
	}

	// Token: 0x060061C1 RID: 25025 RVA: 0x002D7AAC File Offset: 0x002D5CAC
	private void OFDEHCMEEEN(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.IKGFHGKKCPG.IHNMOJHBMNJ(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = false;
			FBFJFAKAGJG.IKGFHGKKCPG.GGFHIFPFEBI("\n", 1881f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.HFJOFLCNLPA("WizardNeoBlock", 805f);
	}

	// Token: 0x060061C2 RID: 25026 RVA: 0x002D70BB File Offset: 0x002D52BB
	public EKBAPCMPANI BHJAJMPGBFI()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.EJFELLJIACI(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061C3 RID: 25027 RVA: 0x002D7B50 File Offset: 0x002D5D50
	private void LHDKPGFLFIE(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.IKGFHGKKCPG.KGKCOLCPIMD(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.CHCGCGBDPLP("RollerBladeRoll", 1207f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = false;
		}
	}

	// Token: 0x060061C4 RID: 25028 RVA: 0x002D7BD4 File Offset: 0x002D5DD4
	private bool BNAOBJAEINK(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE == null || (!this.OAJFBGDGGHD && MEJMEKODJAE.ICOFLHIIBCP) || ((this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (this.MGLECJKFBCN || JLFJEGIPIMM.NNEAHAFBOHC().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM) || true));
	}

	// Token: 0x060061C5 RID: 25029 RVA: 0x002D7C34 File Offset: 0x002D5E34
	private bool MHBODPKEMGF(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE != null && (this.OAJFBGDGGHD || !MEJMEKODJAE.ICOFLHIIBCP) && (this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (this.MGLECJKFBCN || JLFJEGIPIMM.NNEAHAFBOHC().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM) || true);
	}

	// Token: 0x060061C6 RID: 25030 RVA: 0x002D7C94 File Offset: 0x002D5E94
	private void NHJNKAJJMFI(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.JFIDAGABKID().KGKCOLCPIMD(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.HFJOFLCNLPA("OneHandSwordIdle", 1700f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.JFIDAGABKID().BFHKBOPOFGB = true;
		}
	}

	// Token: 0x060061C7 RID: 25031 RVA: 0x002D7D18 File Offset: 0x002D5F18
	private bool CKAECFALGBO(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE != null && (this.OAJFBGDGGHD || !MEJMEKODJAE.ICOFLHIIBCP) && (this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (this.MGLECJKFBCN || JLFJEGIPIMM.NNEAHAFBOHC().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM));
	}

	// Token: 0x060061C8 RID: 25032 RVA: 0x002D70BB File Offset: 0x002D52BB
	public EKBAPCMPANI LKMPEFKNBKD()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.EJFELLJIACI(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061C9 RID: 25033 RVA: 0x002D7D78 File Offset: 0x002D5F78
	private void BMMLFCBGDOD(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.IKGFHGKKCPG.GLPNNGNMHOO(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.FIHNMPAMAFE("repair.ogg", 0.9f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.IKGFHGKKCPG.BFHKBOPOFGB = false;
		}
	}

	// Token: 0x060061CA RID: 25034 RVA: 0x002D7DFC File Offset: 0x002D5FFC
	private bool LJHNLNPIEBD(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE == null || (!this.OAJFBGDGGHD && MEJMEKODJAE.ICOFLHIIBCP) || ((this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (!this.MGLECJKFBCN && !JLFJEGIPIMM.MHFDIJGJGBJ().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM)));
	}

	// Token: 0x060061CB RID: 25035 RVA: 0x002D7E5C File Offset: 0x002D605C
	private void DJGOJIMMLMB(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.HMJJPNDEKPP().HFBKHEHNCPO(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.DIHKGFJGMBE("FistPump", 1230f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = false;
		}
	}

	// Token: 0x060061CC RID: 25036 RVA: 0x002D7EE0 File Offset: 0x002D60E0
	public virtual void FHNNBBLGFDN(bool CFMPGCJMHJM)
	{
		bool flag = this.KBBOMGFKEOM(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 399f, 1712f), string.Concat(this.OHNAHKMBABD ? 0 : 1));
		}
		base.FCCFIHJKFNK(CFMPGCJMHJM);
	}

	// Token: 0x060061CD RID: 25037 RVA: 0x002D7F9C File Offset: 0x002D619C
	private void KHLDHILACBC(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.JFIDAGABKID().FDMNKDONMFM(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.IKGFHGKKCPG.BFHKBOPOFGB = true;
			FBFJFAKAGJG.IKGFHGKKCPG.HJICBDFHNOO("Water", 1551f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.FIHNMPAMAFE("WizardBlock", 642f);
	}

	// Token: 0x060061CE RID: 25038 RVA: 0x002D803E File Offset: 0x002D623E
	public void CHAPJAPAIDP(string DCCPCBLODIG)
	{
		this.FLBHDKHKAPM = JLFJEGIPIMM.IKGFHGKKCPG.HJKCDNIECNI(DCCPCBLODIG);
		this.MGLECJKFBCN = true;
	}

	// Token: 0x060061CF RID: 25039 RVA: 0x002D70BB File Offset: 0x002D52BB
	public EKBAPCMPANI CAJAPJLOCPF()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.EJFELLJIACI(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061D0 RID: 25040 RVA: 0x002D70BB File Offset: 0x002D52BB
	public EKBAPCMPANI HKHLLGJHDCF()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.EJFELLJIACI(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061D1 RID: 25041 RVA: 0x002D6E72 File Offset: 0x002D5072
	public EKBAPCMPANI ODLNOPEKFDI()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KIFEKEONBOL(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061D2 RID: 25042 RVA: 0x002D8058 File Offset: 0x002D6258
	private void JJHBMECIJIP(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.JFIDAGABKID().IEHLDAKIIDF(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.HFJOFLCNLPA("chatconnect", 1950f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = true;
		}
	}

	// Token: 0x060061D3 RID: 25043 RVA: 0x002D6E72 File Offset: 0x002D5072
	public EKBAPCMPANI ENGOGGKIGHD()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KIFEKEONBOL(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061D4 RID: 25044 RVA: 0x002D80DC File Offset: 0x002D62DC
	public virtual void OCEGEBCJIMH()
	{
		if (this.OHNAHKMBABD)
		{
			MDEKJCCIDIA.IKGFHGKKCPG.ABLFGLMKPNO = true;
			MDEKJCCIDIA.IKGFHGKKCPG.AMBNJGDIDED = this.APABMACIAOK;
			MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = this.JOONFGABJEA;
			if (!this.MMLLCAPHKIE(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC))
			{
				MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = -1;
			}
		}
		base.FKMLCFCDJAD();
	}

	// Token: 0x060061D5 RID: 25045 RVA: 0x002D8140 File Offset: 0x002D6340
	private void KGLACLAMHCK(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.IKGFHGKKCPG.GLPNNGNMHOO(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.IAIFBJJHLOA("gamesrv1.af2.cryptodev.app", 1564f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.MNJNNDHCDGG().BFHKBOPOFGB = true;
		}
	}

	// Token: 0x060061D6 RID: 25046 RVA: 0x002D81C1 File Offset: 0x002D63C1
	public void BBONLANINKL(string DCCPCBLODIG)
	{
		this.FLBHDKHKAPM = JLFJEGIPIMM.IKGFHGKKCPG.FGCOGEFACJJ(DCCPCBLODIG);
		this.MGLECJKFBCN = false;
	}

	// Token: 0x060061D7 RID: 25047 RVA: 0x002D81DC File Offset: 0x002D63DC
	private void FHKKFLDHPGE(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.IKGFHGKKCPG.KGKCOLCPIMD(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.KMOGGCNEKPB("No klev! shance=", 1285f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = false;
		}
	}

	// Token: 0x060061D8 RID: 25048 RVA: 0x002D8260 File Offset: 0x002D6460
	public virtual void FOGCOMNGOFB(bool CFMPGCJMHJM)
	{
		bool flag = this.KLDJIGOOFPB(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 1821f, 971f), string.Concat(this.OHNAHKMBABD ? 1 : 1));
		}
		base.FCCFIHJKFNK(CFMPGCJMHJM);
	}

	// Token: 0x060061D9 RID: 25049 RVA: 0x002D831C File Offset: 0x002D651C
	private void CCGHEPIOFPE(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.HMJJPNDEKPP().IHNMOJHBMNJ(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.IKGFHGKKCPG.BFHKBOPOFGB = false;
			FBFJFAKAGJG.IKGFHGKKCPG.GGFHIFPFEBI("sunshine_ShadowCoordDepthStart", 1948f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.CHCGCGBDPLP("Sound/", 1114f);
	}

	// Token: 0x060061DA RID: 25050 RVA: 0x002D83C0 File Offset: 0x002D65C0
	private void ODCADOKOFDH(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.MNJNNDHCDGG().GLPNNGNMHOO(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.KMOGGCNEKPB("_MainTex", 327f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = false;
		}
	}

	// Token: 0x060061DB RID: 25051 RVA: 0x002D62AE File Offset: 0x002D44AE
	public EKBAPCMPANI AFOLABIACNF()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.EHHKCFOAKAI(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061DC RID: 25052 RVA: 0x002D8444 File Offset: 0x002D6644
	private void AJNPJDKCEKE(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.IKGFHGKKCPG.PFHLOHKPPEG(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.KMOGGCNEKPB("TextureLoader: ", 694f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = true;
		}
	}

	// Token: 0x060061DD RID: 25053 RVA: 0x002D84C8 File Offset: 0x002D66C8
	public virtual void JBNJOHNJPKM()
	{
		if (this.OHNAHKMBABD)
		{
			MDEKJCCIDIA.IKGFHGKKCPG.ABLFGLMKPNO = false;
			MDEKJCCIDIA.IKGFHGKKCPG.AMBNJGDIDED = this.APABMACIAOK;
			MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = this.JOONFGABJEA;
			if (!this.OIFGPMCBHLC(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC))
			{
				MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = -1;
			}
		}
		base.OKLHKBMOLHN();
	}

	// Token: 0x060061DE RID: 25054 RVA: 0x002D852C File Offset: 0x002D672C
	private bool MLJBPHHOFJB(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE != null && (this.OAJFBGDGGHD || !MEJMEKODJAE.ICOFLHIIBCP) && (this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (this.MGLECJKFBCN || JLFJEGIPIMM.NNEAHAFBOHC().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM));
	}

	// Token: 0x060061DF RID: 25055 RVA: 0x002D858C File Offset: 0x002D678C
	private void KACCEGEOELK(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.MNJNNDHCDGG().CHPPAAAAJFC(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.IKGFHGKKCPG.BFHKBOPOFGB = false;
			FBFJFAKAGJG.IKGFHGKKCPG.GAFOHKNHFOA("act_orderb_", 1452f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.GGFHIFPFEBI("Get post", 999f);
	}

	// Token: 0x060061E0 RID: 25056 RVA: 0x002D8630 File Offset: 0x002D6830
	private bool KMFKNFOBFID(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE != null && (this.OAJFBGDGGHD || !MEJMEKODJAE.ICOFLHIIBCP) && (this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (this.MGLECJKFBCN || JLFJEGIPIMM.PKGMBFEMKGP().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM));
	}

	// Token: 0x060061E1 RID: 25057 RVA: 0x002D8690 File Offset: 0x002D6890
	private bool CNCNHKIOEOO(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE != null && ((!this.OAJFBGDGGHD && MEJMEKODJAE.ICOFLHIIBCP) || ((this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (!this.MGLECJKFBCN && !JLFJEGIPIMM.PKGMBFEMKGP().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM)) && false));
	}

	// Token: 0x060061E2 RID: 25058 RVA: 0x002D86F0 File Offset: 0x002D68F0
	public override void HFJFBDPNCCB(bool CFMPGCJMHJM)
	{
		bool flag = this.LCIPMAMCPLF(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 56f, 56f), string.Concat(this.OHNAHKMBABD ? 1 : 0));
		}
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x060061E3 RID: 25059 RVA: 0x002D87AC File Offset: 0x002D69AC
	public virtual void EPHCPAOAHOP(bool CFMPGCJMHJM)
	{
		bool flag = this.JGGBILCFMKJ(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 1214f, 249f), string.Concat(this.OHNAHKMBABD ? 1 : 0));
		}
		base.KCHEILEJGPL(CFMPGCJMHJM);
	}

	// Token: 0x060061E4 RID: 25060 RVA: 0x002D8868 File Offset: 0x002D6A68
	private bool KEECEEFCGKF(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE == null || ((this.OAJFBGDGGHD || !MEJMEKODJAE.ICOFLHIIBCP) && ((!this.PBHHLLKCICM && !MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) || this.MGLECJKFBCN || JLFJEGIPIMM.NNEAHAFBOHC().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM)));
	}

	// Token: 0x060061E5 RID: 25061 RVA: 0x002D88C8 File Offset: 0x002D6AC8
	private void NHPHJJJKNBL(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.JFIDAGABKID().FDMNKDONMFM(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.MNJNNDHCDGG().BFHKBOPOFGB = false;
			FBFJFAKAGJG.IKGFHGKKCPG.GAFOHKNHFOA("Flap_04.wav", 1267f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.IAIFBJJHLOA("", 1476f);
	}

	// Token: 0x060061E6 RID: 25062 RVA: 0x002D896C File Offset: 0x002D6B6C
	private bool AJBKJEGFHAB(EKBAPCMPANI MEJMEKODJAE)
	{
		return MEJMEKODJAE == null || ((this.OAJFBGDGGHD || !MEJMEKODJAE.ICOFLHIIBCP) && (this.PBHHLLKCICM || MEJMEKODJAE.BDHHPAEHFHG.DAGKAGJCNAH) && (this.MGLECJKFBCN || JLFJEGIPIMM.MHFDIJGJGBJ().EHEMCMKMECH(MEJMEKODJAE.MBKMKGABBGE, this.FLBHDKHKAPM)));
	}

	// Token: 0x060061E7 RID: 25063 RVA: 0x002D89CC File Offset: 0x002D6BCC
	private void HGIKJHDDAAE(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.IKGFHGKKCPG.HILJENLHLDE(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.IKGFHGKKCPG.BFHKBOPOFGB = true;
			FBFJFAKAGJG.IKGFHGKKCPG.FIHNMPAMAFE("Flap_08.wav", 0.5f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.FIHNMPAMAFE("Flap_08.wav", 0.5f);
	}

	// Token: 0x060061E8 RID: 25064 RVA: 0x002D8A70 File Offset: 0x002D6C70
	public virtual void FCEMLCJHBGL()
	{
		if (this.OHNAHKMBABD)
		{
			MDEKJCCIDIA.IKGFHGKKCPG.ABLFGLMKPNO = true;
			MDEKJCCIDIA.IKGFHGKKCPG.AMBNJGDIDED = this.APABMACIAOK;
			MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = this.JOONFGABJEA;
			if (!this.LCIPMAMCPLF(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC))
			{
				MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = -1;
			}
		}
		base.BKHMJNDBHCO();
	}

	// Token: 0x060061E9 RID: 25065 RVA: 0x002D8AD3 File Offset: 0x002D6CD3
	public void GLMFBHEIHBP(string DCCPCBLODIG)
	{
		this.FLBHDKHKAPM = JLFJEGIPIMM.MHFDIJGJGBJ().HJKCDNIECNI(DCCPCBLODIG);
		this.MGLECJKFBCN = false;
	}

	// Token: 0x060061EA RID: 25066 RVA: 0x002D8AF0 File Offset: 0x002D6CF0
	public virtual void HAFLDKCLKKL()
	{
		if (this.OHNAHKMBABD)
		{
			MDEKJCCIDIA.IKGFHGKKCPG.ABLFGLMKPNO = false;
			MDEKJCCIDIA.IKGFHGKKCPG.AMBNJGDIDED = this.APABMACIAOK;
			MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = this.JOONFGABJEA;
			if (!this.MMLLCAPHKIE(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC))
			{
				MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = -1;
			}
		}
		base.BKHMJNDBHCO();
	}

	// Token: 0x060061EB RID: 25067 RVA: 0x002D8B53 File Offset: 0x002D6D53
	public void CIKEHPNOLFH(string DCCPCBLODIG)
	{
		this.FLBHDKHKAPM = JLFJEGIPIMM.NNEAHAFBOHC().HJKCDNIECNI(DCCPCBLODIG);
		this.MGLECJKFBCN = true;
	}

	// Token: 0x060061EC RID: 25068 RVA: 0x002D8B70 File Offset: 0x002D6D70
	public override void BKHMJNDBHCO()
	{
		if (this.OHNAHKMBABD)
		{
			MDEKJCCIDIA.IKGFHGKKCPG.ABLFGLMKPNO = true;
			MDEKJCCIDIA.IKGFHGKKCPG.AMBNJGDIDED = this.APABMACIAOK;
			MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = this.JOONFGABJEA;
			if (!this.LCIPMAMCPLF(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC))
			{
				MDEKJCCIDIA.IKGFHGKKCPG.OJKBEDCFFND = -1;
			}
		}
		base.BKHMJNDBHCO();
	}

	// Token: 0x060061ED RID: 25069 RVA: 0x002D6E72 File Offset: 0x002D5072
	public EKBAPCMPANI BCOEDEGBJKL()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KIFEKEONBOL(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061EE RID: 25070 RVA: 0x002D8BD4 File Offset: 0x002D6DD4
	private void PLCPMHIDOBF(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC != null)
		{
			JDCEFOFMGHB.IKGFHGKKCPG.IEHLDAKIIDF(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
			this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC;
			FBFJFAKAGJG.IKGFHGKKCPG.KJDAEGFOAIO("Bend Constraint is referencing to a bone '", 1761f);
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC.BFHKBOPOFGB = true;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = null;
			JDCEFOFMGHB.JFIDAGABKID().BFHKBOPOFGB = false;
		}
	}

	// Token: 0x060061EF RID: 25071 RVA: 0x002D62AE File Offset: 0x002D44AE
	public EKBAPCMPANI LBMJLKIMMNL()
	{
		this.OBLONDPEGLN = MDEKJCCIDIA.IKGFHGKKCPG.EHHKCFOAKAI(this.APABMACIAOK, this.JOONFGABJEA);
		return this.OBLONDPEGLN;
	}

	// Token: 0x060061F0 RID: 25072 RVA: 0x002D8C58 File Offset: 0x002D6E58
	public virtual void FDCOFCOIHEH(bool CFMPGCJMHJM)
	{
		bool flag = this.KLDJIGOOFPB(MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC);
		GUI.DrawTexture(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, this.OCHCODJIPHJ.width, this.OCHCODJIPHJ.height), flag ? GameInterface.getI.invEmptyCellSelect : GameInterface.getI.invEmptyCell);
		if (Application.isEditor)
		{
			GUI.Label(new Rect(this.OCHCODJIPHJ.x, this.OCHCODJIPHJ.y, 1703f, 436f), string.Concat(this.OHNAHKMBABD ? 1 : 0));
		}
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x060061F1 RID: 25073 RVA: 0x002D8D14 File Offset: 0x002D6F14
	private void HDPFHLCIFAN(ONKDCGNBALK JMAKEAHMLMI)
	{
		if (!this.OHNAHKMBABD)
		{
			return;
		}
		if (this.OBLONDPEGLN == null)
		{
			return;
		}
		if (JDCEFOFMGHB.JFIDAGABKID().CHPPAAAAJFC(MDEKJCCIDIA.IKGFHGKKCPG.NGKLLCCLFCM) != null)
		{
			this.OBLONDPEGLN.BFHKBOPOFGB = false;
			MDEKJCCIDIA.IKGFHGKKCPG.KKLEEIBNIBC = this.OBLONDPEGLN;
			JDCEFOFMGHB.HMJJPNDEKPP().BFHKBOPOFGB = true;
			FBFJFAKAGJG.IKGFHGKKCPG.LMGDONLPHBJ("_TurnReg.ogg", 247f);
			return;
		}
		if (this.FJBIDGIINCP != null)
		{
			this.FJBIDGIINCP(this);
		}
		else
		{
			this.OBLONDPEGLN = null;
		}
		FBFJFAKAGJG.IKGFHGKKCPG.DIHKGFJGMBE("usetime", 538f);
	}

	// Token: 0x04000E0A RID: 3594
	public int APABMACIAOK;

	// Token: 0x04000E0B RID: 3595
	public int JOONFGABJEA;

	// Token: 0x04000E0C RID: 3596
	public bool OAJFBGDGGHD = true;

	// Token: 0x04000E0D RID: 3597
	public bool PBHHLLKCICM = true;

	// Token: 0x04000E0E RID: 3598
	public bool MGLECJKFBCN = true;

	// Token: 0x04000E0F RID: 3599
	public List<int> FLBHDKHKAPM = new List<int>();
}
