using System;

// Token: 0x0200009A RID: 154
public struct AOAHEAEHFLC
{
	// Token: 0x06002088 RID: 8328 RVA: 0x000F66D2 File Offset: 0x000F48D2
	public static AOAHEAEHFLC KHDNKBMIPOO(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x06002089 RID: 8329 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC BLHEABLLIDP(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x0600208A RID: 8330 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC PEGFNFPFKGJ(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x0600208B RID: 8331 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC JHIBOEFONII(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x0600208C RID: 8332 RVA: 0x000F6735 File Offset: 0x000F4935
	public static AOAHEAEHFLC EHCJMMGKMPI(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML);
	}

	// Token: 0x0600208D RID: 8333 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC EBGNKBEBBLD(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x0600208E RID: 8334 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC EGIABFFGIGH(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x0600208F RID: 8335 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC LALGKKNAAGK(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x06002090 RID: 8336 RVA: 0x000F679B File Offset: 0x000F499B
	public static AOAHEAEHFLC OGDEKOGEJIG(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML);
	}

	// Token: 0x06002091 RID: 8337 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC LEFBBCNOAJD(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x06002092 RID: 8338 RVA: 0x000F6735 File Offset: 0x000F4935
	public static AOAHEAEHFLC NKLDPHFDFNB(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML);
	}

	// Token: 0x06002093 RID: 8339 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC BKEMNEKNEFJ(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x06002094 RID: 8340 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC EDHEGCDMPCL(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x06002095 RID: 8341 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC LKPKJBIGAMF(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x06002096 RID: 8342 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC KKELDFDJJAG(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x06002097 RID: 8343 RVA: 0x000F66D2 File Offset: 0x000F48D2
	public static AOAHEAEHFLC NIJPDFFJFDP(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x06002098 RID: 8344 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC AHAHNPGIFEF(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x06002099 RID: 8345 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC FCINJHKJIHA(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x0600209A RID: 8346 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC KMHCCBEJGKM(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x0600209B RID: 8347 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC EPKDCBPCHNC(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x0600209C RID: 8348 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC JHDHKJPPFHI(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x0600209D RID: 8349 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC KLEOBLIMCJO(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x0600209E RID: 8350 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC AKCFJCCIMAP(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x0600209F RID: 8351 RVA: 0x000F679B File Offset: 0x000F499B
	public static AOAHEAEHFLC JFHPHEDGFOL(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML);
	}

	// Token: 0x060020A0 RID: 8352 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC BBEKGCPMDOF(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020A1 RID: 8353 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC CMKCHHHJKLA(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020A2 RID: 8354 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC PICCFFHAMAG(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020A3 RID: 8355 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC DKCGLAMKDPP(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020A4 RID: 8356 RVA: 0x000F6735 File Offset: 0x000F4935
	public static AOAHEAEHFLC PPBHEODICFA(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML);
	}

	// Token: 0x060020A5 RID: 8357 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC ODBJPCFOJJB(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020A6 RID: 8358 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC COOPMDCDJEC(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x060020A7 RID: 8359 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC GGFAGMDPNHB(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020A8 RID: 8360 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC PPBHEODICFA(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020A9 RID: 8361 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC AGFLENMNGFB(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020AA RID: 8362 RVA: 0x000F679B File Offset: 0x000F499B
	public static AOAHEAEHFLC OLEDALCBHLA(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML);
	}

	// Token: 0x060020AB RID: 8363 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC PGPHGBNBKCO(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020AC RID: 8364 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC ECKKCOGLHPE(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020AD RID: 8365 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC PAIKMKFILMD(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020AE RID: 8366 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC PCHIFEMKMHH(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020AF RID: 8367 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC JFLOHKDMMLH(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x060020B0 RID: 8368 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC DFLKALJLCBP(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020B1 RID: 8369 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC HAKJGJPACPG(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020B2 RID: 8370 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC ABEIBCAFMNC(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x060020B3 RID: 8371 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC PANGFJNOJHB(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020B4 RID: 8372 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC KFELEJAAPME(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020B5 RID: 8373 RVA: 0x000F66D2 File Offset: 0x000F48D2
	public static AOAHEAEHFLC FFJBOLKNHLD(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020B6 RID: 8374 RVA: 0x000F66D2 File Offset: 0x000F48D2
	public static AOAHEAEHFLC AJEBHJFEOEJ(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020B7 RID: 8375 RVA: 0x000F6735 File Offset: 0x000F4935
	public static AOAHEAEHFLC BGALHPLHOFM(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML);
	}

	// Token: 0x060020B8 RID: 8376 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC JAJGLPAHJLL(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020B9 RID: 8377 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC HBGADBDLHDP(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020BA RID: 8378 RVA: 0x000F6735 File Offset: 0x000F4935
	public static AOAHEAEHFLC KEFGPIBNJFF(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML);
	}

	// Token: 0x060020BB RID: 8379 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC DECLHFOBJMA(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020BC RID: 8380 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC PEFLKPDGOAO(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x060020BD RID: 8381 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC DHONLBCFNBH(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020BE RID: 8382 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC CFBPAJKMPFM(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020BF RID: 8383 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC OEKGHIPOEPC(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020C0 RID: 8384 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC EHOHJCMFCJB(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020C1 RID: 8385 RVA: 0x000F6735 File Offset: 0x000F4935
	public static AOAHEAEHFLC HHBIOJODHLD(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML);
	}

	// Token: 0x060020C2 RID: 8386 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC FAKMFFFOGPH(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020C3 RID: 8387 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC ENKAJPKKNHK(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020C4 RID: 8388 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC JIAJIPEHCEM(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020C5 RID: 8389 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC EOPIAAALCKC(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020C6 RID: 8390 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC KHOAKJPNLKA(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020C7 RID: 8391 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC IHGCNKABBHN(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020C8 RID: 8392 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC ENMDIOGKNKO(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020C9 RID: 8393 RVA: 0x000F66D2 File Offset: 0x000F48D2
	public static AOAHEAEHFLC FGDFOOKKLFI(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020CA RID: 8394 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC BMMIBAJKODI(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020CB RID: 8395 RVA: 0x000F66D2 File Offset: 0x000F48D2
	public static AOAHEAEHFLC APBNHMGGDEM(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020CC RID: 8396 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC DNHIPFNDPHE(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020CD RID: 8397 RVA: 0x000F67B2 File Offset: 0x000F49B2
	public AOAHEAEHFLC(int OCNGPCPMCPM, int ADMFAEOOOHD)
	{
		this.OCNGPCPMCPM = OCNGPCPMCPM;
		this.ADMFAEOOOHD = ADMFAEOOOHD;
	}

	// Token: 0x060020CE RID: 8398 RVA: 0x000F66D2 File Offset: 0x000F48D2
	public static AOAHEAEHFLC IEDOOPFCLLJ(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020CF RID: 8399 RVA: 0x000F679B File Offset: 0x000F499B
	public static AOAHEAEHFLC OFIMDBIHEDF(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML);
	}

	// Token: 0x060020D0 RID: 8400 RVA: 0x000F6735 File Offset: 0x000F4935
	public static AOAHEAEHFLC JNBIHOPKKEO(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML);
	}

	// Token: 0x060020D1 RID: 8401 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC BIJIICONMHE(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020D2 RID: 8402 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC EJNFEMNJMPP(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020D3 RID: 8403 RVA: 0x000F66D2 File Offset: 0x000F48D2
	public static AOAHEAEHFLC OOEFFGJHJHC(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020D4 RID: 8404 RVA: 0x000F6735 File Offset: 0x000F4935
	public static AOAHEAEHFLC EHJPKDDFAFG(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML);
	}

	// Token: 0x060020D5 RID: 8405 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC IOPDNKMJEHC(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020D6 RID: 8406 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC GDOLJEABDCN(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020D7 RID: 8407 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC POKNFCILCBN(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020D8 RID: 8408 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC FAFNDLCMLOK(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020D9 RID: 8409 RVA: 0x000F679B File Offset: 0x000F499B
	public static AOAHEAEHFLC MHDGPGNBCBE(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML);
	}

	// Token: 0x060020DA RID: 8410 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC NHIJGBPBLFC(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020DB RID: 8411 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC JOJBFMIKMIO(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x060020DC RID: 8412 RVA: 0x000F6735 File Offset: 0x000F4935
	public static AOAHEAEHFLC JCOIBBKIMIB(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML);
	}

	// Token: 0x060020DD RID: 8413 RVA: 0x000F679B File Offset: 0x000F499B
	public static AOAHEAEHFLC PICCFFHAMAG(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML);
	}

	// Token: 0x060020DE RID: 8414 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC LMAAGFEGFFO(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020DF RID: 8415 RVA: 0x000F6735 File Offset: 0x000F4935
	public static AOAHEAEHFLC MCNCJNCLHGA(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML);
	}

	// Token: 0x060020E0 RID: 8416 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC LJHJKPOIPEF(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x060020E1 RID: 8417 RVA: 0x000F679B File Offset: 0x000F499B
	public static AOAHEAEHFLC CIPGLDFOEJD(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML);
	}

	// Token: 0x060020E2 RID: 8418 RVA: 0x000F6735 File Offset: 0x000F4935
	public static AOAHEAEHFLC AFPIPHPEBGB(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML);
	}

	// Token: 0x060020E3 RID: 8419 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC FGDFOOKKLFI(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x060020E4 RID: 8420 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC NHIJGBPBLFC(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020E5 RID: 8421 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC GMOGNMIFECM(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020E6 RID: 8422 RVA: 0x000F66D2 File Offset: 0x000F48D2
	public static AOAHEAEHFLC KCPEOPPKBHA(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020E7 RID: 8423 RVA: 0x000F6735 File Offset: 0x000F4935
	public static AOAHEAEHFLC LBPMJHPPBDJ(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML);
	}

	// Token: 0x060020E8 RID: 8424 RVA: 0x000F679B File Offset: 0x000F499B
	public static AOAHEAEHFLC BCLJKBLBHCG(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML);
	}

	// Token: 0x060020E9 RID: 8425 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC JJAOIKKMPCC(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020EA RID: 8426 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC FILPMHFGAFL(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020EB RID: 8427 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC OAKKCHDJDDB(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020EC RID: 8428 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC IJDBECJHNJO(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020ED RID: 8429 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC BINHHOPNAMN(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020EE RID: 8430 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC LIFBJHJPANJ(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x060020EF RID: 8431 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC PBCMPOOOLFI(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020F0 RID: 8432 RVA: 0x000F6784 File Offset: 0x000F4984
	public static AOAHEAEHFLC LBFKEADHKHO(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML);
	}

	// Token: 0x060020F1 RID: 8433 RVA: 0x000F66D2 File Offset: 0x000F48D2
	public static AOAHEAEHFLC EBLHNINGJDH(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM / HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD / HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020F2 RID: 8434 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC LAMJLEBMMNG(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020F3 RID: 8435 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC GNJFCFONNEG(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020F4 RID: 8436 RVA: 0x000F6763 File Offset: 0x000F4963
	public static AOAHEAEHFLC GHCDCKOIDOJ(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020F5 RID: 8437 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC AAKMICCPPLG(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020F6 RID: 8438 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC JLKEPPCCJBK(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020F7 RID: 8439 RVA: 0x000F679B File Offset: 0x000F499B
	public static AOAHEAEHFLC NDCIJMNIEMG(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM + HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD + HHAGIHEGFML);
	}

	// Token: 0x060020F8 RID: 8440 RVA: 0x000F66F3 File Offset: 0x000F48F3
	public static AOAHEAEHFLC GNILPKLBCDK(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020F9 RID: 8441 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC ELIGHHMMPCJ(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020FA RID: 8442 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC MDPAMKBEINI(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020FB RID: 8443 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC FNKBFNALECC(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020FC RID: 8444 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC KKCBCHMCDHI(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020FD RID: 8445 RVA: 0x000F6714 File Offset: 0x000F4914
	public static AOAHEAEHFLC KKDLNGKBDKC(AOAHEAEHFLC EGABJKIFAON, AOAHEAEHFLC HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM - HHAGIHEGFML.OCNGPCPMCPM, EGABJKIFAON.ADMFAEOOOHD - HHAGIHEGFML.ADMFAEOOOHD);
	}

	// Token: 0x060020FE RID: 8446 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC KBBFLCMMMAJ(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x060020FF RID: 8447 RVA: 0x000F674C File Offset: 0x000F494C
	public static AOAHEAEHFLC LOGCLBDIKNO(AOAHEAEHFLC EGABJKIFAON, int HHAGIHEGFML)
	{
		return new AOAHEAEHFLC(EGABJKIFAON.OCNGPCPMCPM * HHAGIHEGFML, EGABJKIFAON.ADMFAEOOOHD * HHAGIHEGFML);
	}

	// Token: 0x040003E8 RID: 1000
	public int OCNGPCPMCPM;

	// Token: 0x040003E9 RID: 1001
	public int ADMFAEOOOHD;
}
