using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

// Token: 0x02000104 RID: 260
public class ELCMHGJLFOL
{
	// Token: 0x060030FE RID: 12542 RVA: 0x0016B484 File Offset: 0x00169684
	public ELCMHGJLFOL.FDEPADNCGIF AHEDNDEJLJP(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x060030FF RID: 12543 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void GDPNJOBMBBO(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003100 RID: 12544 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void KGCELFFBHIB(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003101 RID: 12545 RVA: 0x0016B50C File Offset: 0x0016970C
	public ELCMHGJLFOL.FDEPADNCGIF GMPNBBLOHGF(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x06003102 RID: 12546 RVA: 0x0016B560 File Offset: 0x00169760
	public ELCMHGJLFOL.FDEPADNCGIF MKNBGEHEMPB(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x06003103 RID: 12547 RVA: 0x0016B5B4 File Offset: 0x001697B4
	public ELCMHGJLFOL.FDEPADNCGIF GECBLDDOENE(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x06003104 RID: 12548 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void FPGMNEHNGMD(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003105 RID: 12549 RVA: 0x0016B608 File Offset: 0x00169808
	public ELCMHGJLFOL.FDEPADNCGIF CEGLBGMFGFF(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x06003106 RID: 12550 RVA: 0x0016B65C File Offset: 0x0016985C
	public ELCMHGJLFOL.FDEPADNCGIF AGFFEHHGELE(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x06003107 RID: 12551 RVA: 0x0016B6B0 File Offset: 0x001698B0
	public ELCMHGJLFOL.FDEPADNCGIF MCBGCEFDIJP(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x06003108 RID: 12552 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void HCMFPOKPCBG(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003109 RID: 12553 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void CCIKAKBFPPJ(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x0600310A RID: 12554 RVA: 0x0016B704 File Offset: 0x00169904
	public ELCMHGJLFOL.FDEPADNCGIF DJIJHNLKAPC(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x0600310B RID: 12555 RVA: 0x0016B758 File Offset: 0x00169958
	public ELCMHGJLFOL.FDEPADNCGIF MNJOAIFPFHL(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x0600310C RID: 12556 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void HCAGFLCIGCI(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x0600310E RID: 12558 RVA: 0x0016B7CC File Offset: 0x001699CC
	public ELCMHGJLFOL.FDEPADNCGIF MLLMKLAIDHC(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x0600310F RID: 12559 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void FCOMHCPFECK(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003110 RID: 12560 RVA: 0x0016B820 File Offset: 0x00169A20
	public ELCMHGJLFOL.FDEPADNCGIF CMMHMGFAFFI(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x06003111 RID: 12561 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void NIPGBPMGAMN(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003112 RID: 12562 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void FDJKGOFOEDG(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003113 RID: 12563 RVA: 0x0016B874 File Offset: 0x00169A74
	public ELCMHGJLFOL.FDEPADNCGIF OPGIDHFNIGC(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x06003114 RID: 12564 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void AJJPEOKLKKL(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003115 RID: 12565 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void AGNNIJBBAJH(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003116 RID: 12566 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void NHLALPHAMFI(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003117 RID: 12567 RVA: 0x0016B8C8 File Offset: 0x00169AC8
	public ELCMHGJLFOL.FDEPADNCGIF EAPIDPPKCMF(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x06003118 RID: 12568 RVA: 0x0016B91C File Offset: 0x00169B1C
	public ELCMHGJLFOL.FDEPADNCGIF BKIILLHFAKE(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x06003119 RID: 12569 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void JGNONIFPOPE(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x0600311A RID: 12570 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void IBBHLECBAML(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x0600311B RID: 12571 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void PNIBPNLJBPN(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x0600311C RID: 12572 RVA: 0x0016B970 File Offset: 0x00169B70
	public ELCMHGJLFOL.FDEPADNCGIF CHKNPLNHJFO(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x0600311D RID: 12573 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void ALCGOADJPAK(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x0600311F RID: 12575 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void OFJJCELCOHH(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003120 RID: 12576 RVA: 0x0016B9D0 File Offset: 0x00169BD0
	public ELCMHGJLFOL.FDEPADNCGIF BCBCICJDIEF(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x06003121 RID: 12577 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void ALNCFMIKCCM(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003122 RID: 12578 RVA: 0x0016BA24 File Offset: 0x00169C24
	public ELCMHGJLFOL.FDEPADNCGIF AIIPKFNLCKG(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x06003123 RID: 12579 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void EKNLOJDDBGL(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003124 RID: 12580 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void ODLPBHJPODK(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003125 RID: 12581 RVA: 0x0016BA78 File Offset: 0x00169C78
	public ELCMHGJLFOL.FDEPADNCGIF IOHGFMOAJIE(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x06003126 RID: 12582 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void EBMDFEMAMMD(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003127 RID: 12583 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void CHAFDOJFFBM(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003128 RID: 12584 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void EDCHNKEFNMH(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003129 RID: 12585 RVA: 0x0016BACC File Offset: 0x00169CCC
	public ELCMHGJLFOL.FDEPADNCGIF INEIMJBBPHJ(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x0600312A RID: 12586 RVA: 0x0016BB20 File Offset: 0x00169D20
	public ELCMHGJLFOL.FDEPADNCGIF CGHPNCELBNI(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x0600312B RID: 12587 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void DLJJJDIPJHI(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x0600312C RID: 12588 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void PBOCOOIPCLI(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x0600312D RID: 12589 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void FNJLJMDFBCK(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x0600312E RID: 12590 RVA: 0x0016BB74 File Offset: 0x00169D74
	public ELCMHGJLFOL.FDEPADNCGIF CEHGLMKOMHC(long LPFKFNLHGBI)
	{
		if (LPFKFNLHGBI == 0L)
		{
			return this.FOKNJGKOEKO;
		}
		if (!this.MGIJLINICPA.ContainsKey(LPFKFNLHGBI))
		{
			if (LPFKFNLHGBI == 0L)
			{
				return this.FOKNJGKOEKO;
			}
			ELCMHGJLFOL.FDEPADNCGIF fdepadncgif = new ELCMHGJLFOL.FDEPADNCGIF(LPFKFNLHGBI);
			this.MGIJLINICPA.Add(fdepadncgif.GPFAEKCMIGF, fdepadncgif);
		}
		return this.MGIJLINICPA[LPFKFNLHGBI];
	}

	// Token: 0x0600312F RID: 12591 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void NKDJHJDEJEO(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x06003130 RID: 12592 RVA: 0x0016B4D8 File Offset: 0x001696D8
	public void IHFLGCJBLCK(ELCMHGJLFOL.FDEPADNCGIF JLFIOOJLJOD)
	{
		if (JLFIOOJLJOD == null)
		{
			return;
		}
		long gpfaekcmigf = JLFIOOJLJOD.GPFAEKCMIGF;
		if (this.MGIJLINICPA.ContainsKey(JLFIOOJLJOD.GPFAEKCMIGF))
		{
			return;
		}
		this.MGIJLINICPA.Add(JLFIOOJLJOD.GPFAEKCMIGF, JLFIOOJLJOD);
	}

	// Token: 0x0400070E RID: 1806
	public static ELCMHGJLFOL IKGFHGKKCPG = new ELCMHGJLFOL();

	// Token: 0x0400070F RID: 1807
	public ELCMHGJLFOL.FDEPADNCGIF FOKNJGKOEKO = new ELCMHGJLFOL.FDEPADNCGIF(0L);

	// Token: 0x04000710 RID: 1808
	public Dictionary<long, ELCMHGJLFOL.FDEPADNCGIF> MGIJLINICPA = new Dictionary<long, ELCMHGJLFOL.FDEPADNCGIF>();

	// Token: 0x02000105 RID: 261
	public class FDEPADNCGIF : ItemBase
	{
		// Token: 0x06003131 RID: 12593 RVA: 0x0016BBC8 File Offset: 0x00169DC8
		public void KIALEELDFDJ(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.KDNDJNEGBDI();
			this.JFGKIGAACHI = KADBECGIMPD.KDELAFDDGJH();
			this.MNGHILMCBCI = KADBECGIMPD.DPLAJNEDGBL();
			this.BHLAFDJCKNL = KADBECGIMPD.NCODBGMGNFD();
			this.JGMDIDHPGLI = KADBECGIMPD.EJPMFEJBGMN();
			this.CNOLCNDBLJE = KADBECGIMPD.KKOKFLMMAAK();
			this.LINFEJEGCPB = KADBECGIMPD.IFDFHJLCHAE();
			this.ALMGPBBJIPH = KADBECGIMPD.IOEEPNCKLJD();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = false;
			}
		}

		// Token: 0x06003132 RID: 12594 RVA: 0x0016BC44 File Offset: 0x00169E44
		public void MPCIALDHHKN(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.DOJKJHMJJNK();
			this.JFGKIGAACHI = KADBECGIMPD.BFPHBMDMODH();
			this.MNGHILMCBCI = KADBECGIMPD.BFPHBMDMODH();
			this.BHLAFDJCKNL = KADBECGIMPD.JJJJAGJCOGD();
			this.JGMDIDHPGLI = KADBECGIMPD.KLHDFFHONON();
			this.CNOLCNDBLJE = KADBECGIMPD.IFDFHJLCHAE();
			this.LINFEJEGCPB = KADBECGIMPD.AGNKAFLKCAG();
			this.ALMGPBBJIPH = KADBECGIMPD.OMCMPDMJFOJ();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = true;
			}
		}

		// Token: 0x06003133 RID: 12595 RVA: 0x0016BCC0 File Offset: 0x00169EC0
		public virtual void CKEADHDIJAO(RectTransform[] IKPEEEBENDE, RectTransform ONPHLHKAGFP)
		{
			if (IKPEEEBENDE == null)
			{
				return;
			}
			IKPEEEBENDE[0].gameObject.GetComponent<Text>().text = this.MNGHILMCBCI;
			IKPEEEBENDE[6].gameObject.GetComponent<Text>().text = string.Concat(this.CNOLCNDBLJE);
			IKPEEEBENDE[1].gameObject.GetComponent<Text>().text = string.Concat(this.JGMDIDHPGLI);
			IKPEEEBENDE[8].gameObject.GetComponent<Text>().text = string.Concat(this.LINFEJEGCPB);
			if (this.ALMGPBBJIPH)
			{
				IKPEEEBENDE[5].gameObject.GetComponent<Image>().color = Color.white;
				return;
			}
			IKPEEEBENDE[7].gameObject.GetComponent<Image>().color = new Color(1435f, 1715f, 1273f, 1005f);
		}

		// Token: 0x06003134 RID: 12596 RVA: 0x0016BD9C File Offset: 0x00169F9C
		public void PJJDAALHOHH(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.HHLDBAEFNMJ();
			this.JFGKIGAACHI = KADBECGIMPD.DHCMILPKJAL();
			this.MNGHILMCBCI = KADBECGIMPD.DPLAJNEDGBL();
			this.BHLAFDJCKNL = KADBECGIMPD.KDELAFDDGJH();
			this.JGMDIDHPGLI = KADBECGIMPD.IJDIMHAEAIE();
			this.CNOLCNDBLJE = KADBECGIMPD.CLPEKGGAMAI();
			this.LINFEJEGCPB = KADBECGIMPD.HDBGOLAFOBK();
			this.ALMGPBBJIPH = KADBECGIMPD.KJIOFDCKIKO();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = false;
			}
		}

		// Token: 0x06003135 RID: 12597 RVA: 0x0016BE18 File Offset: 0x0016A018
		public void LBBBADCPGOI(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.KKOKFLMMAAK();
			this.JFGKIGAACHI = KADBECGIMPD.LPKJHMGLCKA();
			this.MNGHILMCBCI = KADBECGIMPD.NCODBGMGNFD();
			this.BHLAFDJCKNL = KADBECGIMPD.JJJJAGJCOGD();
			this.JGMDIDHPGLI = KADBECGIMPD.HFOPFEJDJFG();
			this.CNOLCNDBLJE = KADBECGIMPD.KDNDJNEGBDI();
			this.LINFEJEGCPB = KADBECGIMPD.KKOKFLMMAAK();
			this.ALMGPBBJIPH = KADBECGIMPD.ELDBJFLCMAJ();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = false;
			}
		}

		// Token: 0x06003136 RID: 12598 RVA: 0x0016BE94 File Offset: 0x0016A094
		public void NHHAANEMJCK(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.CLPEKGGAMAI();
			this.JFGKIGAACHI = KADBECGIMPD.KDELAFDDGJH();
			this.MNGHILMCBCI = KADBECGIMPD.DHCMILPKJAL();
			this.BHLAFDJCKNL = KADBECGIMPD.DPLAJNEDGBL();
			this.JGMDIDHPGLI = KADBECGIMPD.IJDIMHAEAIE();
			this.CNOLCNDBLJE = KADBECGIMPD.IFDFHJLCHAE();
			this.LINFEJEGCPB = KADBECGIMPD.KDNDJNEGBDI();
			this.ALMGPBBJIPH = KADBECGIMPD.IJJDHHFAIPE();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = true;
			}
		}

		// Token: 0x06003137 RID: 12599 RVA: 0x0016BF10 File Offset: 0x0016A110
		public FDEPADNCGIF(long HMMPJNDKKCA)
		{
			this.GPFAEKCMIGF = HMMPJNDKKCA;
			this.JFGKIGAACHI = "";
			this.MNGHILMCBCI = "";
			this.BHLAFDJCKNL = "";
			this.FAHPDKIIIBO = false;
		}

		// Token: 0x06003138 RID: 12600 RVA: 0x0016BF48 File Offset: 0x0016A148
		public virtual void FOKHLKPGGFO(RectTransform[] IKPEEEBENDE, RectTransform ONPHLHKAGFP)
		{
			if (IKPEEEBENDE == null)
			{
				return;
			}
			IKPEEEBENDE[1].gameObject.GetComponent<Text>().text = this.MNGHILMCBCI;
			IKPEEEBENDE[8].gameObject.GetComponent<Text>().text = string.Concat(this.CNOLCNDBLJE);
			IKPEEEBENDE[5].gameObject.GetComponent<Text>().text = string.Concat(this.JGMDIDHPGLI);
			IKPEEEBENDE[8].gameObject.GetComponent<Text>().text = string.Concat(this.LINFEJEGCPB);
			if (this.ALMGPBBJIPH)
			{
				IKPEEEBENDE[1].gameObject.GetComponent<Image>().color = Color.white;
				return;
			}
			IKPEEEBENDE[8].gameObject.GetComponent<Image>().color = new Color(656f, 1664f, 447f, 679f);
		}

		// Token: 0x06003139 RID: 12601 RVA: 0x0016C024 File Offset: 0x0016A224
		public void FEEODCOLNIN(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.DOJKJHMJJNK();
			this.JFGKIGAACHI = KADBECGIMPD.BFPHBMDMODH();
			this.MNGHILMCBCI = KADBECGIMPD.PNBECHOLCJM();
			this.BHLAFDJCKNL = KADBECGIMPD.LPKJHMGLCKA();
			this.JGMDIDHPGLI = KADBECGIMPD.DNIIFBAIPBE();
			this.CNOLCNDBLJE = KADBECGIMPD.LDLKLPJBIJN();
			this.LINFEJEGCPB = KADBECGIMPD.DOJKJHMJJNK();
			this.ALMGPBBJIPH = KADBECGIMPD.BLNIHNKJJPJ();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = false;
			}
		}

		// Token: 0x0600313A RID: 12602 RVA: 0x0016C0A0 File Offset: 0x0016A2A0
		public void ONIJHKMCCHH(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.HDBGOLAFOBK();
			this.JFGKIGAACHI = KADBECGIMPD.KDELAFDDGJH();
			this.MNGHILMCBCI = KADBECGIMPD.JJJJAGJCOGD();
			this.BHLAFDJCKNL = KADBECGIMPD.JJJJAGJCOGD();
			this.JGMDIDHPGLI = KADBECGIMPD.HHMGLDMFCPF();
			this.CNOLCNDBLJE = KADBECGIMPD.LDLKLPJBIJN();
			this.LINFEJEGCPB = KADBECGIMPD.DOJKJHMJJNK();
			this.ALMGPBBJIPH = KADBECGIMPD.OMCMPDMJFOJ();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = false;
			}
		}

		// Token: 0x0600313B RID: 12603 RVA: 0x0016C11C File Offset: 0x0016A31C
		public virtual void MAMHFDJCIGK(RectTransform[] IKPEEEBENDE, RectTransform ONPHLHKAGFP)
		{
			if (IKPEEEBENDE == null)
			{
				return;
			}
			IKPEEEBENDE[0].gameObject.GetComponent<Text>().text = this.MNGHILMCBCI;
			IKPEEEBENDE[3].gameObject.GetComponent<Text>().text = string.Concat(this.CNOLCNDBLJE);
			IKPEEEBENDE[1].gameObject.GetComponent<Text>().text = string.Concat(this.JGMDIDHPGLI);
			IKPEEEBENDE[2].gameObject.GetComponent<Text>().text = string.Concat(this.LINFEJEGCPB);
			if (this.ALMGPBBJIPH)
			{
				IKPEEEBENDE[2].gameObject.GetComponent<Image>().color = Color.white;
				return;
			}
			IKPEEEBENDE[5].gameObject.GetComponent<Image>().color = new Color(411f, 967f, 617f, 1847f);
		}

		// Token: 0x0600313C RID: 12604 RVA: 0x0016C1F8 File Offset: 0x0016A3F8
		public void IHONANEEDOC(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.DOJKJHMJJNK();
			this.JFGKIGAACHI = KADBECGIMPD.FDIDEGHPJPF();
			this.MNGHILMCBCI = KADBECGIMPD.PNBECHOLCJM();
			this.BHLAFDJCKNL = KADBECGIMPD.JJJJAGJCOGD();
			this.JGMDIDHPGLI = KADBECGIMPD.DCGEOFHNBCN();
			this.CNOLCNDBLJE = KADBECGIMPD.AGNKAFLKCAG();
			this.LINFEJEGCPB = KADBECGIMPD.HHLDBAEFNMJ();
			this.ALMGPBBJIPH = KADBECGIMPD.JNOKJCDAPPA();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = false;
			}
		}

		// Token: 0x0600313D RID: 12605 RVA: 0x0016C274 File Offset: 0x0016A474
		public virtual void NKBOMOAMPOO(RectTransform[] IKPEEEBENDE, RectTransform ONPHLHKAGFP)
		{
			if (IKPEEEBENDE == null)
			{
				return;
			}
			IKPEEEBENDE[0].gameObject.GetComponent<Text>().text = this.MNGHILMCBCI;
			IKPEEEBENDE[5].gameObject.GetComponent<Text>().text = string.Concat(this.CNOLCNDBLJE);
			IKPEEEBENDE[6].gameObject.GetComponent<Text>().text = string.Concat(this.JGMDIDHPGLI);
			IKPEEEBENDE[5].gameObject.GetComponent<Text>().text = string.Concat(this.LINFEJEGCPB);
			if (this.ALMGPBBJIPH)
			{
				IKPEEEBENDE[7].gameObject.GetComponent<Image>().color = Color.white;
				return;
			}
			IKPEEEBENDE[5].gameObject.GetComponent<Image>().color = new Color(361f, 420f, 1873f, 1084f);
		}

		// Token: 0x0600313E RID: 12606 RVA: 0x0016C350 File Offset: 0x0016A550
		public void LFOPENOJDIM(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.HHLDBAEFNMJ();
			this.JFGKIGAACHI = KADBECGIMPD.JJJJAGJCOGD();
			this.MNGHILMCBCI = KADBECGIMPD.DHCMILPKJAL();
			this.BHLAFDJCKNL = KADBECGIMPD.DPLAJNEDGBL();
			this.JGMDIDHPGLI = KADBECGIMPD.DCGEOFHNBCN();
			this.CNOLCNDBLJE = KADBECGIMPD.DOJKJHMJJNK();
			this.LINFEJEGCPB = KADBECGIMPD.IFDFHJLCHAE();
			this.ALMGPBBJIPH = KADBECGIMPD.ELDBJFLCMAJ();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = true;
			}
		}

		// Token: 0x0600313F RID: 12607 RVA: 0x0016C3CC File Offset: 0x0016A5CC
		public void KKLMGOBGMHD(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.LDLKLPJBIJN();
			this.JFGKIGAACHI = KADBECGIMPD.LPKJHMGLCKA();
			this.MNGHILMCBCI = KADBECGIMPD.DPLAJNEDGBL();
			this.BHLAFDJCKNL = KADBECGIMPD.FDIDEGHPJPF();
			this.JGMDIDHPGLI = KADBECGIMPD.IJDIMHAEAIE();
			this.CNOLCNDBLJE = KADBECGIMPD.LDLKLPJBIJN();
			this.LINFEJEGCPB = KADBECGIMPD.IFDFHJLCHAE();
			this.ALMGPBBJIPH = KADBECGIMPD.LAECLJFMGPE();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = true;
			}
		}

		// Token: 0x06003140 RID: 12608 RVA: 0x0016C448 File Offset: 0x0016A648
		public void KAOKKLLOFBE(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.KKOKFLMMAAK();
			this.JFGKIGAACHI = KADBECGIMPD.KDELAFDDGJH();
			this.MNGHILMCBCI = KADBECGIMPD.NCODBGMGNFD();
			this.BHLAFDJCKNL = KADBECGIMPD.FDIDEGHPJPF();
			this.JGMDIDHPGLI = KADBECGIMPD.DMABDIGCLKA();
			this.CNOLCNDBLJE = KADBECGIMPD.IFDFHJLCHAE();
			this.LINFEJEGCPB = KADBECGIMPD.CLPEKGGAMAI();
			this.ALMGPBBJIPH = KADBECGIMPD.KJIOFDCKIKO();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = false;
			}
		}

		// Token: 0x06003141 RID: 12609 RVA: 0x0016C4C4 File Offset: 0x0016A6C4
		public void MPMELFMBFAN(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.DOJKJHMJJNK();
			this.JFGKIGAACHI = KADBECGIMPD.LPKJHMGLCKA();
			this.MNGHILMCBCI = KADBECGIMPD.JJJJAGJCOGD();
			this.BHLAFDJCKNL = KADBECGIMPD.NCODBGMGNFD();
			this.JGMDIDHPGLI = KADBECGIMPD.HHMGLDMFCPF();
			this.CNOLCNDBLJE = KADBECGIMPD.HHLDBAEFNMJ();
			this.LINFEJEGCPB = KADBECGIMPD.HDBGOLAFOBK();
			this.ALMGPBBJIPH = KADBECGIMPD.KJIOFDCKIKO();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = false;
			}
		}

		// Token: 0x06003142 RID: 12610 RVA: 0x0016C540 File Offset: 0x0016A740
		public void OCPAHLAGCAI(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.HDBGOLAFOBK();
			this.JFGKIGAACHI = KADBECGIMPD.BFPHBMDMODH();
			this.MNGHILMCBCI = KADBECGIMPD.BFPHBMDMODH();
			this.BHLAFDJCKNL = KADBECGIMPD.BFPHBMDMODH();
			this.JGMDIDHPGLI = KADBECGIMPD.DNIIFBAIPBE();
			this.CNOLCNDBLJE = KADBECGIMPD.HDBGOLAFOBK();
			this.LINFEJEGCPB = KADBECGIMPD.HDBGOLAFOBK();
			this.ALMGPBBJIPH = KADBECGIMPD.FIFNOBGEKFF();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = true;
			}
		}

		// Token: 0x06003143 RID: 12611 RVA: 0x0016C5BC File Offset: 0x0016A7BC
		public void HLJFBOLPOMG(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.DOJKJHMJJNK();
			this.JFGKIGAACHI = KADBECGIMPD.KDELAFDDGJH();
			this.MNGHILMCBCI = KADBECGIMPD.DPLAJNEDGBL();
			this.BHLAFDJCKNL = KADBECGIMPD.LPKJHMGLCKA();
			this.JGMDIDHPGLI = KADBECGIMPD.ANPEIKGEDHJ();
			this.CNOLCNDBLJE = KADBECGIMPD.LDLKLPJBIJN();
			this.LINFEJEGCPB = KADBECGIMPD.IFDFHJLCHAE();
			this.ALMGPBBJIPH = KADBECGIMPD.IOEEPNCKLJD();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = true;
			}
		}

		// Token: 0x06003144 RID: 12612 RVA: 0x0016C638 File Offset: 0x0016A838
		public void FNJFCJFAJFG(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.HHLDBAEFNMJ();
			this.JFGKIGAACHI = KADBECGIMPD.DHCMILPKJAL();
			this.MNGHILMCBCI = KADBECGIMPD.FDIDEGHPJPF();
			this.BHLAFDJCKNL = KADBECGIMPD.NCODBGMGNFD();
			this.JGMDIDHPGLI = KADBECGIMPD.DCGEOFHNBCN();
			this.CNOLCNDBLJE = KADBECGIMPD.HDBGOLAFOBK();
			this.LINFEJEGCPB = KADBECGIMPD.IFDFHJLCHAE();
			this.ALMGPBBJIPH = KADBECGIMPD.KJIOFDCKIKO();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = true;
			}
		}

		// Token: 0x06003145 RID: 12613 RVA: 0x0016C6B4 File Offset: 0x0016A8B4
		public virtual void DDPDGBHHJAF(RectTransform[] IKPEEEBENDE, RectTransform ONPHLHKAGFP)
		{
			if (IKPEEEBENDE == null)
			{
				return;
			}
			IKPEEEBENDE[0].gameObject.GetComponent<Text>().text = this.MNGHILMCBCI;
			IKPEEEBENDE[3].gameObject.GetComponent<Text>().text = string.Concat(this.CNOLCNDBLJE);
			IKPEEEBENDE[7].gameObject.GetComponent<Text>().text = string.Concat(this.JGMDIDHPGLI);
			IKPEEEBENDE[5].gameObject.GetComponent<Text>().text = string.Concat(this.LINFEJEGCPB);
			if (this.ALMGPBBJIPH)
			{
				IKPEEEBENDE[7].gameObject.GetComponent<Image>().color = Color.white;
				return;
			}
			IKPEEEBENDE[2].gameObject.GetComponent<Image>().color = new Color(821f, 1489f, 657f, 17f);
		}

		// Token: 0x06003146 RID: 12614 RVA: 0x0016C790 File Offset: 0x0016A990
		public override void MLCFJPPIOJG(RectTransform[] IKPEEEBENDE, RectTransform ONPHLHKAGFP)
		{
			if (IKPEEEBENDE == null)
			{
				return;
			}
			IKPEEEBENDE[1].gameObject.GetComponent<Text>().text = this.MNGHILMCBCI;
			IKPEEEBENDE[2].gameObject.GetComponent<Text>().text = string.Concat(this.CNOLCNDBLJE);
			IKPEEEBENDE[3].gameObject.GetComponent<Text>().text = string.Concat(this.JGMDIDHPGLI);
			IKPEEEBENDE[4].gameObject.GetComponent<Text>().text = string.Concat(this.LINFEJEGCPB);
			if (this.ALMGPBBJIPH)
			{
				IKPEEEBENDE[5].gameObject.GetComponent<Image>().color = Color.white;
				return;
			}
			IKPEEEBENDE[5].gameObject.GetComponent<Image>().color = new Color(0.4f, 0.2f, 0.2f, 0.2f);
		}

		// Token: 0x06003147 RID: 12615 RVA: 0x0016C86A File Offset: 0x0016AA6A
		public FDEPADNCGIF(long HMMPJNDKKCA, HBPNMNGOFMA KADBECGIMPD)
		{
			this.GPFAEKCMIGF = HMMPJNDKKCA;
			this.OCPAHLAGCAI(KADBECGIMPD);
		}

		// Token: 0x06003148 RID: 12616 RVA: 0x0016C880 File Offset: 0x0016AA80
		public void AGADBLDMILO(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.LDLKLPJBIJN();
			this.JFGKIGAACHI = KADBECGIMPD.PNBECHOLCJM();
			this.MNGHILMCBCI = KADBECGIMPD.KDELAFDDGJH();
			this.BHLAFDJCKNL = KADBECGIMPD.NCODBGMGNFD();
			this.JGMDIDHPGLI = KADBECGIMPD.IBKCNEICPEL();
			this.CNOLCNDBLJE = KADBECGIMPD.IFDFHJLCHAE();
			this.LINFEJEGCPB = KADBECGIMPD.IFDFHJLCHAE();
			this.ALMGPBBJIPH = KADBECGIMPD.DADCGPGEHFK();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = true;
			}
		}

		// Token: 0x06003149 RID: 12617 RVA: 0x0016C8FC File Offset: 0x0016AAFC
		public virtual void HGPPGJPEPEE(RectTransform[] IKPEEEBENDE, RectTransform ONPHLHKAGFP)
		{
			if (IKPEEEBENDE == null)
			{
				return;
			}
			IKPEEEBENDE[1].gameObject.GetComponent<Text>().text = this.MNGHILMCBCI;
			IKPEEEBENDE[6].gameObject.GetComponent<Text>().text = string.Concat(this.CNOLCNDBLJE);
			IKPEEEBENDE[0].gameObject.GetComponent<Text>().text = string.Concat(this.JGMDIDHPGLI);
			IKPEEEBENDE[1].gameObject.GetComponent<Text>().text = string.Concat(this.LINFEJEGCPB);
			if (this.ALMGPBBJIPH)
			{
				IKPEEEBENDE[3].gameObject.GetComponent<Image>().color = Color.white;
				return;
			}
			IKPEEEBENDE[8].gameObject.GetComponent<Image>().color = new Color(1535f, 442f, 802f, 729f);
		}

		// Token: 0x0600314A RID: 12618 RVA: 0x0016C9D8 File Offset: 0x0016ABD8
		public void OLGEDIFBGNL(HBPNMNGOFMA KADBECGIMPD)
		{
			this.ONHAAKOLHII = KADBECGIMPD.HHLDBAEFNMJ();
			this.JFGKIGAACHI = KADBECGIMPD.JJJJAGJCOGD();
			this.MNGHILMCBCI = KADBECGIMPD.JJJJAGJCOGD();
			this.BHLAFDJCKNL = KADBECGIMPD.PNBECHOLCJM();
			this.JGMDIDHPGLI = KADBECGIMPD.DCGEOFHNBCN();
			this.CNOLCNDBLJE = KADBECGIMPD.KKOKFLMMAAK();
			this.LINFEJEGCPB = KADBECGIMPD.LDLKLPJBIJN();
			this.ALMGPBBJIPH = KADBECGIMPD.KJIOFDCKIKO();
			if (this.GPFAEKCMIGF != 0L)
			{
				this.FAHPDKIIIBO = true;
			}
		}

		// Token: 0x04000711 RID: 1809
		public long GPFAEKCMIGF;

		// Token: 0x04000712 RID: 1810
		public int ONHAAKOLHII;

		// Token: 0x04000713 RID: 1811
		public string JFGKIGAACHI;

		// Token: 0x04000714 RID: 1812
		public string MNGHILMCBCI;

		// Token: 0x04000715 RID: 1813
		public string BHLAFDJCKNL;

		// Token: 0x04000716 RID: 1814
		public long JGMDIDHPGLI;

		// Token: 0x04000717 RID: 1815
		public int CNOLCNDBLJE;

		// Token: 0x04000718 RID: 1816
		public int LINFEJEGCPB;

		// Token: 0x04000719 RID: 1817
		public bool ALMGPBBJIPH;

		// Token: 0x0400071A RID: 1818
		public bool FAHPDKIIIBO;
	}
}
