using System;
using UnityEngine;

// Token: 0x020001BC RID: 444
public class GMNEKCBLIAN : ONKDCGNBALK
{
	// Token: 0x06006321 RID: 25377 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void OECNEDDNMGC(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006322 RID: 25378 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void OOKDJBCNEBH(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006323 RID: 25379 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void FJNDHHDAGCI(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006324 RID: 25380 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void KNCJKEEICGO(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006325 RID: 25381 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void JOBPKNNNEAD(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006326 RID: 25382 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void KJFNHNJEADK(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006327 RID: 25383 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void GMLICBKPPCC(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006328 RID: 25384 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void APOPIOPIFMP(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006329 RID: 25385 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void LCIKLFLKPEE(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600632A RID: 25386 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void OCCJHOPJHLG(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600632B RID: 25387 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void DDLPNGBNMED(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600632C RID: 25388 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void DLBGNLEIMPB(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600632D RID: 25389 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void FDCOFCOIHEH(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600632E RID: 25390 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void NDEKHNDALJJ(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600632F RID: 25391 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void JIGDBPIJDHE(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006330 RID: 25392 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void ENCCJFKCHIE(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006331 RID: 25393 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void CBGMHNELDIA(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006332 RID: 25394 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void HCHJHBGEGMP(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006333 RID: 25395 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void FMBBLFIGPGL(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006334 RID: 25396 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void EGKHIENICMJ(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006335 RID: 25397 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void LCOKOEMNPEL(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006336 RID: 25398 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void CMNHIIEFOHJ(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006337 RID: 25399 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void MBABINJIPDF(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006338 RID: 25400 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void DKOEJJHKMHI(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006339 RID: 25401 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void LPPKKCCKLJF(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600633A RID: 25402 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void LNEKEJJIHHP(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600633B RID: 25403 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void CMECHJMLPGD(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600633C RID: 25404 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void FCCFIHJKFNK(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600633D RID: 25405 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void KCHEILEJGPL(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600633E RID: 25406 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void PHJEFJPDDDI(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600633F RID: 25407 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void NEHJDJAAMEO(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006340 RID: 25408 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void LNNEOFFJJJA(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006341 RID: 25409 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void BFHPJCKICCE(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006342 RID: 25410 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void AMEAHFNAHDC(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006343 RID: 25411 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void BLGIOPMGMPG(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006344 RID: 25412 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void OAPAJJAJPEK(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006345 RID: 25413 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void OPAJOHMJIJJ(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006346 RID: 25414 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void BIJMKMEPBIC(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006347 RID: 25415 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void FOGCOMNGOFB(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006348 RID: 25416 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void JBBGCIICJIH(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006349 RID: 25417 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void HADLKLNMMNC(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600634A RID: 25418 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void JIAOONGONPM(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600634B RID: 25419 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void DBHACAENJOE(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600634C RID: 25420 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void BNBECPLPKGM(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600634D RID: 25421 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void ECLJBBPGNPA(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600634E RID: 25422 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void OEGEMMPIIPC(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x0600634F RID: 25423 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void GHGLBEBFGAP(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006350 RID: 25424 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void CGKPGCLLJHJ(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006351 RID: 25425 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public override void HFJFBDPNCCB(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006352 RID: 25426 RVA: 0x002E2628 File Offset: 0x002E0828
	public GMNEKCBLIAN(ONKDCGNBALK OCBAOFLJBGP, Rect OCHCODJIPHJ, float IHDGCJACCAB, float LHNHNBBAEGE, int POBKJFFLEPN, string EHHIFDHHMPP, bool DPFKHKLCIJP = true) : base(OCBAOFLJBGP, OCHCODJIPHJ.x, OCHCODJIPHJ.y, OCHCODJIPHJ.width, OCHCODJIPHJ.height, "", 0, 7)
	{
		this.KNIOGNKKINO = 7;
		this.DPANHMGCBNL = EHHIFDHHMPP;
		this.EBLHAJDINBH = IHDGCJACCAB;
		this.EJBJCJJMOPJ = LHNHNBBAEGE;
		this.DEGLDDJPMNF = POBKJFFLEPN;
		this.KPLMFNIFPMM = DPFKHKLCIJP;
	}

	// Token: 0x06006353 RID: 25427 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void OFCJAMLCEPB(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006354 RID: 25428 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void LMIIDBOCFPI(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006355 RID: 25429 RVA: 0x002E25B8 File Offset: 0x002E07B8
	public virtual void OLHEECEMJDD(bool CFMPGCJMHJM)
	{
		GameInterface.getI.renderPBar(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x06006356 RID: 25430 RVA: 0x002E25EF File Offset: 0x002E07EF
	public virtual void ILHLJFHLJIH(bool CFMPGCJMHJM)
	{
		GameInterface.getI.NFGOLLEEHHK(this.OCHCODJIPHJ, this.EBLHAJDINBH, this.EJBJCJJMOPJ, this.DEGLDDJPMNF, this.DPANHMGCBNL, this.KPLMFNIFPMM);
		base.HFJFBDPNCCB(CFMPGCJMHJM);
	}

	// Token: 0x04000E5C RID: 3676
	public new string DPANHMGCBNL;

	// Token: 0x04000E5D RID: 3677
	public bool KPLMFNIFPMM;

	// Token: 0x04000E5E RID: 3678
	public float EBLHAJDINBH;

	// Token: 0x04000E5F RID: 3679
	public float EJBJCJJMOPJ;

	// Token: 0x04000E60 RID: 3680
	public int DEGLDDJPMNF;
}
