using System;
using UnityEngine;
using UnityEngine.UI;

// Token: 0x02000241 RID: 577
public class LocButton : MonoBehaviour
{
	// Token: 0x060083F9 RID: 33785 RVA: 0x003DEDDC File Offset: 0x003DCFDC
	public void FPKIKIFEOID()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.JIIKLOKAGIC(JBEHMPDDMME.PLGADNLAEGN().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.FLLJONHPLNA(this.toLocId);
			epmphjgalbe.JIIKLOKAGIC(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.EILLJGEHCOH(-113, epmphjgalbe.JDPHBLHOLAD());
		}
		finally
		{
			epmphjgalbe.KNPHNLLMJKJ();
		}
		JDCEFOFMGHB.JFIDAGABKID().LCEOGOCIMMB();
		JDCEFOFMGHB.JFIDAGABKID().MDBKHKBJNAO(true);
	}

	// Token: 0x060083FA RID: 33786 RVA: 0x003DEE60 File Offset: 0x003DD060
	public void NLLINCLCCHA()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.KCONDIDKLIB(-93, 1);
		JDCEFOFMGHB.MNJNNDHCDGG().DDAIBFBOENE();
		JDCEFOFMGHB.IKGFHGKKCPG.HCFDADCKMCB(true);
	}

	// Token: 0x060083FB RID: 33787 RVA: 0x003DEE88 File Offset: 0x003DD088
	public void IPILBMBODNE()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.EIMEKHOFIEA(JBEHMPDDMME.EAJHPOJPPFA().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.LHLOOIDHGMA(this.toLocId);
			epmphjgalbe.GOMLLPFFPNP(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(-128, epmphjgalbe.PBOPEDMCKDD());
		}
		finally
		{
			epmphjgalbe.HDKBMLOJLLC();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().DDAIBFBOENE();
		JDCEFOFMGHB.HMJJPNDEKPP().MDBKHKBJNAO(true);
	}

	// Token: 0x060083FC RID: 33788 RVA: 0x003DEF0C File Offset: 0x003DD10C
	public void PGFNEHOOOPP()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.AKJKNCIKBBF(120, 1);
		JDCEFOFMGHB.MNJNNDHCDGG().DDAIBFBOENE();
		JDCEFOFMGHB.HMJJPNDEKPP().LHHBOOJPBPH = true;
	}

	// Token: 0x060083FD RID: 33789 RVA: 0x003DEF33 File Offset: 0x003DD133
	public void CIBKONDPANH()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.PIGIIJLCADJ(154, 1);
		JDCEFOFMGHB.JFIDAGABKID().LCEOGOCIMMB();
		JDCEFOFMGHB.HMJJPNDEKPP().HCFDADCKMCB(true);
	}

	// Token: 0x060083FF RID: 33791 RVA: 0x003DEF6C File Offset: 0x003DD16C
	public void ONMLHHLGMOF()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.ALNEALEKFNB(JBEHMPDDMME.PLGADNLAEGN().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.JIIKLOKAGIC(this.toLocId);
			epmphjgalbe.DEHJNGMHGAJ(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().HJPGADJMICM(-102, epmphjgalbe.PBOPEDMCKDD());
		}
		finally
		{
			epmphjgalbe.LMBPNFHKNGA();
		}
		JDCEFOFMGHB.HMJJPNDEKPP().DDAIBFBOENE();
		JDCEFOFMGHB.HMJJPNDEKPP().MDBKHKBJNAO(false);
	}

	// Token: 0x06008400 RID: 33792 RVA: 0x003DEFF0 File Offset: 0x003DD1F0
	public void NCONBKELEAP()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.KPCGLGHDILI(JBEHMPDDMME.BPPFAOOCENN().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.ALNEALEKFNB(this.toLocId);
			epmphjgalbe.JIIKLOKAGIC(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.AKJKNCIKBBF(192, epmphjgalbe.NNEAJJNCGMK());
		}
		finally
		{
			epmphjgalbe.OGPGOEJFIBO();
		}
		JDCEFOFMGHB.HMJJPNDEKPP().DDAIBFBOENE();
		JDCEFOFMGHB.HMJJPNDEKPP().LHHBOOJPBPH = false;
	}

	// Token: 0x06008401 RID: 33793 RVA: 0x003DF074 File Offset: 0x003DD274
	public void OJNFDIHAHGE()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.KCONDIDKLIB(-32, 1);
		JDCEFOFMGHB.IKGFHGKKCPG.LCEOGOCIMMB();
		JDCEFOFMGHB.MNJNNDHCDGG().HCFDADCKMCB(true);
	}

	// Token: 0x06008402 RID: 33794 RVA: 0x003DF09B File Offset: 0x003DD29B
	public void IEJOMFDDALG()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().PIGIIJLCADJ(-173, 1);
		JDCEFOFMGHB.MNJNNDHCDGG().DDAIBFBOENE();
		JDCEFOFMGHB.MNJNNDHCDGG().LHHBOOJPBPH = true;
	}

	// Token: 0x06008403 RID: 33795 RVA: 0x003DF0C4 File Offset: 0x003DD2C4
	public void LJOPHBNIIOA()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.ALNEALEKFNB(JBEHMPDDMME.BPPFAOOCENN().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.EIMEKHOFIEA(this.toLocId);
			epmphjgalbe.ALNEALEKFNB(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().EILLJGEHCOH(95, epmphjgalbe.PBOPEDMCKDD());
		}
		finally
		{
			epmphjgalbe.NCKMEIBFNGL();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().LCEOGOCIMMB();
		JDCEFOFMGHB.JFIDAGABKID().LHHBOOJPBPH = true;
	}

	// Token: 0x06008404 RID: 33796 RVA: 0x003DF148 File Offset: 0x003DD348
	public void PIDIJJBLHOH()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.EIMEKHOFIEA(JBEHMPDDMME.BOKIOJFHNLD().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.JDOLCNDNFGP(this.toLocId);
			epmphjgalbe.ALNEALEKFNB(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.EILLJGEHCOH(149, epmphjgalbe.ALLANCHILCM());
		}
		finally
		{
			epmphjgalbe.NCKMEIBFNGL();
		}
		JDCEFOFMGHB.HMJJPNDEKPP().LCEOGOCIMMB();
		JDCEFOFMGHB.HMJJPNDEKPP().HCFDADCKMCB(true);
	}

	// Token: 0x06008405 RID: 33797 RVA: 0x003DF1CC File Offset: 0x003DD3CC
	public void HKKKIILALOF()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.KPCGLGHDILI(JBEHMPDDMME.BPPFAOOCENN().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.DEHJNGMHGAJ(this.toLocId);
			epmphjgalbe.PDEFLCIEMFF(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.EILLJGEHCOH(-140, epmphjgalbe.PBOPEDMCKDD());
		}
		finally
		{
			epmphjgalbe.PGLFHABMJPO();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().LCEOGOCIMMB();
		JDCEFOFMGHB.JFIDAGABKID().MDBKHKBJNAO(true);
	}

	// Token: 0x06008406 RID: 33798 RVA: 0x003DF250 File Offset: 0x003DD450
	public void OBADFFCMGGJ()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.JDOLCNDNFGP(JBEHMPDDMME.PFOLNEGNIPP().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.FLLJONHPLNA(this.toLocId);
			epmphjgalbe.KPCGLGHDILI(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.AKJKNCIKBBF(-57, epmphjgalbe.HDEKHFOKCKI());
		}
		finally
		{
			epmphjgalbe.NCKMEIBFNGL();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().LCEOGOCIMMB();
		JDCEFOFMGHB.HMJJPNDEKPP().LHHBOOJPBPH = false;
	}

	// Token: 0x06008407 RID: 33799 RVA: 0x003DF2D4 File Offset: 0x003DD4D4
	public void OnBaseClick()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.AKJKNCIKBBF(145, 0);
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.IKGFHGKKCPG.LHHBOOJPBPH = true;
	}

	// Token: 0x06008408 RID: 33800 RVA: 0x003DF2FB File Offset: 0x003DD4FB
	public void JHICCIGBIBE()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.PIGIIJLCADJ(-11, 0);
		JDCEFOFMGHB.JFIDAGABKID().LCEOGOCIMMB();
		JDCEFOFMGHB.IKGFHGKKCPG.HCFDADCKMCB(false);
	}

	// Token: 0x06008409 RID: 33801 RVA: 0x003DF322 File Offset: 0x003DD522
	public void EHHCJDJPGKP()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(-152, 0);
		JDCEFOFMGHB.JFIDAGABKID().LCEOGOCIMMB();
		JDCEFOFMGHB.HMJJPNDEKPP().MDBKHKBJNAO(false);
	}

	// Token: 0x0600840A RID: 33802 RVA: 0x003DF349 File Offset: 0x003DD549
	public void OCDHHDMPDII()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().KCONDIDKLIB(-37, 0);
		JDCEFOFMGHB.HMJJPNDEKPP().LCEOGOCIMMB();
		JDCEFOFMGHB.HMJJPNDEKPP().LHHBOOJPBPH = false;
	}

	// Token: 0x0600840B RID: 33803 RVA: 0x003DF370 File Offset: 0x003DD570
	public void EGNHNIKCEOA()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().PIGIIJLCADJ(-39, 1);
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.MNJNNDHCDGG().LHHBOOJPBPH = true;
	}

	// Token: 0x0600840C RID: 33804 RVA: 0x003DF397 File Offset: 0x003DD597
	public void LCPPBMJJNBC()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.PIGIIJLCADJ(-41, 0);
		JDCEFOFMGHB.JFIDAGABKID().LCEOGOCIMMB();
		JDCEFOFMGHB.JFIDAGABKID().LHHBOOJPBPH = false;
	}

	// Token: 0x0600840D RID: 33805 RVA: 0x003DF3C0 File Offset: 0x003DD5C0
	public void NKLLOKFFBFO()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.DEHJNGMHGAJ(JBEHMPDDMME.PFOLNEGNIPP().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.PDEFLCIEMFF(this.toLocId);
			epmphjgalbe.ALNEALEKFNB(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(149, epmphjgalbe.HDEKHFOKCKI());
		}
		finally
		{
			epmphjgalbe.OGPGOEJFIBO();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().LCEOGOCIMMB();
		JDCEFOFMGHB.HMJJPNDEKPP().LHHBOOJPBPH = true;
	}

	// Token: 0x0600840E RID: 33806 RVA: 0x003DF444 File Offset: 0x003DD644
	public void ANLLGONPBPB()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.PDEFLCIEMFF(JBEHMPDDMME.PFOLNEGNIPP().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.EIMEKHOFIEA(this.toLocId);
			epmphjgalbe.FLLJONHPLNA(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.HJPGADJMICM(-81, epmphjgalbe.IEJLLFECFHF());
		}
		finally
		{
			epmphjgalbe.HDKBMLOJLLC();
		}
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.JFIDAGABKID().LHHBOOJPBPH = true;
	}

	// Token: 0x0600840F RID: 33807 RVA: 0x003DF4C8 File Offset: 0x003DD6C8
	public void MIEMOJJPJKE()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().KCONDIDKLIB(-92, 1);
		JDCEFOFMGHB.HMJJPNDEKPP().DDAIBFBOENE();
		JDCEFOFMGHB.JFIDAGABKID().LHHBOOJPBPH = true;
	}

	// Token: 0x06008410 RID: 33808 RVA: 0x003DF4F0 File Offset: 0x003DD6F0
	public void BLPEKKIBJNM()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.PDEFLCIEMFF(JBEHMPDDMME.PFOLNEGNIPP().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.GOMLLPFFPNP(this.toLocId);
			epmphjgalbe.JIIKLOKAGIC(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().EILLJGEHCOH(104, epmphjgalbe.ALLANCHILCM());
		}
		finally
		{
			epmphjgalbe.PGLFHABMJPO();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().DDAIBFBOENE();
		JDCEFOFMGHB.JFIDAGABKID().LHHBOOJPBPH = false;
	}

	// Token: 0x06008411 RID: 33809 RVA: 0x003DF574 File Offset: 0x003DD774
	public void GBPKFBNIAFF()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.GOMLLPFFPNP(JBEHMPDDMME.EAJHPOJPPFA().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.FLLJONHPLNA(this.toLocId);
			epmphjgalbe.GOMLLPFFPNP(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.HJPGADJMICM(-128, epmphjgalbe.HDEKHFOKCKI());
		}
		finally
		{
			epmphjgalbe.HDKBMLOJLLC();
		}
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.JFIDAGABKID().LHHBOOJPBPH = true;
	}

	// Token: 0x06008412 RID: 33810 RVA: 0x003DF5F8 File Offset: 0x003DD7F8
	public void EHHIEAHFDMF()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.LHLOOIDHGMA(JBEHMPDDMME.PFOLNEGNIPP().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.DEHJNGMHGAJ(this.toLocId);
			epmphjgalbe.ENDMKPCFKND(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().HJPGADJMICM(-166, epmphjgalbe.PBOPEDMCKDD());
		}
		finally
		{
			epmphjgalbe.KNPHNLLMJKJ();
		}
		JDCEFOFMGHB.JFIDAGABKID().DDAIBFBOENE();
		JDCEFOFMGHB.IKGFHGKKCPG.MDBKHKBJNAO(true);
	}

	// Token: 0x06008413 RID: 33811 RVA: 0x003DF67C File Offset: 0x003DD87C
	public void OJAMAAJLFNM()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.PIGIIJLCADJ(-64, 0);
		JDCEFOFMGHB.JFIDAGABKID().LCEOGOCIMMB();
		JDCEFOFMGHB.MNJNNDHCDGG().LHHBOOJPBPH = true;
	}

	// Token: 0x06008414 RID: 33812 RVA: 0x003DF6A3 File Offset: 0x003DD8A3
	public void MAJMPPLEJAM()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(-106, 1);
		JDCEFOFMGHB.MNJNNDHCDGG().LCEOGOCIMMB();
		JDCEFOFMGHB.IKGFHGKKCPG.MDBKHKBJNAO(false);
	}

	// Token: 0x06008415 RID: 33813 RVA: 0x003DF6CC File Offset: 0x003DD8CC
	public void DNMKKMGDGKM()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.GOMLLPFFPNP(JBEHMPDDMME.EAJHPOJPPFA().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.LHLOOIDHGMA(this.toLocId);
			epmphjgalbe.FLLJONHPLNA(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(190, epmphjgalbe.PBOPEDMCKDD());
		}
		finally
		{
			epmphjgalbe.PMIGGJHLIDO();
		}
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.IKGFHGKKCPG.LHHBOOJPBPH = true;
	}

	// Token: 0x06008416 RID: 33814 RVA: 0x003DF750 File Offset: 0x003DD950
	public void KBFEDMEIHIH()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().PIGIIJLCADJ(89, 0);
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.JFIDAGABKID().HCFDADCKMCB(false);
	}

	// Token: 0x06008417 RID: 33815 RVA: 0x003DF778 File Offset: 0x003DD978
	public void OnLocClick()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.GOMLLPFFPNP(JBEHMPDDMME.IKGFHGKKCPG.KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.GOMLLPFFPNP(this.toLocId);
			epmphjgalbe.GOMLLPFFPNP(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.AKJKNCIKBBF(138, epmphjgalbe.JDPHBLHOLAD());
		}
		finally
		{
			epmphjgalbe.LMBPNFHKNGA();
		}
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.IKGFHGKKCPG.LHHBOOJPBPH = true;
	}

	// Token: 0x06008418 RID: 33816 RVA: 0x003DF7FC File Offset: 0x003DD9FC
	public void FOKLCMJNPFE()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.JDOLCNDNFGP(JBEHMPDDMME.EAJHPOJPPFA().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.JDOLCNDNFGP(this.toLocId);
			epmphjgalbe.EAOGDKDBENC(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().EILLJGEHCOH(2, epmphjgalbe.JDPHBLHOLAD());
		}
		finally
		{
			epmphjgalbe.LMBPNFHKNGA();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().LCEOGOCIMMB();
		JDCEFOFMGHB.IKGFHGKKCPG.MDBKHKBJNAO(false);
	}

	// Token: 0x06008419 RID: 33817 RVA: 0x003DF880 File Offset: 0x003DDA80
	public void FGOFJIHKGGJ()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.KPCGLGHDILI(JBEHMPDDMME.PFOLNEGNIPP().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.ENDMKPCFKND(this.toLocId);
			epmphjgalbe.ENDMKPCFKND(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.EILLJGEHCOH(-160, epmphjgalbe.JDPHBLHOLAD());
		}
		finally
		{
			epmphjgalbe.OGPGOEJFIBO();
		}
		JDCEFOFMGHB.HMJJPNDEKPP().LCEOGOCIMMB();
		JDCEFOFMGHB.IKGFHGKKCPG.MDBKHKBJNAO(false);
	}

	// Token: 0x0600841A RID: 33818 RVA: 0x003DF904 File Offset: 0x003DDB04
	public void PNMODIKJNPL()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.ENDMKPCFKND(JBEHMPDDMME.PLGADNLAEGN().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.EAOGDKDBENC(this.toLocId);
			epmphjgalbe.AEMAHNDEBKJ(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().HJPGADJMICM(195, epmphjgalbe.JDPHBLHOLAD());
		}
		finally
		{
			epmphjgalbe.PGLFHABMJPO();
		}
		JDCEFOFMGHB.HMJJPNDEKPP().DDAIBFBOENE();
		JDCEFOFMGHB.HMJJPNDEKPP().LHHBOOJPBPH = true;
	}

	// Token: 0x0600841B RID: 33819 RVA: 0x003DF988 File Offset: 0x003DDB88
	public void CNOGNBAECEI()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.AEMAHNDEBKJ(JBEHMPDDMME.BOKIOJFHNLD().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.ALNEALEKFNB(this.toLocId);
			epmphjgalbe.JDOLCNDNFGP(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().HJPGADJMICM(80, epmphjgalbe.ALLANCHILCM());
		}
		finally
		{
			epmphjgalbe.OGPGOEJFIBO();
		}
		JDCEFOFMGHB.JFIDAGABKID().LCEOGOCIMMB();
		JDCEFOFMGHB.IKGFHGKKCPG.MDBKHKBJNAO(false);
	}

	// Token: 0x0600841C RID: 33820 RVA: 0x003DFA0C File Offset: 0x003DDC0C
	public void EOBBPIJAMKP()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(-64, 0);
		JDCEFOFMGHB.IKGFHGKKCPG.LCEOGOCIMMB();
		JDCEFOFMGHB.MNJNNDHCDGG().HCFDADCKMCB(false);
	}

	// Token: 0x0600841D RID: 33821 RVA: 0x003DFA33 File Offset: 0x003DDC33
	public void PHFLHMMPGHI()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.KCONDIDKLIB(-169, 1);
		JDCEFOFMGHB.HMJJPNDEKPP().LCEOGOCIMMB();
		JDCEFOFMGHB.IKGFHGKKCPG.LHHBOOJPBPH = false;
	}

	// Token: 0x0600841E RID: 33822 RVA: 0x003DFA5A File Offset: 0x003DDC5A
	public void JILCOGFOCMB()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().PIGIIJLCADJ(165, 1);
		JDCEFOFMGHB.HMJJPNDEKPP().LCEOGOCIMMB();
		JDCEFOFMGHB.HMJJPNDEKPP().LHHBOOJPBPH = false;
	}

	// Token: 0x0600841F RID: 33823 RVA: 0x003DFA84 File Offset: 0x003DDC84
	public void BFOKHKHKPFK()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.LHLOOIDHGMA(JBEHMPDDMME.NPCAKEGNBHD().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.EAOGDKDBENC(this.toLocId);
			epmphjgalbe.DEHJNGMHGAJ(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.HJPGADJMICM(61, epmphjgalbe.JOCJNOBBELJ());
		}
		finally
		{
			epmphjgalbe.PGLFHABMJPO();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().LCEOGOCIMMB();
		JDCEFOFMGHB.HMJJPNDEKPP().MDBKHKBJNAO(true);
	}

	// Token: 0x06008420 RID: 33824 RVA: 0x003DFB08 File Offset: 0x003DDD08
	public void PLNDECBLCMG()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().KCONDIDKLIB(53, 1);
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.JFIDAGABKID().LHHBOOJPBPH = false;
	}

	// Token: 0x06008421 RID: 33825 RVA: 0x003DFB30 File Offset: 0x003DDD30
	public void AELDFBBHDLM()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.JIIKLOKAGIC(JBEHMPDDMME.IKGFHGKKCPG.KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.AEMAHNDEBKJ(this.toLocId);
			epmphjgalbe.GOMLLPFFPNP(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.HJPGADJMICM(16, epmphjgalbe.LAFILAEOPAJ());
		}
		finally
		{
			epmphjgalbe.PGLFHABMJPO();
		}
		JDCEFOFMGHB.JFIDAGABKID().DDAIBFBOENE();
		JDCEFOFMGHB.JFIDAGABKID().MDBKHKBJNAO(true);
	}

	// Token: 0x06008422 RID: 33826 RVA: 0x003DFBB4 File Offset: 0x003DDDB4
	public void DNIHJCPJFEP()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(89, 0);
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.JFIDAGABKID().HCFDADCKMCB(true);
	}

	// Token: 0x06008423 RID: 33827 RVA: 0x003DFBDC File Offset: 0x003DDDDC
	public void PJKOFGNBMMC()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.EAOGDKDBENC(JBEHMPDDMME.PFOLNEGNIPP().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.FLLJONHPLNA(this.toLocId);
			epmphjgalbe.ENDMKPCFKND(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().EILLJGEHCOH(-36, epmphjgalbe.JOCJNOBBELJ());
		}
		finally
		{
			epmphjgalbe.LMBPNFHKNGA();
		}
		JDCEFOFMGHB.JFIDAGABKID().LCEOGOCIMMB();
		JDCEFOFMGHB.IKGFHGKKCPG.HCFDADCKMCB(true);
	}

	// Token: 0x06008424 RID: 33828 RVA: 0x003DFC60 File Offset: 0x003DDE60
	public void CMABDJBNFOC()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.FLLJONHPLNA(JBEHMPDDMME.NPCAKEGNBHD().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.PDEFLCIEMFF(this.toLocId);
			epmphjgalbe.EAOGDKDBENC(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.EILLJGEHCOH(131, epmphjgalbe.NNEAJJNCGMK());
		}
		finally
		{
			epmphjgalbe.NCKMEIBFNGL();
		}
		JDCEFOFMGHB.IKGFHGKKCPG.LCEOGOCIMMB();
		JDCEFOFMGHB.IKGFHGKKCPG.LHHBOOJPBPH = true;
	}

	// Token: 0x06008425 RID: 33829 RVA: 0x003DFCE4 File Offset: 0x003DDEE4
	public void BHKNLIPLCOH()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.AKJKNCIKBBF(35, 0);
		JDCEFOFMGHB.IKGFHGKKCPG.LCEOGOCIMMB();
		JDCEFOFMGHB.IKGFHGKKCPG.MDBKHKBJNAO(true);
	}

	// Token: 0x06008426 RID: 33830 RVA: 0x003DFD0C File Offset: 0x003DDF0C
	public void LLLJAIFNGKH()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.ENDMKPCFKND(JBEHMPDDMME.NPCAKEGNBHD().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.FLLJONHPLNA(this.toLocId);
			epmphjgalbe.KPCGLGHDILI(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.EILLJGEHCOH(-84, epmphjgalbe.LAFILAEOPAJ());
		}
		finally
		{
			epmphjgalbe.LMBPNFHKNGA();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().DDAIBFBOENE();
		JDCEFOFMGHB.HMJJPNDEKPP().LHHBOOJPBPH = true;
	}

	// Token: 0x06008427 RID: 33831 RVA: 0x003DFD90 File Offset: 0x003DDF90
	public void ALKJDALHAIL()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.EIMEKHOFIEA(JBEHMPDDMME.JKIFIBEPICO().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.GOMLLPFFPNP(this.toLocId);
			epmphjgalbe.LHLOOIDHGMA(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.EILLJGEHCOH(-66, epmphjgalbe.NNEAJJNCGMK());
		}
		finally
		{
			epmphjgalbe.KNPHNLLMJKJ();
		}
		JDCEFOFMGHB.IKGFHGKKCPG.LCEOGOCIMMB();
		JDCEFOFMGHB.JFIDAGABKID().LHHBOOJPBPH = false;
	}

	// Token: 0x06008428 RID: 33832 RVA: 0x003DFE14 File Offset: 0x003DE014
	public void AOHCJOMOOGJ()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.JIIKLOKAGIC(JBEHMPDDMME.EAJHPOJPPFA().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.DEHJNGMHGAJ(this.toLocId);
			epmphjgalbe.PDEFLCIEMFF(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.AKJKNCIKBBF(164, epmphjgalbe.JDPHBLHOLAD());
		}
		finally
		{
			epmphjgalbe.HDKBMLOJLLC();
		}
		JDCEFOFMGHB.JFIDAGABKID().DDAIBFBOENE();
		JDCEFOFMGHB.JFIDAGABKID().MDBKHKBJNAO(false);
	}

	// Token: 0x06008429 RID: 33833 RVA: 0x003DFE98 File Offset: 0x003DE098
	public void KCDKLBAHLFM()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.ENDMKPCFKND(JBEHMPDDMME.PLGADNLAEGN().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.GOMLLPFFPNP(this.toLocId);
			epmphjgalbe.ENDMKPCFKND(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().EILLJGEHCOH(0, epmphjgalbe.JOCJNOBBELJ());
		}
		finally
		{
			epmphjgalbe.PGLFHABMJPO();
		}
		JDCEFOFMGHB.JFIDAGABKID().DDAIBFBOENE();
		JDCEFOFMGHB.HMJJPNDEKPP().MDBKHKBJNAO(true);
	}

	// Token: 0x0600842A RID: 33834 RVA: 0x003DFF1C File Offset: 0x003DE11C
	public void LLMMKHNJGMF()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.EAOGDKDBENC(JBEHMPDDMME.IKGFHGKKCPG.KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.ENDMKPCFKND(this.toLocId);
			epmphjgalbe.JDOLCNDNFGP(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().EILLJGEHCOH(-159, epmphjgalbe.ALLANCHILCM());
		}
		finally
		{
			epmphjgalbe.KNPHNLLMJKJ();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().DDAIBFBOENE();
		JDCEFOFMGHB.HMJJPNDEKPP().HCFDADCKMCB(true);
	}

	// Token: 0x0600842B RID: 33835 RVA: 0x003DFFA0 File Offset: 0x003DE1A0
	public void AGJOFLEIHFF()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.EIMEKHOFIEA(JBEHMPDDMME.PLGADNLAEGN().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.AEMAHNDEBKJ(this.toLocId);
			epmphjgalbe.EIMEKHOFIEA(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().EILLJGEHCOH(116, epmphjgalbe.HDEKHFOKCKI());
		}
		finally
		{
			epmphjgalbe.LMBPNFHKNGA();
		}
		JDCEFOFMGHB.HMJJPNDEKPP().LCEOGOCIMMB();
		JDCEFOFMGHB.JFIDAGABKID().MDBKHKBJNAO(false);
	}

	// Token: 0x0600842C RID: 33836 RVA: 0x003E0024 File Offset: 0x003DE224
	public void KIBGFFFIJMO()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.ALNEALEKFNB(JBEHMPDDMME.IKGFHGKKCPG.KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.LHLOOIDHGMA(this.toLocId);
			epmphjgalbe.EAOGDKDBENC(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().HJPGADJMICM(-128, epmphjgalbe.LAFILAEOPAJ());
		}
		finally
		{
			epmphjgalbe.OGPGOEJFIBO();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().LCEOGOCIMMB();
		JDCEFOFMGHB.JFIDAGABKID().HCFDADCKMCB(false);
	}

	// Token: 0x0600842D RID: 33837 RVA: 0x003E00A8 File Offset: 0x003DE2A8
	public void GICKLBBHDOG()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().PIGIIJLCADJ(-155, 1);
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.IKGFHGKKCPG.MDBKHKBJNAO(false);
	}

	// Token: 0x0600842E RID: 33838 RVA: 0x003E00CF File Offset: 0x003DE2CF
	public void AKBLAAGBALG()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().KCONDIDKLIB(133, 0);
		JDCEFOFMGHB.JFIDAGABKID().DDAIBFBOENE();
		JDCEFOFMGHB.HMJJPNDEKPP().MDBKHKBJNAO(false);
	}

	// Token: 0x0600842F RID: 33839 RVA: 0x003E00F6 File Offset: 0x003DE2F6
	public void IAOFLGNEBPC()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(-67, 1);
		JDCEFOFMGHB.MNJNNDHCDGG().DDAIBFBOENE();
		JDCEFOFMGHB.IKGFHGKKCPG.MDBKHKBJNAO(true);
	}

	// Token: 0x06008430 RID: 33840 RVA: 0x003E011D File Offset: 0x003DE31D
	public void NIJAKANEBKM()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.KCONDIDKLIB(158, 1);
		JDCEFOFMGHB.HMJJPNDEKPP().LCEOGOCIMMB();
		JDCEFOFMGHB.HMJJPNDEKPP().MDBKHKBJNAO(false);
	}

	// Token: 0x06008431 RID: 33841 RVA: 0x003E0144 File Offset: 0x003DE344
	public void CJLGJDIPCJB()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().KCONDIDKLIB(-110, 1);
		JDCEFOFMGHB.HMJJPNDEKPP().DDAIBFBOENE();
		JDCEFOFMGHB.IKGFHGKKCPG.HCFDADCKMCB(false);
	}

	// Token: 0x06008432 RID: 33842 RVA: 0x003E016B File Offset: 0x003DE36B
	public void DEPHAGPMCIA()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().PIGIIJLCADJ(-52, 0);
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.MNJNNDHCDGG().MDBKHKBJNAO(true);
	}

	// Token: 0x06008433 RID: 33843 RVA: 0x003E0194 File Offset: 0x003DE394
	public void PMDNMIDNGHG()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.PDEFLCIEMFF(JBEHMPDDMME.PFOLNEGNIPP().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.LHLOOIDHGMA(this.toLocId);
			epmphjgalbe.LHLOOIDHGMA(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(-178, epmphjgalbe.NNEAJJNCGMK());
		}
		finally
		{
			epmphjgalbe.OGPGOEJFIBO();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().LCEOGOCIMMB();
		JDCEFOFMGHB.HMJJPNDEKPP().LHHBOOJPBPH = false;
	}

	// Token: 0x06008434 RID: 33844 RVA: 0x003E0218 File Offset: 0x003DE418
	public void NICOEBICIHG()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(169, 1);
		JDCEFOFMGHB.HMJJPNDEKPP().LCEOGOCIMMB();
		JDCEFOFMGHB.HMJJPNDEKPP().MDBKHKBJNAO(true);
	}

	// Token: 0x06008435 RID: 33845 RVA: 0x003E023F File Offset: 0x003DE43F
	public void JODCHLLHCMJ()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().PIGIIJLCADJ(-191, 0);
		JDCEFOFMGHB.MNJNNDHCDGG().DDAIBFBOENE();
		JDCEFOFMGHB.MNJNNDHCDGG().MDBKHKBJNAO(false);
	}

	// Token: 0x06008436 RID: 33846 RVA: 0x003E0266 File Offset: 0x003DE466
	public void MAFBFHODAIC()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(88, 1);
		JDCEFOFMGHB.HMJJPNDEKPP().LCEOGOCIMMB();
		JDCEFOFMGHB.IKGFHGKKCPG.MDBKHKBJNAO(false);
	}

	// Token: 0x06008437 RID: 33847 RVA: 0x003E028D File Offset: 0x003DE48D
	public void KOCLKCIFDOI()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().KCONDIDKLIB(-159, 1);
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.JFIDAGABKID().HCFDADCKMCB(false);
	}

	// Token: 0x06008438 RID: 33848 RVA: 0x003E02B4 File Offset: 0x003DE4B4
	public void CIJADMOHAKH()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.AKJKNCIKBBF(-126, 0);
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.IKGFHGKKCPG.HCFDADCKMCB(false);
	}

	// Token: 0x06008439 RID: 33849 RVA: 0x003E02DC File Offset: 0x003DE4DC
	public void CIGPLGOAEIP()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.DEHJNGMHGAJ(JBEHMPDDMME.NPCAKEGNBHD().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.AEMAHNDEBKJ(this.toLocId);
			epmphjgalbe.DEHJNGMHGAJ(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.HJPGADJMICM(7, epmphjgalbe.JDPHBLHOLAD());
		}
		finally
		{
			epmphjgalbe.BKKEFKANGIM();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().LCEOGOCIMMB();
		JDCEFOFMGHB.MNJNNDHCDGG().LHHBOOJPBPH = true;
	}

	// Token: 0x0600843A RID: 33850 RVA: 0x003E0360 File Offset: 0x003DE560
	public void EMDGKHJOKBL()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().PIGIIJLCADJ(144, 0);
		JDCEFOFMGHB.JFIDAGABKID().DDAIBFBOENE();
		JDCEFOFMGHB.JFIDAGABKID().MDBKHKBJNAO(false);
	}

	// Token: 0x0600843B RID: 33851 RVA: 0x003E0387 File Offset: 0x003DE587
	public void BNJCCHNPDIF()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.AKJKNCIKBBF(165, 0);
		JDCEFOFMGHB.MNJNNDHCDGG().LCEOGOCIMMB();
		JDCEFOFMGHB.HMJJPNDEKPP().HCFDADCKMCB(true);
	}

	// Token: 0x0600843C RID: 33852 RVA: 0x003E03B0 File Offset: 0x003DE5B0
	public void LJECKELOKBI()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.FLLJONHPLNA(JBEHMPDDMME.EAJHPOJPPFA().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.EIMEKHOFIEA(this.toLocId);
			epmphjgalbe.GOMLLPFFPNP(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(-45, epmphjgalbe.NNEAJJNCGMK());
		}
		finally
		{
			epmphjgalbe.BKKEFKANGIM();
		}
		JDCEFOFMGHB.JFIDAGABKID().DDAIBFBOENE();
		JDCEFOFMGHB.MNJNNDHCDGG().LHHBOOJPBPH = true;
	}

	// Token: 0x0600843D RID: 33853 RVA: 0x003E0434 File Offset: 0x003DE634
	public void DNLIOLKPIKF()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.JIIKLOKAGIC(JBEHMPDDMME.EAJHPOJPPFA().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.ENDMKPCFKND(this.toLocId);
			epmphjgalbe.DEHJNGMHGAJ(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.HJPGADJMICM(-47, epmphjgalbe.LAFILAEOPAJ());
		}
		finally
		{
			epmphjgalbe.HDKBMLOJLLC();
		}
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.HMJJPNDEKPP().LHHBOOJPBPH = false;
	}

	// Token: 0x0600843E RID: 33854 RVA: 0x003E04B8 File Offset: 0x003DE6B8
	public void NBFBDPLOHBH()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.PIGIIJLCADJ(130, 1);
		JDCEFOFMGHB.HMJJPNDEKPP().LCEOGOCIMMB();
		JDCEFOFMGHB.HMJJPNDEKPP().HCFDADCKMCB(false);
	}

	// Token: 0x0600843F RID: 33855 RVA: 0x003E04E0 File Offset: 0x003DE6E0
	public void ONOLCBFDLJD()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.GOMLLPFFPNP(JBEHMPDDMME.PLGADNLAEGN().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.FLLJONHPLNA(this.toLocId);
			epmphjgalbe.PDEFLCIEMFF(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.AKJKNCIKBBF(-75, epmphjgalbe.JOCJNOBBELJ());
		}
		finally
		{
			epmphjgalbe.HDKBMLOJLLC();
		}
		JDCEFOFMGHB.JFIDAGABKID().LCEOGOCIMMB();
		JDCEFOFMGHB.MNJNNDHCDGG().MDBKHKBJNAO(false);
	}

	// Token: 0x06008440 RID: 33856 RVA: 0x003E0564 File Offset: 0x003DE764
	public void MLGAFJKANMP()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.LHLOOIDHGMA(JBEHMPDDMME.NPCAKEGNBHD().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.DEHJNGMHGAJ(this.toLocId);
			epmphjgalbe.AEMAHNDEBKJ(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().EILLJGEHCOH(46, epmphjgalbe.IEJLLFECFHF());
		}
		finally
		{
			epmphjgalbe.OGPGOEJFIBO();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().LCEOGOCIMMB();
		JDCEFOFMGHB.IKGFHGKKCPG.LHHBOOJPBPH = true;
	}

	// Token: 0x06008441 RID: 33857 RVA: 0x003E05E8 File Offset: 0x003DE7E8
	public void HMFHMGCPEFI()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.JIIKLOKAGIC(JBEHMPDDMME.EAJHPOJPPFA().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.GOMLLPFFPNP(this.toLocId);
			epmphjgalbe.ENDMKPCFKND(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(126, epmphjgalbe.JOCJNOBBELJ());
		}
		finally
		{
			epmphjgalbe.NCKMEIBFNGL();
		}
		JDCEFOFMGHB.HMJJPNDEKPP().LCEOGOCIMMB();
		JDCEFOFMGHB.IKGFHGKKCPG.HCFDADCKMCB(false);
	}

	// Token: 0x06008442 RID: 33858 RVA: 0x003E066C File Offset: 0x003DE86C
	public void NEHKDMECLID()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().PIGIIJLCADJ(6, 1);
		JDCEFOFMGHB.IKGFHGKKCPG.DDAIBFBOENE();
		JDCEFOFMGHB.JFIDAGABKID().MDBKHKBJNAO(true);
	}

	// Token: 0x06008443 RID: 33859 RVA: 0x003E0693 File Offset: 0x003DE893
	public void KFCDOJHFIJP()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.KCONDIDKLIB(-172, 1);
		JDCEFOFMGHB.JFIDAGABKID().LCEOGOCIMMB();
		JDCEFOFMGHB.MNJNNDHCDGG().MDBKHKBJNAO(false);
	}

	// Token: 0x06008444 RID: 33860 RVA: 0x003E06BC File Offset: 0x003DE8BC
	public void MJEGPEGANBJ()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.EAOGDKDBENC(JBEHMPDDMME.PFOLNEGNIPP().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.JIIKLOKAGIC(this.toLocId);
			epmphjgalbe.ENDMKPCFKND(this.toPointId);
			NJMHLCGIAJI.IKGFHGKKCPG.EILLJGEHCOH(82, epmphjgalbe.ALLANCHILCM());
		}
		finally
		{
			epmphjgalbe.NCKMEIBFNGL();
		}
		JDCEFOFMGHB.MNJNNDHCDGG().DDAIBFBOENE();
		JDCEFOFMGHB.JFIDAGABKID().LHHBOOJPBPH = false;
	}

	// Token: 0x06008445 RID: 33861 RVA: 0x003E0740 File Offset: 0x003DE940
	public void KHCAEMHLMPC()
	{
		NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(-44, 0);
		JDCEFOFMGHB.JFIDAGABKID().LCEOGOCIMMB();
		JDCEFOFMGHB.MNJNNDHCDGG().LHHBOOJPBPH = true;
	}

	// Token: 0x06008446 RID: 33862 RVA: 0x003E0768 File Offset: 0x003DE968
	public void OOBJJFCIAIC()
	{
		EPMPHJGALBE epmphjgalbe = new EPMPHJGALBE();
		try
		{
			epmphjgalbe.EIMEKHOFIEA(JBEHMPDDMME.BPPFAOOCENN().KFHELHGLNMH.PNEDPPPEFFG);
			epmphjgalbe.PDEFLCIEMFF(this.toLocId);
			epmphjgalbe.KPCGLGHDILI(this.toPointId);
			NJMHLCGIAJI.EAJGHMMBAFP().AKJKNCIKBBF(132, epmphjgalbe.JDPHBLHOLAD());
		}
		finally
		{
			epmphjgalbe.HDKBMLOJLLC();
		}
		JDCEFOFMGHB.JFIDAGABKID().LCEOGOCIMMB();
		JDCEFOFMGHB.IKGFHGKKCPG.LHHBOOJPBPH = false;
	}

	// Token: 0x06008447 RID: 33863 RVA: 0x003E07EC File Offset: 0x003DE9EC
	public void JMGLNLJFIAP()
	{
		NJMHLCGIAJI.IKGFHGKKCPG.KCONDIDKLIB(185, 1);
		JDCEFOFMGHB.JFIDAGABKID().DDAIBFBOENE();
		JDCEFOFMGHB.HMJJPNDEKPP().MDBKHKBJNAO(false);
	}

	// Token: 0x040012A9 RID: 4777
	public int toLocId;

	// Token: 0x040012AA RID: 4778
	public int toPointId;

	// Token: 0x040012AB RID: 4779
	public Button btn;

	// Token: 0x040012AC RID: 4780
	public Text locName;

	// Token: 0x040012AD RID: 4781
	public int minimalLevel = 10;
}
