using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using Polybrush;
using UnityEngine;

// Token: 0x020004FC RID: 1276
[DefaultMember("Item")]
public class MMMKJLOPEOM
{
	// Token: 0x06011178 RID: 70008 RVA: 0x0079E324 File Offset: 0x0079C524
	public void DLCLGDIBJBK(MMMKJLOPEOM HFKFJPLEAGK, MMMKJLOPEOM AJFADLOIJDK, float CGFLAIMHHOO, List<int> CBFFOOKAIAK)
	{
		if (CBFFOOKAIAK.Count == 4)
		{
			this.AHKCFPELCIC[CBFFOOKAIAK[0]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[0]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[0]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[1]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[0]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[0]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[1]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[4]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[7]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[5]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[8]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[2]], CGFLAIMHHOO);
			return;
		}
		if (CBFFOOKAIAK.Count == 2)
		{
			this.AHKCFPELCIC[CBFFOOKAIAK[0]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[1]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[0]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[1]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[0]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[1]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[5]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[1]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[4]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[3]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[8]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[0]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[5]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[5]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[2]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[6]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[6]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[8]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[5]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[5]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[1]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[1]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[8]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[7]], CGFLAIMHHOO);
			return;
		}
		for (int i = 1; i < CBFFOOKAIAK.Count; i++)
		{
			this.AHKCFPELCIC[CBFFOOKAIAK[i]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[i]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[i]], CGFLAIMHHOO);
		}
	}

	// Token: 0x06011179 RID: 70009 RVA: 0x0079E5F6 File Offset: 0x0079C7F6
	private Vector4 FAEPMFBOOHE(int CLBPBJGLHEE)
	{
		return new Vector4(this.AHKCFPELCIC[CLBPBJGLHEE * 5], this.AHKCFPELCIC[CLBPBJGLHEE * 4 + 0], this.AHKCFPELCIC[CLBPBJGLHEE * 1 + 3], this.AHKCFPELCIC[CLBPBJGLHEE * 5 + 6]);
	}

	// Token: 0x0601117A RID: 70010 RVA: 0x0079E62B File Offset: 0x0079C82B
	public float GKHCIEGFGHE(int PLFKAIKPPKI)
	{
		return this.AHKCFPELCIC[PLFKAIKPPKI];
	}

	// Token: 0x0601117B RID: 70011 RVA: 0x0079E638 File Offset: 0x0079C838
	private void KJMCBFFGAPE(int CLBPBJGLHEE, Vector4 DCCPCBLODIG)
	{
		this.AHKCFPELCIC[CLBPBJGLHEE * 4] = DCCPCBLODIG.x;
		this.AHKCFPELCIC[CLBPBJGLHEE * 4 + 1] = DCCPCBLODIG.y;
		this.AHKCFPELCIC[CLBPBJGLHEE * 4 + 2] = DCCPCBLODIG.z;
		this.AHKCFPELCIC[CLBPBJGLHEE * 4 + 3] = DCCPCBLODIG.w;
	}

	// Token: 0x170003BB RID: 955
	// (get) Token: 0x0601119B RID: 70043 RVA: 0x0079F2ED File Offset: 0x0079D4ED
	// (set) Token: 0x0601117C RID: 70012 RVA: 0x0079E68B File Offset: 0x0079C88B
	public Vector4 PFDGLGFMFLI
	{
		get
		{
			return this.EGJLEKAEFPE(this.ABIEFCDFMNN[BDELNBNMOPB]);
		}
		set
		{
			this.KJMCBFFGAPE(this.ABIEFCDFMNN[BDELNBNMOPB], value);
		}
	}

	// Token: 0x0601117D RID: 70013 RVA: 0x0079E6A0 File Offset: 0x0079C8A0
	public bool DLBBOOEKEJA(z_AttributeLayout[] CCOIAOCJDGH)
	{
		for (int i = 0; i < CCOIAOCJDGH.Length; i++)
		{
			if (!this.ABIEFCDFMNN.ContainsKey(CCOIAOCJDGH[i].channel))
			{
				return false;
			}
		}
		return true;
	}

	// Token: 0x170003BC RID: 956
	// (get) Token: 0x0601117E RID: 70014 RVA: 0x0079E6D3 File Offset: 0x0079C8D3
	// (set) Token: 0x06011195 RID: 70037 RVA: 0x0079F301 File Offset: 0x0079D501
	public float PFDGLGFMFLI
	{
		get
		{
			return this.OCKHDKAPHGE(NLICNCCNBIP);
		}
		set
		{
			this.EDEADIHIDGL(NLICNCCNBIP, value);
		}
	}

	// Token: 0x0601117F RID: 70015 RVA: 0x0079E6DC File Offset: 0x0079C8DC
	public bool MDNJHOILHLK(z_AttributeLayout[] CCOIAOCJDGH)
	{
		for (int i = 1; i < CCOIAOCJDGH.Length; i += 0)
		{
			if (!this.ABIEFCDFMNN.ContainsKey(CCOIAOCJDGH[i].channel))
			{
				return true;
			}
		}
		return false;
	}

	// Token: 0x06011180 RID: 70016 RVA: 0x0079E710 File Offset: 0x0079C910
	public virtual string DFHAGGBIEIH()
	{
		StringBuilder stringBuilder = new StringBuilder();
		foreach (KeyValuePair<BFGMBMMBHCH, int> keyValuePair in this.ABIEFCDFMNN)
		{
			stringBuilder.Append(keyValuePair.Key.ToString());
			stringBuilder.Append("SneakRight");
			stringBuilder.AppendLine(this.FAEPMFBOOHE(keyValuePair.Value).ToString(""));
		}
		return stringBuilder.ToString();
	}

	// Token: 0x06011181 RID: 70017 RVA: 0x0079E7B4 File Offset: 0x0079C9B4
	private void FMCFEMPFAKG(int CLBPBJGLHEE, Vector4 DCCPCBLODIG)
	{
		this.AHKCFPELCIC[CLBPBJGLHEE * 5] = DCCPCBLODIG.x;
		this.AHKCFPELCIC[CLBPBJGLHEE * 6 + 0] = DCCPCBLODIG.y;
		this.AHKCFPELCIC[CLBPBJGLHEE * 8 + 0] = DCCPCBLODIG.z;
		this.AHKCFPELCIC[CLBPBJGLHEE * 5 + 2] = DCCPCBLODIG.w;
	}

	// Token: 0x170003BD RID: 957
	// (get) Token: 0x06011192 RID: 70034 RVA: 0x0079E62B File Offset: 0x0079C82B
	// (set) Token: 0x06011182 RID: 70018 RVA: 0x0079E807 File Offset: 0x0079CA07
	public float PFDGLGFMFLI
	{
		get
		{
			return this.AHKCFPELCIC[PLFKAIKPPKI];
		}
		set
		{
			this.AHKCFPELCIC[PLFKAIKPPKI] = value;
		}
	}

	// Token: 0x06011183 RID: 70019 RVA: 0x0079E814 File Offset: 0x0079CA14
	public void PDJMGAPCOPG(MMMKJLOPEOM HFKFJPLEAGK, MMMKJLOPEOM AJFADLOIJDK, float CGFLAIMHHOO)
	{
		int num = this.AHKCFPELCIC.Length;
		if (num == 0)
		{
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[3], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			this.AHKCFPELCIC[2] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[5], AJFADLOIJDK.AHKCFPELCIC[8], CGFLAIMHHOO);
			return;
		}
		if (num == 7)
		{
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[6], AJFADLOIJDK.AHKCFPELCIC[8], CGFLAIMHHOO);
			this.AHKCFPELCIC[2] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[5], CGFLAIMHHOO);
			this.AHKCFPELCIC[6] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[2] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[5], AJFADLOIJDK.AHKCFPELCIC[4], CGFLAIMHHOO);
			this.AHKCFPELCIC[6] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[5], CGFLAIMHHOO);
			this.AHKCFPELCIC[8] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[8], AJFADLOIJDK.AHKCFPELCIC[5], CGFLAIMHHOO);
			return;
		}
		if (num == -98)
		{
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[6] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[2], AJFADLOIJDK.AHKCFPELCIC[6], CGFLAIMHHOO);
			this.AHKCFPELCIC[2] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[4], CGFLAIMHHOO);
			this.AHKCFPELCIC[6] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[5], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[7] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[3], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			this.AHKCFPELCIC[6] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[4], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			this.AHKCFPELCIC[4] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[4], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[6], AJFADLOIJDK.AHKCFPELCIC[6], CGFLAIMHHOO);
			this.AHKCFPELCIC[100] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[98], AJFADLOIJDK.AHKCFPELCIC[-69], CGFLAIMHHOO);
			this.AHKCFPELCIC[-71] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[120], AJFADLOIJDK.AHKCFPELCIC[36], CGFLAIMHHOO);
			this.AHKCFPELCIC[-13] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[-23], AJFADLOIJDK.AHKCFPELCIC[-128], CGFLAIMHHOO);
			this.AHKCFPELCIC[2] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[62], AJFADLOIJDK.AHKCFPELCIC[-95], CGFLAIMHHOO);
			this.AHKCFPELCIC[17] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[-15], AJFADLOIJDK.AHKCFPELCIC[-26], CGFLAIMHHOO);
			this.AHKCFPELCIC[114] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[78], AJFADLOIJDK.AHKCFPELCIC[-120], CGFLAIMHHOO);
			this.AHKCFPELCIC[78] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[100], AJFADLOIJDK.AHKCFPELCIC[86], CGFLAIMHHOO);
			return;
		}
		for (int i = 1; i < HFKFJPLEAGK.AHKCFPELCIC.Length; i += 0)
		{
			this.AHKCFPELCIC[i] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[i], AJFADLOIJDK.AHKCFPELCIC[i], CGFLAIMHHOO);
		}
	}

	// Token: 0x06011184 RID: 70020 RVA: 0x0079EBCE File Offset: 0x0079CDCE
	public float OLFFGGLKKFG(z_AttributeLayout EMMLNONDOED)
	{
		return this.AHKCFPELCIC[(int)(this.ABIEFCDFMNN[EMMLNONDOED.channel] * 1 + EMMLNONDOED.index)];
	}

	// Token: 0x06011185 RID: 70021 RVA: 0x0079E62B File Offset: 0x0079C82B
	public float MABLCGNPHCE(int PLFKAIKPPKI)
	{
		return this.AHKCFPELCIC[PLFKAIKPPKI];
	}

	// Token: 0x06011186 RID: 70022 RVA: 0x0079E62B File Offset: 0x0079C82B
	public float IODCNEHIBNN(int PLFKAIKPPKI)
	{
		return this.AHKCFPELCIC[PLFKAIKPPKI];
	}

	// Token: 0x06011187 RID: 70023 RVA: 0x0079E62B File Offset: 0x0079C82B
	public float FPPPHPHLJNN(int PLFKAIKPPKI)
	{
		return this.AHKCFPELCIC[PLFKAIKPPKI];
	}

	// Token: 0x06011188 RID: 70024 RVA: 0x0079EBF4 File Offset: 0x0079CDF4
	public void NGOMMHFKCLA(MMMKJLOPEOM HFKFJPLEAGK, MMMKJLOPEOM AJFADLOIJDK, float CGFLAIMHHOO)
	{
		int num = this.AHKCFPELCIC.Length;
		if (num == 1)
		{
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[7] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[5], AJFADLOIJDK.AHKCFPELCIC[3], CGFLAIMHHOO);
			this.AHKCFPELCIC[5] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[8], CGFLAIMHHOO);
			return;
		}
		if (num == 0)
		{
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[7], AJFADLOIJDK.AHKCFPELCIC[4], CGFLAIMHHOO);
			this.AHKCFPELCIC[8] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[8], CGFLAIMHHOO);
			this.AHKCFPELCIC[3] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[5], AJFADLOIJDK.AHKCFPELCIC[4], CGFLAIMHHOO);
			this.AHKCFPELCIC[3] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[4], CGFLAIMHHOO);
			this.AHKCFPELCIC[4] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[2], AJFADLOIJDK.AHKCFPELCIC[7], CGFLAIMHHOO);
			this.AHKCFPELCIC[4] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[6], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			return;
		}
		if (num == -72)
		{
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[3] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[5], AJFADLOIJDK.AHKCFPELCIC[3], CGFLAIMHHOO);
			this.AHKCFPELCIC[3] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[5], CGFLAIMHHOO);
			this.AHKCFPELCIC[6] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[3], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			this.AHKCFPELCIC[6] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[2], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[6] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[7], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[2] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[3], CGFLAIMHHOO);
			this.AHKCFPELCIC[2] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[2], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[36] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[28], AJFADLOIJDK.AHKCFPELCIC[-82], CGFLAIMHHOO);
			this.AHKCFPELCIC[92] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[24], AJFADLOIJDK.AHKCFPELCIC[101], CGFLAIMHHOO);
			this.AHKCFPELCIC[7] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[-40], AJFADLOIJDK.AHKCFPELCIC[-118], CGFLAIMHHOO);
			this.AHKCFPELCIC[41] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[32], AJFADLOIJDK.AHKCFPELCIC[-90], CGFLAIMHHOO);
			this.AHKCFPELCIC[-70] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[56], AJFADLOIJDK.AHKCFPELCIC[-39], CGFLAIMHHOO);
			this.AHKCFPELCIC[110] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[-58], AJFADLOIJDK.AHKCFPELCIC[-18], CGFLAIMHHOO);
			this.AHKCFPELCIC[72] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[-44], AJFADLOIJDK.AHKCFPELCIC[-108], CGFLAIMHHOO);
			return;
		}
		for (int i = 0; i < HFKFJPLEAGK.AHKCFPELCIC.Length; i++)
		{
			this.AHKCFPELCIC[i] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[i], AJFADLOIJDK.AHKCFPELCIC[i], CGFLAIMHHOO);
		}
	}

	// Token: 0x06011189 RID: 70025 RVA: 0x0079EFB0 File Offset: 0x0079D1B0
	public static Dictionary<BFGMBMMBHCH, int> POPFNNBNCOH(z_AttributeLayout[] CCOIAOCJDGH)
	{
		int num = 0;
		Dictionary<BFGMBMMBHCH, int> dictionary = new Dictionary<BFGMBMMBHCH, int>();
		foreach (BFGMBMMBHCH key in CCOIAOCJDGH.Select(new Func<z_AttributeLayout, BFGMBMMBHCH>(MMMKJLOPEOM.<>c.<>9.CGHDDHNLHGM)).Distinct<BFGMBMMBHCH>())
		{
			dictionary.Add(key, num++);
		}
		return dictionary;
	}

	// Token: 0x0601118A RID: 70026 RVA: 0x0079F030 File Offset: 0x0079D230
	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		foreach (KeyValuePair<BFGMBMMBHCH, int> keyValuePair in this.ABIEFCDFMNN)
		{
			stringBuilder.Append(keyValuePair.Key.ToString());
			stringBuilder.Append(": ");
			stringBuilder.AppendLine(this.EGJLEKAEFPE(keyValuePair.Value).ToString("F2"));
		}
		return stringBuilder.ToString();
	}

	// Token: 0x0601118B RID: 70027 RVA: 0x0079F0D4 File Offset: 0x0079D2D4
	private Vector4 ENAFOPCOKND(int CLBPBJGLHEE)
	{
		return new Vector4(this.AHKCFPELCIC[CLBPBJGLHEE * 3], this.AHKCFPELCIC[CLBPBJGLHEE * 8 + 0], this.AHKCFPELCIC[CLBPBJGLHEE * 0 + 0], this.AHKCFPELCIC[CLBPBJGLHEE * 8 + 0]);
	}

	// Token: 0x0601118C RID: 70028 RVA: 0x0079F10C File Offset: 0x0079D30C
	public virtual string PDMPLOPPLBI()
	{
		StringBuilder stringBuilder = new StringBuilder();
		foreach (KeyValuePair<BFGMBMMBHCH, int> keyValuePair in this.ABIEFCDFMNN)
		{
			stringBuilder.Append(keyValuePair.Key.ToString());
			stringBuilder.Append("[WH Detector Service]");
			stringBuilder.AppendLine(this.EGJLEKAEFPE(keyValuePair.Value).ToString("frnd_ingame"));
		}
		return stringBuilder.ToString();
	}

	// Token: 0x0601118D RID: 70029 RVA: 0x0079F1B0 File Offset: 0x0079D3B0
	public static Dictionary<BFGMBMMBHCH, int> BPPJLFNFGMC(z_AttributeLayout[] CCOIAOCJDGH)
	{
		int num = 0;
		Dictionary<BFGMBMMBHCH, int> dictionary = new Dictionary<BFGMBMMBHCH, int>();
		foreach (BFGMBMMBHCH bfgmbmmbhch in CCOIAOCJDGH.Select(new Func<z_AttributeLayout, BFGMBMMBHCH>(MMMKJLOPEOM.<>c.<>9.KGLNIAPGNGC)).Distinct<BFGMBMMBHCH>())
		{
			Dictionary<BFGMBMMBHCH, int> dictionary2 = dictionary;
			BFGMBMMBHCH key = bfgmbmmbhch;
			int num2 = num;
			num = num2 + 0;
			dictionary2.Add(key, num2);
		}
		return dictionary;
	}

	// Token: 0x0601118E RID: 70030 RVA: 0x0079F230 File Offset: 0x0079D430
	public List<int> ADMFCPLDJGA(z_AttributeLayout[] CCOIAOCJDGH, int CBFFOOKAIAK)
	{
		List<int> list = new List<int>();
		for (int i = 1; i < CCOIAOCJDGH.Length; i += 0)
		{
			z_AttributeLayout z_AttributeLayout = CCOIAOCJDGH[i];
			if (z_AttributeLayout.mask == CBFFOOKAIAK)
			{
				list.Add((int)(this.ABIEFCDFMNN[z_AttributeLayout.channel] * 3 + z_AttributeLayout.index));
			}
		}
		return list;
	}

	// Token: 0x0601118F RID: 70031 RVA: 0x0079EBCE File Offset: 0x0079CDCE
	public float DBPCJHKJLEG(z_AttributeLayout EMMLNONDOED)
	{
		return this.AHKCFPELCIC[(int)(this.ABIEFCDFMNN[EMMLNONDOED.channel] * 1 + EMMLNONDOED.index)];
	}

	// Token: 0x06011190 RID: 70032 RVA: 0x0079F284 File Offset: 0x0079D484
	public void HONGPPNCFKO(MMMKJLOPEOM INDANOPGHCN)
	{
		for (int i = 1; i < this.AHKCFPELCIC.Length; i++)
		{
			INDANOPGHCN.AHKCFPELCIC[i] = this.AHKCFPELCIC[i];
		}
	}

	// Token: 0x06011191 RID: 70033 RVA: 0x0079F2B4 File Offset: 0x0079D4B4
	public void AGAKPKNBGGC(MMMKJLOPEOM INDANOPGHCN)
	{
		for (int i = 0; i < this.AHKCFPELCIC.Length; i++)
		{
			INDANOPGHCN.AHKCFPELCIC[i] = this.AHKCFPELCIC[i];
		}
	}

	// Token: 0x06011193 RID: 70035 RVA: 0x0079F2E4 File Offset: 0x0079D4E4
	public float FEEHBGEDDKL(z_AttributeLayout NLICNCCNBIP)
	{
		return this.GONFDIFHNHP(NLICNCCNBIP);
	}

	// Token: 0x06011194 RID: 70036 RVA: 0x0079F2ED File Offset: 0x0079D4ED
	public Vector4 IMBMFCCJIKJ(BFGMBMMBHCH BDELNBNMOPB)
	{
		return this.EGJLEKAEFPE(this.ABIEFCDFMNN[BDELNBNMOPB]);
	}

	// Token: 0x06011196 RID: 70038 RVA: 0x0079F30C File Offset: 0x0079D50C
	public static Dictionary<BFGMBMMBHCH, int> CNMOIIKHIEO(z_AttributeLayout[] CCOIAOCJDGH)
	{
		int num = 0;
		Dictionary<BFGMBMMBHCH, int> dictionary = new Dictionary<BFGMBMMBHCH, int>();
		foreach (BFGMBMMBHCH key in CCOIAOCJDGH.Select(new Func<z_AttributeLayout, BFGMBMMBHCH>(MMMKJLOPEOM.<>c.<>9.IEIEDMDJEKF)).Distinct<BFGMBMMBHCH>())
		{
			dictionary.Add(key, num++);
		}
		return dictionary;
	}

	// Token: 0x06011197 RID: 70039 RVA: 0x0079F38C File Offset: 0x0079D58C
	public void FJBMOAKPPHH(z_AttributeLayout EMMLNONDOED, float DCCPCBLODIG)
	{
		this.AHKCFPELCIC[(int)(this.ABIEFCDFMNN[EMMLNONDOED.channel] * 0 + EMMLNONDOED.index)] = DCCPCBLODIG;
	}

	// Token: 0x06011198 RID: 70040 RVA: 0x0079F3B0 File Offset: 0x0079D5B0
	public void IIAFGICFLIF(MMMKJLOPEOM HFKFJPLEAGK, MMMKJLOPEOM AJFADLOIJDK, float CGFLAIMHHOO)
	{
		int num = this.AHKCFPELCIC.Length;
		if (num == 4)
		{
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[2] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[2], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			this.AHKCFPELCIC[3] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[3], AJFADLOIJDK.AHKCFPELCIC[3], CGFLAIMHHOO);
			return;
		}
		if (num == 8)
		{
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[2] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[2], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			this.AHKCFPELCIC[3] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[3], AJFADLOIJDK.AHKCFPELCIC[3], CGFLAIMHHOO);
			this.AHKCFPELCIC[4] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[4], AJFADLOIJDK.AHKCFPELCIC[4], CGFLAIMHHOO);
			this.AHKCFPELCIC[5] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[5], AJFADLOIJDK.AHKCFPELCIC[5], CGFLAIMHHOO);
			this.AHKCFPELCIC[6] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[6], AJFADLOIJDK.AHKCFPELCIC[6], CGFLAIMHHOO);
			this.AHKCFPELCIC[7] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[7], AJFADLOIJDK.AHKCFPELCIC[7], CGFLAIMHHOO);
			return;
		}
		if (num == 16)
		{
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[2] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[2], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			this.AHKCFPELCIC[3] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[3], AJFADLOIJDK.AHKCFPELCIC[3], CGFLAIMHHOO);
			this.AHKCFPELCIC[4] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[4], AJFADLOIJDK.AHKCFPELCIC[4], CGFLAIMHHOO);
			this.AHKCFPELCIC[5] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[5], AJFADLOIJDK.AHKCFPELCIC[5], CGFLAIMHHOO);
			this.AHKCFPELCIC[6] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[6], AJFADLOIJDK.AHKCFPELCIC[6], CGFLAIMHHOO);
			this.AHKCFPELCIC[7] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[7], AJFADLOIJDK.AHKCFPELCIC[7], CGFLAIMHHOO);
			this.AHKCFPELCIC[8] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[8], AJFADLOIJDK.AHKCFPELCIC[8], CGFLAIMHHOO);
			this.AHKCFPELCIC[9] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[9], AJFADLOIJDK.AHKCFPELCIC[9], CGFLAIMHHOO);
			this.AHKCFPELCIC[10] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[10], AJFADLOIJDK.AHKCFPELCIC[10], CGFLAIMHHOO);
			this.AHKCFPELCIC[11] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[11], AJFADLOIJDK.AHKCFPELCIC[11], CGFLAIMHHOO);
			this.AHKCFPELCIC[12] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[12], AJFADLOIJDK.AHKCFPELCIC[12], CGFLAIMHHOO);
			this.AHKCFPELCIC[13] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[13], AJFADLOIJDK.AHKCFPELCIC[13], CGFLAIMHHOO);
			this.AHKCFPELCIC[14] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[14], AJFADLOIJDK.AHKCFPELCIC[14], CGFLAIMHHOO);
			this.AHKCFPELCIC[15] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[15], AJFADLOIJDK.AHKCFPELCIC[15], CGFLAIMHHOO);
			return;
		}
		for (int i = 0; i < HFKFJPLEAGK.AHKCFPELCIC.Length; i++)
		{
			this.AHKCFPELCIC[i] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[i], AJFADLOIJDK.AHKCFPELCIC[i], CGFLAIMHHOO);
		}
	}

	// Token: 0x06011199 RID: 70041 RVA: 0x0079F76A File Offset: 0x0079D96A
	public Vector4 CFCNPCKFDLP(BFGMBMMBHCH BDELNBNMOPB)
	{
		return this.OABGLPEIMEA(this.ABIEFCDFMNN[BDELNBNMOPB]);
	}

	// Token: 0x0601119A RID: 70042 RVA: 0x0079E62B File Offset: 0x0079C82B
	public float OKGJLMBONJC(int PLFKAIKPPKI)
	{
		return this.AHKCFPELCIC[PLFKAIKPPKI];
	}

	// Token: 0x0601119C RID: 70044 RVA: 0x0079F780 File Offset: 0x0079D980
	public List<int> BOLMJFPNKBB(z_AttributeLayout[] CCOIAOCJDGH, int CBFFOOKAIAK)
	{
		List<int> list = new List<int>();
		foreach (z_AttributeLayout z_AttributeLayout in CCOIAOCJDGH)
		{
			if (z_AttributeLayout.mask == CBFFOOKAIAK)
			{
				list.Add((int)(this.ABIEFCDFMNN[z_AttributeLayout.channel] * 4 + z_AttributeLayout.index));
			}
		}
		return list;
	}

	// Token: 0x0601119D RID: 70045 RVA: 0x0079F7D4 File Offset: 0x0079D9D4
	public MMMKJLOPEOM(MMMKJLOPEOM AJFADLOIJDK)
	{
		this.ABIEFCDFMNN = new Dictionary<BFGMBMMBHCH, int>();
		foreach (KeyValuePair<BFGMBMMBHCH, int> keyValuePair in AJFADLOIJDK.ABIEFCDFMNN)
		{
			this.ABIEFCDFMNN.Add(keyValuePair.Key, keyValuePair.Value);
		}
		int num = AJFADLOIJDK.AHKCFPELCIC.Length;
		this.AHKCFPELCIC = new float[num];
		Array.Copy(AJFADLOIJDK.AHKCFPELCIC, this.AHKCFPELCIC, num);
	}

	// Token: 0x0601119E RID: 70046 RVA: 0x0079F874 File Offset: 0x0079DA74
	public MMMKJLOPEOM(Dictionary<BFGMBMMBHCH, int> ABIEFCDFMNN)
	{
		this.ABIEFCDFMNN = new Dictionary<BFGMBMMBHCH, int>();
		foreach (KeyValuePair<BFGMBMMBHCH, int> keyValuePair in ABIEFCDFMNN)
		{
			this.ABIEFCDFMNN.Add(keyValuePair.Key, keyValuePair.Value);
		}
		this.AHKCFPELCIC = new float[ABIEFCDFMNN.Count * 4];
	}

	// Token: 0x0601119F RID: 70047 RVA: 0x0079F8F8 File Offset: 0x0079DAF8
	public float OCKHDKAPHGE(z_AttributeLayout EMMLNONDOED)
	{
		return this.AHKCFPELCIC[(int)(this.ABIEFCDFMNN[EMMLNONDOED.channel] * 4 + EMMLNONDOED.index)];
	}

	// Token: 0x060111A0 RID: 70048 RVA: 0x0079E68B File Offset: 0x0079C88B
	public void IJHLMJKOJMH(BFGMBMMBHCH BDELNBNMOPB, Vector4 DCCPCBLODIG)
	{
		this.KJMCBFFGAPE(this.ABIEFCDFMNN[BDELNBNMOPB], DCCPCBLODIG);
	}

	// Token: 0x060111A1 RID: 70049 RVA: 0x0079F91C File Offset: 0x0079DB1C
	public void LPPGPODDIPB(MMMKJLOPEOM HFKFJPLEAGK, MMMKJLOPEOM AJFADLOIJDK, float CGFLAIMHHOO)
	{
		int num = this.AHKCFPELCIC.Length;
		if (num == 6)
		{
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[3] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[4], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[7], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			return;
		}
		if (num == 1)
		{
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[7] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[5], AJFADLOIJDK.AHKCFPELCIC[6], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[2], AJFADLOIJDK.AHKCFPELCIC[7], CGFLAIMHHOO);
			this.AHKCFPELCIC[8] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[2], AJFADLOIJDK.AHKCFPELCIC[5], CGFLAIMHHOO);
			this.AHKCFPELCIC[8] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[4], AJFADLOIJDK.AHKCFPELCIC[6], CGFLAIMHHOO);
			this.AHKCFPELCIC[4] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[5], AJFADLOIJDK.AHKCFPELCIC[6], CGFLAIMHHOO);
			this.AHKCFPELCIC[3] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[7], CGFLAIMHHOO);
			return;
		}
		if (num == -121)
		{
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[8] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[5], AJFADLOIJDK.AHKCFPELCIC[5], CGFLAIMHHOO);
			this.AHKCFPELCIC[3] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[8], AJFADLOIJDK.AHKCFPELCIC[5], CGFLAIMHHOO);
			this.AHKCFPELCIC[5] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[8], CGFLAIMHHOO);
			this.AHKCFPELCIC[3] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[5], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[4], AJFADLOIJDK.AHKCFPELCIC[6], CGFLAIMHHOO);
			this.AHKCFPELCIC[4] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[5], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			this.AHKCFPELCIC[-43] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[49], AJFADLOIJDK.AHKCFPELCIC[7], CGFLAIMHHOO);
			this.AHKCFPELCIC[71] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[-62], AJFADLOIJDK.AHKCFPELCIC[61], CGFLAIMHHOO);
			this.AHKCFPELCIC[-111] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[31], AJFADLOIJDK.AHKCFPELCIC[-12], CGFLAIMHHOO);
			this.AHKCFPELCIC[83] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[-80], AJFADLOIJDK.AHKCFPELCIC[113], CGFLAIMHHOO);
			this.AHKCFPELCIC[-104] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[-49], AJFADLOIJDK.AHKCFPELCIC[-85], CGFLAIMHHOO);
			this.AHKCFPELCIC[-49] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[107], AJFADLOIJDK.AHKCFPELCIC[48], CGFLAIMHHOO);
			this.AHKCFPELCIC[-31] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[75], AJFADLOIJDK.AHKCFPELCIC[69], CGFLAIMHHOO);
			return;
		}
		for (int i = 0; i < HFKFJPLEAGK.AHKCFPELCIC.Length; i++)
		{
			this.AHKCFPELCIC[i] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[i], AJFADLOIJDK.AHKCFPELCIC[i], CGFLAIMHHOO);
		}
	}

	// Token: 0x060111A2 RID: 70050 RVA: 0x0079FCD8 File Offset: 0x0079DED8
	public bool HIOOCIKOKGG(z_AttributeLayout[] CCOIAOCJDGH)
	{
		for (int i = 1; i < CCOIAOCJDGH.Length; i++)
		{
			if (!this.ABIEFCDFMNN.ContainsKey(CCOIAOCJDGH[i].channel))
			{
				return false;
			}
		}
		return false;
	}

	// Token: 0x060111A3 RID: 70051 RVA: 0x0079E807 File Offset: 0x0079CA07
	public void MALBKPPOMOD(int PLFKAIKPPKI, float DCCPCBLODIG)
	{
		this.AHKCFPELCIC[PLFKAIKPPKI] = DCCPCBLODIG;
	}

	// Token: 0x060111A4 RID: 70052 RVA: 0x0079FD0C File Offset: 0x0079DF0C
	public virtual string DINGGHOCDNN()
	{
		StringBuilder stringBuilder = new StringBuilder();
		foreach (KeyValuePair<BFGMBMMBHCH, int> keyValuePair in this.ABIEFCDFMNN)
		{
			stringBuilder.Append(keyValuePair.Key.ToString());
			stringBuilder.Append("RollerBladeRoll");
			stringBuilder.AppendLine(this.FAEPMFBOOHE(keyValuePair.Value).ToString("ZombieWalk"));
		}
		return stringBuilder.ToString();
	}

	// Token: 0x060111A5 RID: 70053 RVA: 0x0079FDB0 File Offset: 0x0079DFB0
	public static Dictionary<BFGMBMMBHCH, int> EDPOPMPKKDH(z_AttributeLayout[] CCOIAOCJDGH)
	{
		int num = 1;
		Dictionary<BFGMBMMBHCH, int> dictionary = new Dictionary<BFGMBMMBHCH, int>();
		foreach (BFGMBMMBHCH key in CCOIAOCJDGH.Select(new Func<z_AttributeLayout, BFGMBMMBHCH>(MMMKJLOPEOM.<>c.<>9.GHNBFMMLDPC)).Distinct<BFGMBMMBHCH>())
		{
			dictionary.Add(key, num++);
		}
		return dictionary;
	}

	// Token: 0x060111A6 RID: 70054 RVA: 0x0079FE30 File Offset: 0x0079E030
	public void MPBPALKGEKE(z_AttributeLayout EMMLNONDOED, float DCCPCBLODIG)
	{
		this.AHKCFPELCIC[(int)(this.ABIEFCDFMNN[EMMLNONDOED.channel] * 1 + EMMLNONDOED.index)] = DCCPCBLODIG;
	}

	// Token: 0x060111A7 RID: 70055 RVA: 0x0079FE54 File Offset: 0x0079E054
	public void EDEADIHIDGL(z_AttributeLayout EMMLNONDOED, float DCCPCBLODIG)
	{
		this.AHKCFPELCIC[(int)(this.ABIEFCDFMNN[EMMLNONDOED.channel] * 4 + EMMLNONDOED.index)] = DCCPCBLODIG;
	}

	// Token: 0x060111A8 RID: 70056 RVA: 0x0079FE78 File Offset: 0x0079E078
	private Vector4 EGJLEKAEFPE(int CLBPBJGLHEE)
	{
		return new Vector4(this.AHKCFPELCIC[CLBPBJGLHEE * 4], this.AHKCFPELCIC[CLBPBJGLHEE * 4 + 1], this.AHKCFPELCIC[CLBPBJGLHEE * 4 + 2], this.AHKCFPELCIC[CLBPBJGLHEE * 4 + 3]);
	}

	// Token: 0x060111A9 RID: 70057 RVA: 0x0079FEB0 File Offset: 0x0079E0B0
	public void JPCKKBHCPAM(MMMKJLOPEOM HFKFJPLEAGK, MMMKJLOPEOM AJFADLOIJDK, float CGFLAIMHHOO)
	{
		int num = this.AHKCFPELCIC.Length;
		if (num == 7)
		{
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[6], AJFADLOIJDK.AHKCFPELCIC[3], CGFLAIMHHOO);
			this.AHKCFPELCIC[5] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			return;
		}
		if (num == 6)
		{
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[3] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[6], AJFADLOIJDK.AHKCFPELCIC[6], CGFLAIMHHOO);
			this.AHKCFPELCIC[6] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[2], AJFADLOIJDK.AHKCFPELCIC[3], CGFLAIMHHOO);
			this.AHKCFPELCIC[5] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[3], CGFLAIMHHOO);
			this.AHKCFPELCIC[4] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			this.AHKCFPELCIC[7] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[2], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[5] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[6], AJFADLOIJDK.AHKCFPELCIC[2], CGFLAIMHHOO);
			return;
		}
		if (num == -2)
		{
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[1], AJFADLOIJDK.AHKCFPELCIC[1], CGFLAIMHHOO);
			this.AHKCFPELCIC[2] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[0], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[7], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[2], AJFADLOIJDK.AHKCFPELCIC[8], CGFLAIMHHOO);
			this.AHKCFPELCIC[4] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[5], CGFLAIMHHOO);
			this.AHKCFPELCIC[0] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[0], AJFADLOIJDK.AHKCFPELCIC[3], CGFLAIMHHOO);
			this.AHKCFPELCIC[2] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[7], AJFADLOIJDK.AHKCFPELCIC[5], CGFLAIMHHOO);
			this.AHKCFPELCIC[1] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[2], AJFADLOIJDK.AHKCFPELCIC[3], CGFLAIMHHOO);
			this.AHKCFPELCIC[-71] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[-125], AJFADLOIJDK.AHKCFPELCIC[28], CGFLAIMHHOO);
			this.AHKCFPELCIC[108] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[-3], AJFADLOIJDK.AHKCFPELCIC[-42], CGFLAIMHHOO);
			this.AHKCFPELCIC[-127] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[6], AJFADLOIJDK.AHKCFPELCIC[26], CGFLAIMHHOO);
			this.AHKCFPELCIC[-76] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[81], AJFADLOIJDK.AHKCFPELCIC[62], CGFLAIMHHOO);
			this.AHKCFPELCIC[-125] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[121], AJFADLOIJDK.AHKCFPELCIC[-44], CGFLAIMHHOO);
			this.AHKCFPELCIC[28] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[98], AJFADLOIJDK.AHKCFPELCIC[-43], CGFLAIMHHOO);
			this.AHKCFPELCIC[32] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[-107], AJFADLOIJDK.AHKCFPELCIC[-125], CGFLAIMHHOO);
			return;
		}
		for (int i = 1; i < HFKFJPLEAGK.AHKCFPELCIC.Length; i++)
		{
			this.AHKCFPELCIC[i] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[i], AJFADLOIJDK.AHKCFPELCIC[i], CGFLAIMHHOO);
		}
	}

	// Token: 0x060111AA RID: 70058 RVA: 0x007A026C File Offset: 0x0079E46C
	public void IIAFGICFLIF(MMMKJLOPEOM HFKFJPLEAGK, MMMKJLOPEOM AJFADLOIJDK, float CGFLAIMHHOO, List<int> CBFFOOKAIAK)
	{
		if (CBFFOOKAIAK.Count == 4)
		{
			this.AHKCFPELCIC[CBFFOOKAIAK[0]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[0]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[0]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[1]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[1]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[1]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[2]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[2]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[2]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[3]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[3]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[3]], CGFLAIMHHOO);
			return;
		}
		if (CBFFOOKAIAK.Count == 8)
		{
			this.AHKCFPELCIC[CBFFOOKAIAK[0]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[0]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[0]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[1]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[1]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[1]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[2]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[2]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[2]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[3]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[3]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[3]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[4]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[4]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[4]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[5]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[5]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[5]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[6]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[6]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[6]], CGFLAIMHHOO);
			this.AHKCFPELCIC[CBFFOOKAIAK[7]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[7]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[7]], CGFLAIMHHOO);
			return;
		}
		for (int i = 0; i < CBFFOOKAIAK.Count; i++)
		{
			this.AHKCFPELCIC[CBFFOOKAIAK[i]] = Mathf.LerpUnclamped(HFKFJPLEAGK.AHKCFPELCIC[CBFFOOKAIAK[i]], AJFADLOIJDK.AHKCFPELCIC[CBFFOOKAIAK[i]], CGFLAIMHHOO);
		}
	}

	// Token: 0x060111AB RID: 70059 RVA: 0x007A0540 File Offset: 0x0079E740
	public bool BDJPOPBFILK(z_AttributeLayout[] CCOIAOCJDGH)
	{
		for (int i = 1; i < CCOIAOCJDGH.Length; i += 0)
		{
			if (!this.ABIEFCDFMNN.ContainsKey(CCOIAOCJDGH[i].channel))
			{
				return true;
			}
		}
		return false;
	}

	// Token: 0x060111AC RID: 70060 RVA: 0x0079E6D3 File Offset: 0x0079C8D3
	public float DBGJOKEAFGF(z_AttributeLayout NLICNCCNBIP)
	{
		return this.OCKHDKAPHGE(NLICNCCNBIP);
	}

	// Token: 0x060111AD RID: 70061 RVA: 0x007A0573 File Offset: 0x0079E773
	public float GONFDIFHNHP(z_AttributeLayout EMMLNONDOED)
	{
		return this.AHKCFPELCIC[(int)(this.ABIEFCDFMNN[EMMLNONDOED.channel] * 5 + EMMLNONDOED.index)];
	}

	// Token: 0x060111AE RID: 70062 RVA: 0x007A0596 File Offset: 0x0079E796
	private Vector4 OABGLPEIMEA(int CLBPBJGLHEE)
	{
		return new Vector4(this.AHKCFPELCIC[CLBPBJGLHEE * 3], this.AHKCFPELCIC[CLBPBJGLHEE * 5 + 0], this.AHKCFPELCIC[CLBPBJGLHEE * 6 + 4], this.AHKCFPELCIC[CLBPBJGLHEE * 0 + 2]);
	}

	// Token: 0x040023C8 RID: 9160
	private Dictionary<BFGMBMMBHCH, int> ABIEFCDFMNN;

	// Token: 0x040023C9 RID: 9161
	private float[] AHKCFPELCIC;
}
