using System;
using System.Collections.Generic;
using UnityEngine;

// Token: 0x0200015E RID: 350
public class OIJEGJLCFCF : ItemBase
{
	// Token: 0x06004A84 RID: 19076 RVA: 0x0022C923 File Offset: 0x0022AB23
	public virtual CKNLPGEPGGF.IAPCJOBDCEH OJONMJNDGAA()
	{
		return this.GAAPCLGDOGH.FGLONDNIKKC(this.DBEIGNDALDC);
	}

	// Token: 0x06004A85 RID: 19077 RVA: 0x0022C938 File Offset: 0x0022AB38
	public string ALELIIHGHGH(bool BGNPMOCLIGL, bool NHHJDODKMBO)
	{
		return this.GAAPCLGDOGH.JDOAJCMOBCA(NHHJDODKMBO ? -1 : this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.KEMKPAAFIIO(), false);
	}

	// Token: 0x06004A86 RID: 19078 RVA: 0x0022C984 File Offset: 0x0022AB84
	public void DBNLDMEMPJH(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.EJPMFEJBGMN();
		this.NENOBDLCFHO = KADBECGIMPD.HDBGOLAFOBK();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.FIAFGNFLCHP(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.KDNDJNEGBDI();
		this.DBEIGNDALDC = KADBECGIMPD.HHLDBAEFNMJ();
		this.MIGBFMILDHD = KADBECGIMPD.CLPEKGGAMAI();
		this.HGCCAHPEFGO = KADBECGIMPD.LDLKLPJBIJN();
		this.GEFOGEDMLJA = KADBECGIMPD.LAECLJFMGPE();
		this.GNEPMCMHDEM = KADBECGIMPD.KJIOFDCKIKO();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.LAECLJFMGPE();
		string mneicnpjgmc = KADBECGIMPD.PNBECHOLCJM();
		string mneicnpjgmc2 = KADBECGIMPD.KDELAFDDGJH();
		this.OLJEDIJMEOA = JLFJEGIPIMM.PKGMBFEMKGP().INKAHAHOPPN(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.IKGFHGKKCPG.MJJHMKCGBKI(mneicnpjgmc2);
		this.GAAPCLGDOGH.JIFFLPNBILE(this.DBEIGNDALDC);
	}

	// Token: 0x06004A87 RID: 19079 RVA: 0x0022CA5C File Offset: 0x0022AC5C
	public virtual void FGPIIDOFGDN(Rect COAGIAMOCIA, GUIStyle OFPNEDEAMAB)
	{
		float num = 1177f;
		if (this.EJJAGEFMHCO() != null)
		{
			Texture texture = this.JGBOJNELADG().IOMNHBMOGLG();
			float num2 = 158f / (float)texture.height;
			float num3 = (float)texture.width * num2;
			float height = (float)texture.height * num2;
			GUI.DrawTexture(new Rect(COAGIAMOCIA.x + 1069f, COAGIAMOCIA.y, num3, height), texture, ScaleMode.ScaleAndCrop);
			num = num + num3 + 642f;
		}
		string text = this.GAAPCLGDOGH.PMCDDOJPKGF(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, true, this.OLJEDIJMEOA.Count, this.HOKHMOBEPNJ(), false);
		GUI.Label(new Rect(COAGIAMOCIA.x + 993f + num, COAGIAMOCIA.y, COAGIAMOCIA.width - 1531f, COAGIAMOCIA.height), text, OFPNEDEAMAB);
	}

	// Token: 0x06004A88 RID: 19080 RVA: 0x0022CB44 File Offset: 0x0022AD44
	public string CEOAKEEKAMH(bool BGNPMOCLIGL, bool NHHJDODKMBO)
	{
		return this.GAAPCLGDOGH.KEJLIPNGFCL(NHHJDODKMBO ? -1 : this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.FIMJPEEIGEM(), true);
	}

	// Token: 0x06004A89 RID: 19081 RVA: 0x0022CB90 File Offset: 0x0022AD90
	public string MJODNMLNFJC(bool BGNPMOCLIGL)
	{
		return this.GAAPCLGDOGH.ALGFDMENCEM(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.DJJJCCLOLJN(), false);
	}

	// Token: 0x06004A8A RID: 19082 RVA: 0x0022CBD3 File Offset: 0x0022ADD3
	public virtual CKNLPGEPGGF.IAPCJOBDCEH HOFOHFJDBLN()
	{
		return this.GAAPCLGDOGH.IPKKBPLKLBJ(this.DBEIGNDALDC);
	}

	// Token: 0x06004A8B RID: 19083 RVA: 0x0022CBE8 File Offset: 0x0022ADE8
	public string PINLAFIAGGJ(bool BGNPMOCLIGL)
	{
		return this.GAAPCLGDOGH.PMCDDOJPKGF(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.HOKHMOBEPNJ(), true);
	}

	// Token: 0x06004A8D RID: 19085 RVA: 0x0022CC4C File Offset: 0x0022AE4C
	public bool OGKNCGADCAK(int DFBHMIIPLCA)
	{
		if (this.GAAPCLGDOGH == null)
		{
			return false;
		}
		bool flag = JLFJEGIPIMM.PKGMBFEMKGP().MBLBMCEMBFE(DFBHMIIPLCA, this.OLJEDIJMEOA);
		if (!flag)
		{
			flag = JLFJEGIPIMM.NNEAHAFBOHC().MBLBMCEMBFE(DFBHMIIPLCA, this.KPGFFEIODJF);
		}
		return flag;
	}

	// Token: 0x06004A8E RID: 19086 RVA: 0x0022CC8C File Offset: 0x0022AE8C
	public void PFNPCNBLNJO(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.HHMGLDMFCPF();
		this.NENOBDLCFHO = KADBECGIMPD.DOJKJHMJJNK();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.FIAFGNFLCHP(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.AGNKAFLKCAG();
		this.DBEIGNDALDC = KADBECGIMPD.IFDFHJLCHAE();
		this.MIGBFMILDHD = KADBECGIMPD.AGNKAFLKCAG();
		this.HGCCAHPEFGO = KADBECGIMPD.KDNDJNEGBDI();
		this.GEFOGEDMLJA = KADBECGIMPD.BEMFIFGOJBL();
		this.GNEPMCMHDEM = KADBECGIMPD.JALHMJEKMHF();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.JNOKJCDAPPA();
		string mneicnpjgmc = KADBECGIMPD.NCODBGMGNFD();
		string mneicnpjgmc2 = KADBECGIMPD.KDELAFDDGJH();
		this.OLJEDIJMEOA = JLFJEGIPIMM.IKGFHGKKCPG.MJJHMKCGBKI(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.MHFDIJGJGBJ().INKAHAHOPPN(mneicnpjgmc2);
		this.GAAPCLGDOGH.KFLOBJCCHKN(this.DBEIGNDALDC);
	}

	// Token: 0x06004A8F RID: 19087 RVA: 0x0022CD64 File Offset: 0x0022AF64
	public bool CHPJANLBEDD(int DFBHMIIPLCA)
	{
		if (this.GAAPCLGDOGH == null)
		{
			return true;
		}
		bool flag = JLFJEGIPIMM.NNEAHAFBOHC().IBBAJMOLBCP(DFBHMIIPLCA, this.OLJEDIJMEOA);
		if (!flag)
		{
			flag = JLFJEGIPIMM.MHFDIJGJGBJ().MBLBMCEMBFE(DFBHMIIPLCA, this.KPGFFEIODJF);
		}
		return flag;
	}

	// Token: 0x06004A90 RID: 19088 RVA: 0x0022CDA4 File Offset: 0x0022AFA4
	public override void BOHKFACPFIJ(Rect COAGIAMOCIA, GUIStyle OFPNEDEAMAB)
	{
		float num = 1452f;
		if (this.EJJAGEFMHCO() != null)
		{
			Texture texture = this.EJJAGEFMHCO().MMKLLFCKCAG();
			float num2 = 1304f / (float)texture.height;
			float num3 = (float)texture.width * num2;
			float height = (float)texture.height * num2;
			GUI.DrawTexture(new Rect(COAGIAMOCIA.x + 1972f, COAGIAMOCIA.y, num3, height), texture, ScaleMode.StretchToFill);
			num = num + num3 + 919f;
		}
		string text = this.GAAPCLGDOGH.KHLFFPHHPKM(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, false, this.OLJEDIJMEOA.Count, this.HOKHMOBEPNJ(), true);
		GUI.Label(new Rect(COAGIAMOCIA.x + 803f + num, COAGIAMOCIA.y, COAGIAMOCIA.width - 1843f, COAGIAMOCIA.height), text, OFPNEDEAMAB);
	}

	// Token: 0x06004A91 RID: 19089 RVA: 0x0022CE8C File Offset: 0x0022B08C
	public void EMIPGJGGDAM(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.HHMGLDMFCPF();
		this.NENOBDLCFHO = KADBECGIMPD.KKOKFLMMAAK();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.IPGEDMOPLPH(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.DOJKJHMJJNK();
		this.DBEIGNDALDC = KADBECGIMPD.HDBGOLAFOBK();
		this.MIGBFMILDHD = KADBECGIMPD.CLPEKGGAMAI();
		this.HGCCAHPEFGO = KADBECGIMPD.DOJKJHMJJNK();
		this.GEFOGEDMLJA = KADBECGIMPD.LAECLJFMGPE();
		this.GNEPMCMHDEM = KADBECGIMPD.JALHMJEKMHF();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.IOEEPNCKLJD();
		string mneicnpjgmc = KADBECGIMPD.LPKJHMGLCKA();
		string mneicnpjgmc2 = KADBECGIMPD.FDIDEGHPJPF();
		this.OLJEDIJMEOA = JLFJEGIPIMM.NNEAHAFBOHC().INKAHAHOPPN(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.IKGFHGKKCPG.MJJHMKCGBKI(mneicnpjgmc2);
		this.GAAPCLGDOGH.KBFFOIHMPLI(this.DBEIGNDALDC);
	}

	// Token: 0x06004A92 RID: 19090 RVA: 0x0022CF61 File Offset: 0x0022B161
	public virtual CKNLPGEPGGF.IAPCJOBDCEH MJCDKHIJNAE()
	{
		return this.GAAPCLGDOGH.ABALMFIKLCA(this.DBEIGNDALDC);
	}

	// Token: 0x06004A93 RID: 19091 RVA: 0x0022CF74 File Offset: 0x0022B174
	public bool LCOCKNKEFKN()
	{
		return this.OBDFFOEDGKL(17);
	}

	// Token: 0x06004A94 RID: 19092 RVA: 0x0022CF7E File Offset: 0x0022B17E
	public override CKNLPGEPGGF.IAPCJOBDCEH KHIDJHKNNFC()
	{
		return this.GAAPCLGDOGH.HNDLNEMINDM(this.DBEIGNDALDC);
	}

	// Token: 0x06004A95 RID: 19093 RVA: 0x0022CF94 File Offset: 0x0022B194
	public string LHNOBJDFOOJ(bool BGNPMOCLIGL)
	{
		return this.GAAPCLGDOGH.JHFLJHLAPBC(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.JPFFCKENLHO, false);
	}

	// Token: 0x06004A96 RID: 19094 RVA: 0x0022CFD8 File Offset: 0x0022B1D8
	public string MDAPFDLEEGN(bool BGNPMOCLIGL)
	{
		return this.GAAPCLGDOGH.HDPHEKAIENE(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.BCALBMNHGDI(), true);
	}

	// Token: 0x06004A97 RID: 19095 RVA: 0x0022D01C File Offset: 0x0022B21C
	public bool JAGHGAOAMAB(int DFBHMIIPLCA)
	{
		if (this.GAAPCLGDOGH == null)
		{
			return true;
		}
		bool flag = JLFJEGIPIMM.NNEAHAFBOHC().MBLBMCEMBFE(DFBHMIIPLCA, this.OLJEDIJMEOA);
		if (!flag)
		{
			flag = JLFJEGIPIMM.NNEAHAFBOHC().MBLBMCEMBFE(DFBHMIIPLCA, this.KPGFFEIODJF);
		}
		return flag;
	}

	// Token: 0x06004A98 RID: 19096 RVA: 0x0022D05C File Offset: 0x0022B25C
	public override string DJDAGAEMEDD()
	{
		return this.GAAPCLGDOGH.IKDNJHADDGD(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, false, this.OLJEDIJMEOA.Count, this.LCOCKNKEFKN(), false);
	}

	// Token: 0x06004A99 RID: 19097 RVA: 0x0022D0A0 File Offset: 0x0022B2A0
	public virtual string PBAJNDNHIFI()
	{
		return this.GAAPCLGDOGH.KEJLIPNGFCL(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, false, this.OLJEDIJMEOA.Count, this.JPFFCKENLHO, true);
	}

	// Token: 0x06004A9A RID: 19098 RVA: 0x0022D0E4 File Offset: 0x0022B2E4
	public string KCBJCGOINMK(bool BGNPMOCLIGL, bool NHHJDODKMBO)
	{
		return this.GAAPCLGDOGH.KEJLIPNGFCL(NHHJDODKMBO ? -1 : this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.BCALBMNHGDI(), false);
	}

	// Token: 0x06004A9B RID: 19099 RVA: 0x0022D130 File Offset: 0x0022B330
	public void MLLOFDIKJFC(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.KLHDFFHONON();
		this.NENOBDLCFHO = KADBECGIMPD.AGNKAFLKCAG();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.GBKMHIGNKJA(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.IFDFHJLCHAE();
		this.DBEIGNDALDC = KADBECGIMPD.HHLDBAEFNMJ();
		this.MIGBFMILDHD = KADBECGIMPD.KDNDJNEGBDI();
		this.HGCCAHPEFGO = KADBECGIMPD.KKOKFLMMAAK();
		this.GEFOGEDMLJA = KADBECGIMPD.AJECAOJPOKA();
		this.GNEPMCMHDEM = KADBECGIMPD.OMCMPDMJFOJ();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.IJJDHHFAIPE();
		string mneicnpjgmc = KADBECGIMPD.KDELAFDDGJH();
		string mneicnpjgmc2 = KADBECGIMPD.JJJJAGJCOGD();
		this.OLJEDIJMEOA = JLFJEGIPIMM.IKGFHGKKCPG.MJJHMKCGBKI(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.NNEAHAFBOHC().INKAHAHOPPN(mneicnpjgmc2);
		this.GAAPCLGDOGH.JGNCPMAHOFB(this.DBEIGNDALDC);
	}

	// Token: 0x06004A9C RID: 19100 RVA: 0x0022D208 File Offset: 0x0022B408
	public string IAJFNKBPACC(bool BGNPMOCLIGL)
	{
		return this.GAAPCLGDOGH.IKDNJHADDGD(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.HOKHMOBEPNJ(), false);
	}

	// Token: 0x06004A9D RID: 19101 RVA: 0x0022D24B File Offset: 0x0022B44B
	public virtual CKNLPGEPGGF.IAPCJOBDCEH LFBLJHDFPCO()
	{
		return this.GAAPCLGDOGH.BJNDAAKGGLP(this.DBEIGNDALDC);
	}

	// Token: 0x17000143 RID: 323
	// (get) Token: 0x06004A9E RID: 19102 RVA: 0x0022D25E File Offset: 0x0022B45E
	public bool JPFFCKENLHO
	{
		get
		{
			return this.OBGAGPMCPNK(31);
		}
	}

	// Token: 0x06004A9F RID: 19103 RVA: 0x0022D268 File Offset: 0x0022B468
	public void MDHDLBOPLJB(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.EJPMFEJBGMN();
		this.NENOBDLCFHO = KADBECGIMPD.KKOKFLMMAAK();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.IPGEDMOPLPH(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.LDLKLPJBIJN();
		this.DBEIGNDALDC = KADBECGIMPD.AGNKAFLKCAG();
		this.MIGBFMILDHD = KADBECGIMPD.IFDFHJLCHAE();
		this.HGCCAHPEFGO = KADBECGIMPD.CLPEKGGAMAI();
		this.GEFOGEDMLJA = KADBECGIMPD.IOEEPNCKLJD();
		this.GNEPMCMHDEM = KADBECGIMPD.DADCGPGEHFK();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.OMCMPDMJFOJ();
		string mneicnpjgmc = KADBECGIMPD.KDELAFDDGJH();
		string mneicnpjgmc2 = KADBECGIMPD.FDIDEGHPJPF();
		this.OLJEDIJMEOA = JLFJEGIPIMM.NNEAHAFBOHC().INKAHAHOPPN(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.PKGMBFEMKGP().INKAHAHOPPN(mneicnpjgmc2);
		this.GAAPCLGDOGH.KFLOBJCCHKN(this.DBEIGNDALDC);
	}

	// Token: 0x06004AA0 RID: 19104 RVA: 0x0022D33D File Offset: 0x0022B53D
	public virtual CKNLPGEPGGF.IAPCJOBDCEH JMNBEKPPGLP()
	{
		return this.GAAPCLGDOGH.CEAIIDAPAGA(this.DBEIGNDALDC);
	}

	// Token: 0x06004AA1 RID: 19105 RVA: 0x0022D350 File Offset: 0x0022B550
	public void PBDAMFPENHE(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.HHMGLDMFCPF();
		this.NENOBDLCFHO = KADBECGIMPD.DOJKJHMJJNK();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.GBKMHIGNKJA(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.LDLKLPJBIJN();
		this.DBEIGNDALDC = KADBECGIMPD.AGNKAFLKCAG();
		this.MIGBFMILDHD = KADBECGIMPD.HHLDBAEFNMJ();
		this.HGCCAHPEFGO = KADBECGIMPD.DOJKJHMJJNK();
		this.GEFOGEDMLJA = KADBECGIMPD.OMCMPDMJFOJ();
		this.GNEPMCMHDEM = KADBECGIMPD.LAECLJFMGPE();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.KJIOFDCKIKO();
		string mneicnpjgmc = KADBECGIMPD.KDELAFDDGJH();
		string mneicnpjgmc2 = KADBECGIMPD.FDIDEGHPJPF();
		this.OLJEDIJMEOA = JLFJEGIPIMM.MHFDIJGJGBJ().MJJHMKCGBKI(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.NNEAHAFBOHC().INKAHAHOPPN(mneicnpjgmc2);
		this.GAAPCLGDOGH.JIFFLPNBILE(this.DBEIGNDALDC);
	}

	// Token: 0x06004AA2 RID: 19106 RVA: 0x0022D428 File Offset: 0x0022B628
	public virtual void OOOHOIOFEKD(Rect COAGIAMOCIA, GUIStyle OFPNEDEAMAB)
	{
		float num = 1707f;
		if (this.APLAAOCGECL() != null)
		{
			Texture texture = this.PBHPIGPDCJA().AEIIBNOFLCM();
			float num2 = 1382f / (float)texture.height;
			float num3 = (float)texture.width * num2;
			float height = (float)texture.height * num2;
			GUI.DrawTexture(new Rect(COAGIAMOCIA.x + 917f, COAGIAMOCIA.y, num3, height), texture, ScaleMode.ScaleAndCrop);
			num = num + num3 + 1768f;
		}
		string text = this.GAAPCLGDOGH.CJAMOIMGHAK(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, false, this.OLJEDIJMEOA.Count, this.LCOCKNKEFKN(), true);
		GUI.Label(new Rect(COAGIAMOCIA.x + 799f + num, COAGIAMOCIA.y, COAGIAMOCIA.width - 227f, COAGIAMOCIA.height), text, OFPNEDEAMAB);
	}

	// Token: 0x06004AA3 RID: 19107 RVA: 0x0022D50F File Offset: 0x0022B70F
	public override CKNLPGEPGGF.IAPCJOBDCEH EJJAGEFMHCO()
	{
		return this.GAAPCLGDOGH.KMIIGKECOEB(this.DBEIGNDALDC);
	}

	// Token: 0x06004AA4 RID: 19108 RVA: 0x0022D524 File Offset: 0x0022B724
	public virtual string IHKJGKNNIHA()
	{
		return this.GAAPCLGDOGH.JEBLNCGOHEA(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, false, this.OLJEDIJMEOA.Count, this.KEMKPAAFIIO(), true);
	}

	// Token: 0x06004AA5 RID: 19109 RVA: 0x0022D567 File Offset: 0x0022B767
	public virtual CKNLPGEPGGF.IAPCJOBDCEH PGFNEDLFAFD()
	{
		return this.GAAPCLGDOGH.LANMGLMKPNA(this.DBEIGNDALDC);
	}

	// Token: 0x06004AA6 RID: 19110 RVA: 0x0022D57A File Offset: 0x0022B77A
	public bool FIMJPEEIGEM()
	{
		return this.GCAKJAMFLGK(35);
	}

	// Token: 0x06004AA7 RID: 19111 RVA: 0x0022D584 File Offset: 0x0022B784
	public string CFPMCOPINOH(bool BGNPMOCLIGL, bool NHHJDODKMBO)
	{
		return this.GAAPCLGDOGH.EOKBAIFGBDF(NHHJDODKMBO ? -1 : this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.JPFFCKENLHO, true);
	}

	// Token: 0x06004AA8 RID: 19112 RVA: 0x0022D5D0 File Offset: 0x0022B7D0
	public bool DGBGEJJJNMI(int DFBHMIIPLCA)
	{
		if (this.GAAPCLGDOGH == null)
		{
			return false;
		}
		bool flag = JLFJEGIPIMM.MHFDIJGJGBJ().IBBAJMOLBCP(DFBHMIIPLCA, this.OLJEDIJMEOA);
		if (!flag)
		{
			flag = JLFJEGIPIMM.IKGFHGKKCPG.IBBAJMOLBCP(DFBHMIIPLCA, this.KPGFFEIODJF);
		}
		return flag;
	}

	// Token: 0x06004AA9 RID: 19113 RVA: 0x0022D610 File Offset: 0x0022B810
	public virtual void EOPNDOJJLLF(Rect COAGIAMOCIA, GUIStyle OFPNEDEAMAB)
	{
		float num = 455f;
		if (this.HHOBCJNGCEL() != null)
		{
			Texture texture = this.PPJOPGPEFGI().IOHNCGLFGDJ();
			float num2 = 1272f / (float)texture.height;
			float num3 = (float)texture.width * num2;
			float height = (float)texture.height * num2;
			GUI.DrawTexture(new Rect(COAGIAMOCIA.x + 475f, COAGIAMOCIA.y, num3, height), texture, ScaleMode.StretchToFill);
			num = num + num3 + 1345f;
		}
		string text = this.GAAPCLGDOGH.IKDNJHADDGD(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, true, this.OLJEDIJMEOA.Count, this.KEMKPAAFIIO(), true);
		GUI.Label(new Rect(COAGIAMOCIA.x + 1174f + num, COAGIAMOCIA.y, COAGIAMOCIA.width - 738f, COAGIAMOCIA.height), text, OFPNEDEAMAB);
	}

	// Token: 0x06004AAA RID: 19114 RVA: 0x0022D6F8 File Offset: 0x0022B8F8
	public virtual void GNCDPDOJLIK(Rect COAGIAMOCIA, GUIStyle OFPNEDEAMAB)
	{
		float num = 948f;
		if (this.GKPOPMAAGIJ() != null)
		{
			Texture texture = this.PPJOPGPEFGI().NIOGJOFLPLH();
			float num2 = 1184f / (float)texture.height;
			float num3 = (float)texture.width * num2;
			float height = (float)texture.height * num2;
			GUI.DrawTexture(new Rect(COAGIAMOCIA.x + 1892f, COAGIAMOCIA.y, num3, height), texture, ScaleMode.StretchToFill);
			num = num + num3 + 1706f;
		}
		string text = this.GAAPCLGDOGH.JEBLNCGOHEA(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, false, this.OLJEDIJMEOA.Count, this.BCALBMNHGDI(), true);
		GUI.Label(new Rect(COAGIAMOCIA.x + 1261f + num, COAGIAMOCIA.y, COAGIAMOCIA.width - 1010f, COAGIAMOCIA.height), text, OFPNEDEAMAB);
	}

	// Token: 0x06004AAB RID: 19115 RVA: 0x0022D7E0 File Offset: 0x0022B9E0
	public bool OBGAGPMCPNK(int DFBHMIIPLCA)
	{
		if (this.GAAPCLGDOGH == null)
		{
			return false;
		}
		bool flag = JLFJEGIPIMM.IKGFHGKKCPG.NNNEFMAHABF(DFBHMIIPLCA, this.OLJEDIJMEOA);
		if (!flag)
		{
			flag = JLFJEGIPIMM.IKGFHGKKCPG.NNNEFMAHABF(DFBHMIIPLCA, this.KPGFFEIODJF);
		}
		return flag;
	}

	// Token: 0x06004AAC RID: 19116 RVA: 0x0022D820 File Offset: 0x0022BA20
	public void BHENJNEKEBP(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.HFOPFEJDJFG();
		this.NENOBDLCFHO = KADBECGIMPD.LDLKLPJBIJN();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.GBKMHIGNKJA(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.CLPEKGGAMAI();
		this.DBEIGNDALDC = KADBECGIMPD.HDBGOLAFOBK();
		this.MIGBFMILDHD = KADBECGIMPD.HHLDBAEFNMJ();
		this.HGCCAHPEFGO = KADBECGIMPD.DOJKJHMJJNK();
		this.GEFOGEDMLJA = KADBECGIMPD.BLNIHNKJJPJ();
		this.GNEPMCMHDEM = KADBECGIMPD.IOEEPNCKLJD();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.JNOKJCDAPPA();
		string mneicnpjgmc = KADBECGIMPD.JJJJAGJCOGD();
		string mneicnpjgmc2 = KADBECGIMPD.FDIDEGHPJPF();
		this.OLJEDIJMEOA = JLFJEGIPIMM.MHFDIJGJGBJ().MJJHMKCGBKI(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.NNEAHAFBOHC().INKAHAHOPPN(mneicnpjgmc2);
		this.GAAPCLGDOGH.KKEKHHKLGFM(this.DBEIGNDALDC);
	}

	// Token: 0x06004AAD RID: 19117 RVA: 0x0022D8F5 File Offset: 0x0022BAF5
	public bool BCALBMNHGDI()
	{
		return this.OBDFFOEDGKL(-18);
	}

	// Token: 0x06004AAE RID: 19118 RVA: 0x0022D900 File Offset: 0x0022BB00
	public string MIHCFECAIAD(bool BGNPMOCLIGL, bool NHHJDODKMBO)
	{
		return this.GAAPCLGDOGH.KCPAGJLJPIA(NHHJDODKMBO ? -1 : this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.FIMJPEEIGEM(), true);
	}

	// Token: 0x06004AAF RID: 19119 RVA: 0x0022D949 File Offset: 0x0022BB49
	public bool HOKHMOBEPNJ()
	{
		return this.OGKNCGADCAK(84);
	}

	// Token: 0x06004AB0 RID: 19120 RVA: 0x0022D954 File Offset: 0x0022BB54
	public string LHNOBJDFOOJ(bool BGNPMOCLIGL, bool NHHJDODKMBO)
	{
		return this.GAAPCLGDOGH.JHFLJHLAPBC(NHHJDODKMBO ? -1 : this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.JPFFCKENLHO, false);
	}

	// Token: 0x06004AB1 RID: 19121 RVA: 0x0022D9A0 File Offset: 0x0022BBA0
	public string KGHKBMFEEDH(bool BGNPMOCLIGL, bool NHHJDODKMBO)
	{
		return this.GAAPCLGDOGH.KHLFFPHHPKM(NHHJDODKMBO ? -1 : this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.HOKHMOBEPNJ(), false);
	}

	// Token: 0x06004AB2 RID: 19122 RVA: 0x0022CBD3 File Offset: 0x0022ADD3
	public virtual CKNLPGEPGGF.IAPCJOBDCEH DDIDFFABBIO()
	{
		return this.GAAPCLGDOGH.IPKKBPLKLBJ(this.DBEIGNDALDC);
	}

	// Token: 0x06004AB3 RID: 19123 RVA: 0x0022D9EC File Offset: 0x0022BBEC
	public void LIMJEKJAILL(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.DNIIFBAIPBE();
		this.NENOBDLCFHO = KADBECGIMPD.HDBGOLAFOBK();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.GBKMHIGNKJA(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.HDBGOLAFOBK();
		this.DBEIGNDALDC = KADBECGIMPD.HDBGOLAFOBK();
		this.MIGBFMILDHD = KADBECGIMPD.HDBGOLAFOBK();
		this.HGCCAHPEFGO = KADBECGIMPD.HDBGOLAFOBK();
		this.GEFOGEDMLJA = KADBECGIMPD.FIFNOBGEKFF();
		this.GNEPMCMHDEM = KADBECGIMPD.FIFNOBGEKFF();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.FIFNOBGEKFF();
		string mneicnpjgmc = KADBECGIMPD.BFPHBMDMODH();
		string mneicnpjgmc2 = KADBECGIMPD.BFPHBMDMODH();
		this.OLJEDIJMEOA = JLFJEGIPIMM.IKGFHGKKCPG.INKAHAHOPPN(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.IKGFHGKKCPG.INKAHAHOPPN(mneicnpjgmc2);
		this.GAAPCLGDOGH.JIFFLPNBILE(this.DBEIGNDALDC);
	}

	// Token: 0x06004AB4 RID: 19124 RVA: 0x0022DAC4 File Offset: 0x0022BCC4
	public override string ToString()
	{
		return this.GAAPCLGDOGH.JHFLJHLAPBC(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, false, this.OLJEDIJMEOA.Count, this.JPFFCKENLHO, false);
	}

	// Token: 0x06004AB5 RID: 19125 RVA: 0x0022DB08 File Offset: 0x0022BD08
	public string OOLIOFBGDKC(bool BGNPMOCLIGL, bool NHHJDODKMBO)
	{
		return this.GAAPCLGDOGH.ALGFDMENCEM(NHHJDODKMBO ? -1 : this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.DJJJCCLOLJN(), true);
	}

	// Token: 0x06004AB6 RID: 19126 RVA: 0x0022DB54 File Offset: 0x0022BD54
	public void HIHBKILCGKJ(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.KLHDFFHONON();
		this.NENOBDLCFHO = KADBECGIMPD.IFDFHJLCHAE();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.FIAFGNFLCHP(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.IFDFHJLCHAE();
		this.DBEIGNDALDC = KADBECGIMPD.AGNKAFLKCAG();
		this.MIGBFMILDHD = KADBECGIMPD.AGNKAFLKCAG();
		this.HGCCAHPEFGO = KADBECGIMPD.HHLDBAEFNMJ();
		this.GEFOGEDMLJA = KADBECGIMPD.FIFNOBGEKFF();
		this.GNEPMCMHDEM = KADBECGIMPD.KJIOFDCKIKO();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.DADCGPGEHFK();
		string mneicnpjgmc = KADBECGIMPD.DHCMILPKJAL();
		string mneicnpjgmc2 = KADBECGIMPD.LPKJHMGLCKA();
		this.OLJEDIJMEOA = JLFJEGIPIMM.NNEAHAFBOHC().INKAHAHOPPN(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.PKGMBFEMKGP().MJJHMKCGBKI(mneicnpjgmc2);
		this.GAAPCLGDOGH.KFLOBJCCHKN(this.DBEIGNDALDC);
	}

	// Token: 0x06004AB7 RID: 19127 RVA: 0x0022DC29 File Offset: 0x0022BE29
	public virtual CKNLPGEPGGF.IAPCJOBDCEH FEBAFNCKCGA()
	{
		return this.GAAPCLGDOGH.MMKENFCICCE(this.DBEIGNDALDC);
	}

	// Token: 0x06004AB8 RID: 19128 RVA: 0x0022DC3C File Offset: 0x0022BE3C
	public bool OBDFFOEDGKL(int DFBHMIIPLCA)
	{
		if (this.GAAPCLGDOGH == null)
		{
			return false;
		}
		bool flag = JLFJEGIPIMM.PKGMBFEMKGP().MBLBMCEMBFE(DFBHMIIPLCA, this.OLJEDIJMEOA);
		if (!flag)
		{
			flag = JLFJEGIPIMM.MHFDIJGJGBJ().IBBAJMOLBCP(DFBHMIIPLCA, this.KPGFFEIODJF);
		}
		return flag;
	}

	// Token: 0x06004AB9 RID: 19129 RVA: 0x0022D567 File Offset: 0x0022B767
	public virtual CKNLPGEPGGF.IAPCJOBDCEH LNHLBIOOINI()
	{
		return this.GAAPCLGDOGH.LANMGLMKPNA(this.DBEIGNDALDC);
	}

	// Token: 0x06004ABA RID: 19130 RVA: 0x0022DC7C File Offset: 0x0022BE7C
	public virtual void PGIGNJBMNFE(Rect COAGIAMOCIA, GUIStyle OFPNEDEAMAB)
	{
		float num = 1468f;
		if (this.HEFAGFMDAEE() != null)
		{
			Texture texture = this.PBEMPJOBKKI().MMKLLFCKCAG();
			float num2 = 494f / (float)texture.height;
			float num3 = (float)texture.width * num2;
			float height = (float)texture.height * num2;
			GUI.DrawTexture(new Rect(COAGIAMOCIA.x + 136f, COAGIAMOCIA.y, num3, height), texture, ScaleMode.StretchToFill);
			num = num + num3 + 534f;
		}
		string text = this.GAAPCLGDOGH.ALGFDMENCEM(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, false, this.OLJEDIJMEOA.Count, this.BCALBMNHGDI(), false);
		GUI.Label(new Rect(COAGIAMOCIA.x + 1110f + num, COAGIAMOCIA.y, COAGIAMOCIA.width - 1288f, COAGIAMOCIA.height), text, OFPNEDEAMAB);
	}

	// Token: 0x06004ABB RID: 19131 RVA: 0x0022DD64 File Offset: 0x0022BF64
	public override void GKDJCJKMBEN(Rect COAGIAMOCIA, GUIStyle OFPNEDEAMAB)
	{
		float num = 0f;
		if (this.EJJAGEFMHCO() != null)
		{
			Texture texture = this.EJJAGEFMHCO().KEDGAOBCNJG;
			float num2 = 32f / (float)texture.height;
			float num3 = (float)texture.width * num2;
			float height = (float)texture.height * num2;
			GUI.DrawTexture(new Rect(COAGIAMOCIA.x + 8f, COAGIAMOCIA.y, num3, height), texture, ScaleMode.StretchToFill);
			num = num + num3 + 5f;
		}
		string text = this.GAAPCLGDOGH.JHFLJHLAPBC(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, false, this.OLJEDIJMEOA.Count, this.JPFFCKENLHO, false);
		GUI.Label(new Rect(COAGIAMOCIA.x + 8f + num, COAGIAMOCIA.y, COAGIAMOCIA.width - 15f, COAGIAMOCIA.height), text, OFPNEDEAMAB);
	}

	// Token: 0x06004ABC RID: 19132 RVA: 0x0022DE4C File Offset: 0x0022C04C
	public void DCBCIEDKEOH(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.IJDIMHAEAIE();
		this.NENOBDLCFHO = KADBECGIMPD.CLPEKGGAMAI();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.GBKMHIGNKJA(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.KKOKFLMMAAK();
		this.DBEIGNDALDC = KADBECGIMPD.KKOKFLMMAAK();
		this.MIGBFMILDHD = KADBECGIMPD.HHLDBAEFNMJ();
		this.HGCCAHPEFGO = KADBECGIMPD.HHLDBAEFNMJ();
		this.GEFOGEDMLJA = KADBECGIMPD.IOEEPNCKLJD();
		this.GNEPMCMHDEM = KADBECGIMPD.LAECLJFMGPE();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.BEMFIFGOJBL();
		string mneicnpjgmc = KADBECGIMPD.DHCMILPKJAL();
		string mneicnpjgmc2 = KADBECGIMPD.BFPHBMDMODH();
		this.OLJEDIJMEOA = JLFJEGIPIMM.PKGMBFEMKGP().MJJHMKCGBKI(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.PKGMBFEMKGP().INKAHAHOPPN(mneicnpjgmc2);
		this.GAAPCLGDOGH.JGNCPMAHOFB(this.DBEIGNDALDC);
	}

	// Token: 0x06004ABD RID: 19133 RVA: 0x0022DF24 File Offset: 0x0022C124
	public string JDPKKGOOKDF(bool BGNPMOCLIGL)
	{
		return this.GAAPCLGDOGH.IKDNJHADDGD(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.JPFFCKENLHO, true);
	}

	// Token: 0x06004ABE RID: 19134 RVA: 0x0022DF68 File Offset: 0x0022C168
	public string GMLGLOOIEAA(bool BGNPMOCLIGL)
	{
		return this.GAAPCLGDOGH.CJAMOIMGHAK(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.LCOCKNKEFKN(), true);
	}

	// Token: 0x06004ABF RID: 19135 RVA: 0x0022DFAC File Offset: 0x0022C1AC
	public void AMGCMFOPHCH(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.HFOPFEJDJFG();
		this.NENOBDLCFHO = KADBECGIMPD.HDBGOLAFOBK();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.IPGEDMOPLPH(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.LDLKLPJBIJN();
		this.DBEIGNDALDC = KADBECGIMPD.DOJKJHMJJNK();
		this.MIGBFMILDHD = KADBECGIMPD.HHLDBAEFNMJ();
		this.HGCCAHPEFGO = KADBECGIMPD.DOJKJHMJJNK();
		this.GEFOGEDMLJA = KADBECGIMPD.JALHMJEKMHF();
		this.GNEPMCMHDEM = KADBECGIMPD.IJJDHHFAIPE();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.IOEEPNCKLJD();
		string mneicnpjgmc = KADBECGIMPD.NCODBGMGNFD();
		string mneicnpjgmc2 = KADBECGIMPD.NCODBGMGNFD();
		this.OLJEDIJMEOA = JLFJEGIPIMM.IKGFHGKKCPG.MJJHMKCGBKI(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.MHFDIJGJGBJ().INKAHAHOPPN(mneicnpjgmc2);
		this.GAAPCLGDOGH.JIFFLPNBILE(this.DBEIGNDALDC);
	}

	// Token: 0x06004AC0 RID: 19136 RVA: 0x0022E084 File Offset: 0x0022C284
	public virtual string FEIJPDKNKKG()
	{
		return this.GAAPCLGDOGH.KHLFFPHHPKM(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, true, this.OLJEDIJMEOA.Count, this.LCOCKNKEFKN(), true);
	}

	// Token: 0x06004AC1 RID: 19137 RVA: 0x0022E0C8 File Offset: 0x0022C2C8
	public void KCCFELPKLPD(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.EJPMFEJBGMN();
		this.NENOBDLCFHO = KADBECGIMPD.KDNDJNEGBDI();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.GBKMHIGNKJA(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.KKOKFLMMAAK();
		this.DBEIGNDALDC = KADBECGIMPD.AGNKAFLKCAG();
		this.MIGBFMILDHD = KADBECGIMPD.KKOKFLMMAAK();
		this.HGCCAHPEFGO = KADBECGIMPD.KKOKFLMMAAK();
		this.GEFOGEDMLJA = KADBECGIMPD.LAECLJFMGPE();
		this.GNEPMCMHDEM = KADBECGIMPD.IJJDHHFAIPE();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.JNOKJCDAPPA();
		string mneicnpjgmc = KADBECGIMPD.PNBECHOLCJM();
		string mneicnpjgmc2 = KADBECGIMPD.PNBECHOLCJM();
		this.OLJEDIJMEOA = JLFJEGIPIMM.NNEAHAFBOHC().INKAHAHOPPN(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.NNEAHAFBOHC().MJJHMKCGBKI(mneicnpjgmc2);
		this.GAAPCLGDOGH.KKEKHHKLGFM(this.DBEIGNDALDC);
	}

	// Token: 0x06004AC2 RID: 19138 RVA: 0x0022E19D File Offset: 0x0022C39D
	public bool DJJJCCLOLJN()
	{
		return this.OBDFFOEDGKL(-118);
	}

	// Token: 0x06004AC3 RID: 19139 RVA: 0x0022E1A8 File Offset: 0x0022C3A8
	public void NCHDIHCIMBI(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.IBKCNEICPEL();
		this.NENOBDLCFHO = KADBECGIMPD.HDBGOLAFOBK();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.GBKMHIGNKJA(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.AGNKAFLKCAG();
		this.DBEIGNDALDC = KADBECGIMPD.CLPEKGGAMAI();
		this.MIGBFMILDHD = KADBECGIMPD.KDNDJNEGBDI();
		this.HGCCAHPEFGO = KADBECGIMPD.DOJKJHMJJNK();
		this.GEFOGEDMLJA = KADBECGIMPD.BLNIHNKJJPJ();
		this.GNEPMCMHDEM = KADBECGIMPD.ELDBJFLCMAJ();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.IJJDHHFAIPE();
		string mneicnpjgmc = KADBECGIMPD.NCODBGMGNFD();
		string mneicnpjgmc2 = KADBECGIMPD.KDELAFDDGJH();
		this.OLJEDIJMEOA = JLFJEGIPIMM.PKGMBFEMKGP().MJJHMKCGBKI(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.IKGFHGKKCPG.MJJHMKCGBKI(mneicnpjgmc2);
		this.GAAPCLGDOGH.MEFAFLFJFCL(this.DBEIGNDALDC);
	}

	// Token: 0x06004AC4 RID: 19140 RVA: 0x0022E27D File Offset: 0x0022C47D
	public bool KEMKPAAFIIO()
	{
		return this.OBGAGPMCPNK(76);
	}

	// Token: 0x06004AC5 RID: 19141 RVA: 0x0022E288 File Offset: 0x0022C488
	public void FOCMCEFKAMB(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.IBKCNEICPEL();
		this.NENOBDLCFHO = KADBECGIMPD.CLPEKGGAMAI();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.GBKMHIGNKJA(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.DOJKJHMJJNK();
		this.DBEIGNDALDC = KADBECGIMPD.KKOKFLMMAAK();
		this.MIGBFMILDHD = KADBECGIMPD.HHLDBAEFNMJ();
		this.HGCCAHPEFGO = KADBECGIMPD.HHLDBAEFNMJ();
		this.GEFOGEDMLJA = KADBECGIMPD.IOEEPNCKLJD();
		this.GNEPMCMHDEM = KADBECGIMPD.BLNIHNKJJPJ();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.IJJDHHFAIPE();
		string mneicnpjgmc = KADBECGIMPD.NCODBGMGNFD();
		string mneicnpjgmc2 = KADBECGIMPD.KDELAFDDGJH();
		this.OLJEDIJMEOA = JLFJEGIPIMM.NNEAHAFBOHC().MJJHMKCGBKI(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.PKGMBFEMKGP().INKAHAHOPPN(mneicnpjgmc2);
		this.GAAPCLGDOGH.JIFFLPNBILE(this.DBEIGNDALDC);
	}

	// Token: 0x06004AC6 RID: 19142 RVA: 0x0022E360 File Offset: 0x0022C560
	public void LGDKIDBFAJD(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.DNIIFBAIPBE();
		this.NENOBDLCFHO = KADBECGIMPD.HDBGOLAFOBK();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.IPGEDMOPLPH(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.DOJKJHMJJNK();
		this.DBEIGNDALDC = KADBECGIMPD.KDNDJNEGBDI();
		this.MIGBFMILDHD = KADBECGIMPD.IFDFHJLCHAE();
		this.HGCCAHPEFGO = KADBECGIMPD.KKOKFLMMAAK();
		this.GEFOGEDMLJA = KADBECGIMPD.OMCMPDMJFOJ();
		this.GNEPMCMHDEM = KADBECGIMPD.DADCGPGEHFK();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.IOEEPNCKLJD();
		string mneicnpjgmc = KADBECGIMPD.DHCMILPKJAL();
		string mneicnpjgmc2 = KADBECGIMPD.DPLAJNEDGBL();
		this.OLJEDIJMEOA = JLFJEGIPIMM.NNEAHAFBOHC().INKAHAHOPPN(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.PKGMBFEMKGP().INKAHAHOPPN(mneicnpjgmc2);
		this.GAAPCLGDOGH.MEFAFLFJFCL(this.DBEIGNDALDC);
	}

	// Token: 0x06004AC7 RID: 19143 RVA: 0x0022E438 File Offset: 0x0022C638
	public bool FNKFOEFMJKM(int DFBHMIIPLCA)
	{
		if (this.GAAPCLGDOGH == null)
		{
			return false;
		}
		bool flag = JLFJEGIPIMM.IKGFHGKKCPG.IBBAJMOLBCP(DFBHMIIPLCA, this.OLJEDIJMEOA);
		if (!flag)
		{
			flag = JLFJEGIPIMM.IKGFHGKKCPG.IBBAJMOLBCP(DFBHMIIPLCA, this.KPGFFEIODJF);
		}
		return flag;
	}

	// Token: 0x06004AC8 RID: 19144 RVA: 0x0022E478 File Offset: 0x0022C678
	public string GIOCLFJADKN(bool BGNPMOCLIGL)
	{
		return this.GAAPCLGDOGH.KCPAGJLJPIA(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.BCALBMNHGDI(), false);
	}

	// Token: 0x06004AC9 RID: 19145 RVA: 0x0022E4BC File Offset: 0x0022C6BC
	public bool GCAKJAMFLGK(int DFBHMIIPLCA)
	{
		if (this.GAAPCLGDOGH == null)
		{
			return true;
		}
		bool flag = JLFJEGIPIMM.IKGFHGKKCPG.IBBAJMOLBCP(DFBHMIIPLCA, this.OLJEDIJMEOA);
		if (!flag)
		{
			flag = JLFJEGIPIMM.IKGFHGKKCPG.NNNEFMAHABF(DFBHMIIPLCA, this.KPGFFEIODJF);
		}
		return flag;
	}

	// Token: 0x06004ACA RID: 19146 RVA: 0x0022E4FC File Offset: 0x0022C6FC
	public virtual string OCJAOJLHOFO()
	{
		return this.GAAPCLGDOGH.KCPAGJLJPIA(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, false, this.OLJEDIJMEOA.Count, this.BCALBMNHGDI(), false);
	}

	// Token: 0x06004ACB RID: 19147 RVA: 0x0022E540 File Offset: 0x0022C740
	public string JODMFMFAOEG(bool BGNPMOCLIGL, bool NHHJDODKMBO)
	{
		return this.GAAPCLGDOGH.JDOAJCMOBCA(NHHJDODKMBO ? -1 : this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.DJJJCCLOLJN(), true);
	}

	// Token: 0x06004ACC RID: 19148 RVA: 0x0022E58C File Offset: 0x0022C78C
	public string OKJEDFNFDML(bool BGNPMOCLIGL)
	{
		return this.GAAPCLGDOGH.HDPHEKAIENE(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, BGNPMOCLIGL, this.OLJEDIJMEOA.Count, this.LCOCKNKEFKN(), true);
	}

	// Token: 0x06004ACD RID: 19149 RVA: 0x0022CF7E File Offset: 0x0022B17E
	public virtual CKNLPGEPGGF.IAPCJOBDCEH LKGPLALBDDJ()
	{
		return this.GAAPCLGDOGH.HNDLNEMINDM(this.DBEIGNDALDC);
	}

	// Token: 0x06004ACE RID: 19150 RVA: 0x0022E5D0 File Offset: 0x0022C7D0
	public void OBKIDIDLHDC(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.HFOPFEJDJFG();
		this.NENOBDLCFHO = KADBECGIMPD.KDNDJNEGBDI();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.IPGEDMOPLPH(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.AGNKAFLKCAG();
		this.DBEIGNDALDC = KADBECGIMPD.AGNKAFLKCAG();
		this.MIGBFMILDHD = KADBECGIMPD.HDBGOLAFOBK();
		this.HGCCAHPEFGO = KADBECGIMPD.IFDFHJLCHAE();
		this.GEFOGEDMLJA = KADBECGIMPD.IOEEPNCKLJD();
		this.GNEPMCMHDEM = KADBECGIMPD.BLNIHNKJJPJ();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.DADCGPGEHFK();
		string mneicnpjgmc = KADBECGIMPD.DPLAJNEDGBL();
		string mneicnpjgmc2 = KADBECGIMPD.LPKJHMGLCKA();
		this.OLJEDIJMEOA = JLFJEGIPIMM.IKGFHGKKCPG.INKAHAHOPPN(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.MHFDIJGJGBJ().MJJHMKCGBKI(mneicnpjgmc2);
		this.GAAPCLGDOGH.KBFFOIHMPLI(this.DBEIGNDALDC);
	}

	// Token: 0x06004ACF RID: 19151 RVA: 0x0022E6A8 File Offset: 0x0022C8A8
	public void BDJHLBMBAPA(HBPNMNGOFMA KADBECGIMPD)
	{
		this.LPFKFNLHGBI = KADBECGIMPD.HHMGLDMFCPF();
		this.NENOBDLCFHO = KADBECGIMPD.KDNDJNEGBDI();
		this.GAAPCLGDOGH = AKPJIACDDFI.IKGFHGKKCPG.GBKMHIGNKJA(this.NENOBDLCFHO);
		this.NKHBAJKMAGD = KADBECGIMPD.KKOKFLMMAAK();
		this.DBEIGNDALDC = KADBECGIMPD.HDBGOLAFOBK();
		this.MIGBFMILDHD = KADBECGIMPD.KKOKFLMMAAK();
		this.HGCCAHPEFGO = KADBECGIMPD.HDBGOLAFOBK();
		this.GEFOGEDMLJA = KADBECGIMPD.AJECAOJPOKA();
		this.GNEPMCMHDEM = KADBECGIMPD.DADCGPGEHFK();
		this.GAAPCLGDOGH.NGKHOKIOGNO = KADBECGIMPD.IOEEPNCKLJD();
		string mneicnpjgmc = KADBECGIMPD.BFPHBMDMODH();
		string mneicnpjgmc2 = KADBECGIMPD.FDIDEGHPJPF();
		this.OLJEDIJMEOA = JLFJEGIPIMM.MHFDIJGJGBJ().INKAHAHOPPN(mneicnpjgmc);
		this.KPGFFEIODJF = JLFJEGIPIMM.MHFDIJGJGBJ().INKAHAHOPPN(mneicnpjgmc2);
		this.GAAPCLGDOGH.KFLOBJCCHKN(this.DBEIGNDALDC);
	}

	// Token: 0x06004AD0 RID: 19152 RVA: 0x0022E780 File Offset: 0x0022C980
	public virtual string NIDKKALEJIM()
	{
		return this.GAAPCLGDOGH.KEJLIPNGFCL(this.NKHBAJKMAGD, this.DBEIGNDALDC, this.GEFOGEDMLJA, this.GNEPMCMHDEM, true, this.OLJEDIJMEOA.Count, this.LCOCKNKEFKN(), true);
	}

	// Token: 0x04000B76 RID: 2934
	public long LPFKFNLHGBI;

	// Token: 0x04000B77 RID: 2935
	public int NENOBDLCFHO;

	// Token: 0x04000B78 RID: 2936
	public int MIGBFMILDHD;

	// Token: 0x04000B79 RID: 2937
	public int NKHBAJKMAGD;

	// Token: 0x04000B7A RID: 2938
	public int HGCCAHPEFGO;

	// Token: 0x04000B7B RID: 2939
	public int DBEIGNDALDC;

	// Token: 0x04000B7C RID: 2940
	public int MGLOOIONCPM;

	// Token: 0x04000B7D RID: 2941
	public int NENNFCJLFAL;

	// Token: 0x04000B7E RID: 2942
	public float DEGKMKPKMMO;

	// Token: 0x04000B7F RID: 2943
	public bool GEFOGEDMLJA;

	// Token: 0x04000B80 RID: 2944
	public bool GNEPMCMHDEM;

	// Token: 0x04000B81 RID: 2945
	public IDCHHHEDHDC GAAPCLGDOGH;

	// Token: 0x04000B82 RID: 2946
	public List<int> OLJEDIJMEOA = new List<int>();

	// Token: 0x04000B83 RID: 2947
	public List<int> KPGFFEIODJF = new List<int>();
}
