using System;
using UnityEngine;

// Token: 0x02000505 RID: 1285
public static class POKHFFPGFLO
{
	// Token: 0x060112AB RID: 70315 RVA: 0x007A2CD0 File Offset: 0x007A0ED0
	public static void BGBLGGJCIKN(Vector3 EGABJKIFAON, Vector3 HHAGIHEGFML, ref float OCNGPCPMCPM, ref float ADMFAEOOOHD, ref float DOCOLPILEAF)
	{
		OCNGPCPMCPM = EGABJKIFAON.y * HHAGIHEGFML.z - EGABJKIFAON.z * HHAGIHEGFML.y;
		ADMFAEOOOHD = EGABJKIFAON.z * HHAGIHEGFML.x - EGABJKIFAON.x * HHAGIHEGFML.z;
		DOCOLPILEAF = EGABJKIFAON.x * HHAGIHEGFML.y - EGABJKIFAON.y * HHAGIHEGFML.x;
	}

	// Token: 0x060112AC RID: 70316 RVA: 0x007A2D38 File Offset: 0x007A0F38
	public static void BGBLGGJCIKN(Vector3 EGABJKIFAON, Vector3 HHAGIHEGFML, ref Vector3 LGABPAHHIDP)
	{
		LGABPAHHIDP.x = EGABJKIFAON.y * HHAGIHEGFML.z - EGABJKIFAON.z * HHAGIHEGFML.y;
		LGABPAHHIDP.y = EGABJKIFAON.z * HHAGIHEGFML.x - EGABJKIFAON.x * HHAGIHEGFML.z;
		LGABPAHHIDP.z = EGABJKIFAON.x * HHAGIHEGFML.y - EGABJKIFAON.y * HHAGIHEGFML.x;
	}

	// Token: 0x060112AD RID: 70317 RVA: 0x007A2DA8 File Offset: 0x007A0FA8
	public static void BGBLGGJCIKN(float HDNCFNLAHHC, float JIIPIJCBBFO, float NHFDKNBEFOE, float AIGCCMNDLGB, float IHOEANCBABJ, float BDKOBLFJHHE, ref float OCNGPCPMCPM, ref float ADMFAEOOOHD, ref float DOCOLPILEAF)
	{
		OCNGPCPMCPM = JIIPIJCBBFO * BDKOBLFJHHE - NHFDKNBEFOE * IHOEANCBABJ;
		ADMFAEOOOHD = NHFDKNBEFOE * AIGCCMNDLGB - HDNCFNLAHHC * BDKOBLFJHHE;
		DOCOLPILEAF = HDNCFNLAHHC * IHOEANCBABJ - JIIPIJCBBFO * AIGCCMNDLGB;
	}

	// Token: 0x060112AE RID: 70318 RVA: 0x007A2DCC File Offset: 0x007A0FCC
	public static void FLBIMMKKNDL(Vector3 EGABJKIFAON, Vector3 HHAGIHEGFML, ref Vector3 LGABPAHHIDP)
	{
		LGABPAHHIDP.x = HHAGIHEGFML.x - EGABJKIFAON.x;
		LGABPAHHIDP.y = HHAGIHEGFML.y - EGABJKIFAON.y;
		LGABPAHHIDP.z = HHAGIHEGFML.z - EGABJKIFAON.z;
	}
}
